[[toc2_02]]
=== 既存資料の把握

「既存資料」には、都市計画基本図や基盤地図情報のような地物型の空間属性（位置や形状）の情報が含まれる資料（地図・図面）や、都市計画基礎調査のような地物型の時間属性や主題属性が含まれる資料（調書・台帳）が存在する。また、これらには、地方公共団体等の行政機関が保有するデータ、一般に公開されている((オープンデータ))、そして、民間企業等が販売するアーカイブデータがある。 +
ここでは、拡張製品仕様として定義された地物型等の情報が含まれる可能性のある既存資料を把握する。

(((3D都市モデル)))(((オープンデータ)))(((土地利用)))
手順：

1）既存資料の有無を調査する。

拡張製品仕様により、原典資料（データ取得の拠り所となる資料）として利用可能な既存資料は異なるが、例えば以下に示す資料の活用が想定される。

* 地方公共団体等の行政機関が保有するデータ
** 都市計画基本図、都市計画図、都市計画基礎調査、都市計画決定図書、数値地形図（DM）データ、公共測量成果（地上レーザ測量、車載写真レーザ測量、UAV写真測量、空中写真測量、航空レーザ測量、地上レーザ点群測量、UAV写真点群測量等、作業規程の準則に基づく各種公共測量における測量成果）、3D都市モデル、道路基盤地図情報、道路台帳及び道路台帳附図、道路施設台帳、指定道路図、路線網図、工事完成図書、下水道台帳及び下水道台帳付図（施設平面図）
* オープンデータ
** 基盤地図情報（基本項目、数値標高モデル）、<<nlftp,国土数値情報>>（例：洪水浸水想定区域、津波浸水想定、土砂災害警戒区域、土地利用細分メッシュデータ）
** 統計データ（全国道路・街路交通情勢調査一般交通量調査）
* 民間企業が販売するアーカイブデータ
** レーザ点群データ、航空写真、地図データ

地方公共団体等の行政機関が保有する都市計画基本図や数値地形図データは、主として3D都市モデルの幾何オブジェクトを作成する際に使用する。また、航空写真やレーザ点群データ等の公共測量成果は、幾何オブジェクトに高さを付与するために使用する。都市計画基礎調査、道路基盤地図情報、道路台帳等の法定図書、統計データは3D都市モデルの主題属性を付与するために使用する。

2）1）で存在が確認された資料について、データ形式、整備項目、整備範囲、整備時点、品質、利用条件及び更新頻度等を整理する。

* 整備した3D都市モデルが様々な分野・用途でも活用されるよう、オープンデータ化を念頭に置いて、既存資料の整理をすること。

　

[NOTE,type=commentary]
--
3D都市モデルの整備に使用する資料・データとして、地方公共団体が法定図書の整備に伴い収集・整備する資料・データが想定される。ユースケースによって収集済みの資料やデータでは不足する場合は、オープンデータや民間企業が販売するアーカイブデータの使用も検討する。

既存資料の活用においては、データ形式や整備項目・整備範囲のみならず、整備時点や品質も調査し、ユースケースの要件を満たす情報が含まれていることを確認すること。さらに、ユースケース（3D都市モデルのオープンデータ化も含む）が既存資料の利用条件に抵触していないかに留意すること。合わせて、データ整備後の更新を考慮し、更新頻度も確認しておくとよい。
--

