[[tocL_08]]
=== brid:_BoundarySurface

brid:_BoundarySurfaceは、橋梁（brid:Bridge）や橋梁部分（brid:BridgePart）の屋根面、壁面及び底面等の境界面を表す地物型である。橋梁モデル（LOD2）、橋梁モデル（LOD3）及び橋梁モデル（LOD4）を作成する際に使用される。 +
この地物型は抽象地物であり、実装においてはこの下位型の具象となる地物型を使用する。


[requirement]
.brid:_BoundarySurfaceの種類
====
[%metadata]
identifier:: /req/brid/11
subject:: 妥当な橋梁データセットの要件
description:: brid:_BoundarySurfaceは、屋根面（brid:RoofSurface）、外壁面（brid:WallSurface）、底面（brid:GroundSurface）、外部床面（brid:OuterFloorSurface）外部天井面（brid:OuterCeillingSurface）、内壁面（brid:InteriorWallSurface）、天井面（brid:CeilingSurface）、床面（brid:FloorSurface）、閉鎖面（brid:ClosureSurface）のいずれかとなる。
====

CityGMLでは、橋梁の境界面としてbrid:_BoundarySurfaceの下位型となる地物型が用意されている。地物型には、屋根面や外壁面、底面などがあるが、これら境界面の空間属性（面）は、橋梁の立体を構成する境界面に一致する。


[requirement]
.橋梁の境界面参照条件
====
[%metadata]
identifier:: /req/brid/12
subject:: 妥当な橋梁データセットの要件
description:: 橋梁及び橋梁部分の立体又は面を構成する境界面は、境界面の空間属性を構成する幾何オブジェクトを参照しなければならない。
====


==== 境界面の下位型

===== brid:RoofSurface

brid:RoofSurfaceは、橋梁の屋根面を記述するために使用する地物型である。

===== brid:WallSurface

brid:WallSurfaceは、橋梁の壁面を記述するために使用する地物型である。

===== brid:GroundSurface

brid:GroundSurfaceは、橋梁の底面を記述するために使用する地物型である。

===== brid:OuterFloorSurface

brid:OuterFloorSurfaceは橋梁の外側を覆う部分であり、通行可能な床面としての機能を有する部分の記述に使用する地物型である。

===== brid:ClosureSurface

brid:ClosureSurfaceは、橋梁部分を用いて橋梁を複数に分ける場合に、その境界面として利用する仮想的な面である。また、建屋がある橋梁について開口部が存在するが、開口部内の詳細なデータ作成が不要である場合に、開口部を閉じるために使用できる。

===== brid:OuterCeilingSurface

brid:OuterCeilingSurfaceは、橋梁の外側を覆う部分であり、天井としての機能を有する面を記述するために使用する地物型である。

===== brid:CeilingSurface

brid:CeilingSurfaceは、橋梁の内部の天井面を記述するために使用する地物型である。

===== brid:InteriorWallSurface

brid:InteriorWallSurfaceは、橋梁の内部空間の区画を区切る壁や仕切りとしての機能を有する面を記述するために使用する地物型である。

===== brid:FloorSurface

brid:FloorSurfaceは、橋梁の内部空間の下面に位置する水平で平らな板状の構造物（床面）を記述するために使用する地物型である。

