[[toc9_04]]
=== テクスチャのための標準製品仕様

本項では、建築物の外観（app:Apperance）に使用する画像（テクスチャ）の標準的な仕様を定める。使用する画像の諸元を以下に示す。

[[toc9_04_01]]
==== 画像の仕様

使用する画像の仕様を<<tab-9-1>>に示す。

[[tab-9-1]]
[cols="1a,3a"]
.画像の製品仕様
|===
h| 形式 | JPG（拡張子は.jpg）又はPNG（拡張子は.png）とする。
h| サイズ
| 高さ及び幅の各辺長のサイズは2の累乗とし、2048ピクセル以下とすることを基本とする。 +
ただし、大規模な建築物等では、各辺を4096ピクセルとすることを可とする。 +
高さ及び幅は異なる辺長として良い。

h| 解像度
| 解像度は、10㎝/pixel以下を基本とする。 +
ただし、ユースケースが必要とする場合は10㎝/pixel以上の高解像画像を用いることを可能とするが、高解像画像を広域に用いた場合に描画負荷が大きいことに留意する。

h| ファイル単位
| パフォーマンスの観点から複数の地物のテクスチャを1つの画像ファイルにまとめること（アトラス化）を推奨する。 +
アトラス化の単位は、1つのCityGMLファイルを上限とする。画像サイズは一辺2048ピクセル以下（辺長サイズは2の累乗）を基本とし、一辺4096ピクセルを上限とする。 +
ただし、大規模な地物などで1つあたりのテクスチャサイズが画像サイズの上限（一辺4096ピクセル）を超える場合は、画像ファイルを分割してもよい。

h| 背景色
| 背景色は、黒（R,G,B:0,0,0）を基本とする。 +
ただし、建築物モデルの色調との調和を考慮し、灰色（R,G,B：90,90,90等）を設定してよい。

|===

[[toc9_04_02]]
==== テクスチャの実装仕様

地物の外観に画像を貼る場合は、アピアランスモデル（app:Appearance）を使用する。アピアランスモデルは、テクスチャとして使用する画像への参照、地物に貼り付けたい画像の部分を切り出すための画像上の座標、切り出した画像の貼り付けたい地物の面への参照により構成する。 +
画像への参照及び貼り付けたい地物の面への参照は、相対パスを使用する。 +
画像上の座標値の指定は、UV座標を用いる。UV座標とは、横方向をU軸、縦方向をV軸とする2次元の直交座標系に基づく座標であり、その座標値は、左下を原点（0.0,0.0）、右上を（1.0,1.0）とする0から1までの小数値で表現される。

