[[toc_03]]
[bibliography]
== 参考文献

// 20250202 rwp a couple more missing bib records noticed during a local build.

* [[[citygml_20,OGC 12-019]]]

* [[[iso_6707-1,ISO 6707-1]]]



// 20250201 rwp sync missing bib records from doc01

* [[[nlftp,1]]]
span:title[国土数値情報].
span:organization[国土交通省 政策統括官付 地理空間情報課].
span:date[2024].
span:uri.citation[https://nlftp.mlit.go.jp].

* [[[mlit_int_flood_guidelines,13]]]
span:title[内水浸水想定区域図作成マニュアル（案）].
span:organization[国土交通省 水管理・国土保全局 下水道部].
span:date[2021-07].
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/pdf/naisui_manual.pdf]

* [[[maff_reservoir_hazard_maps,18]]]
span:title[ため池ハザードマップ作成の手引き].
span:organization[農林水産省 農村振興局 防災課].
span:date[2013-05].
span:uri.citation[https://www.maff.go.jp/j/nousin/bousai/bousai_saigai/b_tameike/pdf/tameike_manual_1rev.pdf]

* [[[real_estate_id_guidelines,1]]]
span:title[不動産 ID ルールガイドライン].
span:organization[国土交通省 不動産・建設経済局].
span:date[2022-03-31]
span:uri.citation[https://www.mlit.go.jp/tochi_fudousan_kensetsugyo/content/001594268.pdf]

// above references were used in doc2 but missing in doc2 bib

* [[[gsi_geospatial_dps_manual,1]]]
span:title[地理空間データ製品仕様書作成マニュアル JPGIS 2014版].
span:organization[国土交通省 国土地理院].
span:date[2020-11].
span:uri.citation[https://www.gsi.go.jp/common/000250810.pdf]
// https://psgsv2.gsi.go.jp/koukyou/public/seihinsiyou/seihinsiyou_index.html
// 令和2年11月

* [[[gsi_map_level_dps,1]]]
span:title[地図情報レベル2500数値地形図データ作成のための標準製品仕様書（案）].
span:organization[国土交通省 国土地理院].
span:edition[第1.1版].
span:date[2014-04].
span:uri.citation[https://www.gsi.go.jp/common/000259076.pdf]
// https://psgsv2.gsi.go.jp/koukyou/public/seihinsiyou/seihinsiyou_index.html

* [[[sig3d_model_1,1]]]
span:title[Modeling Guide for 3D Objects Part 1: Basics (Rules for Validating GML Geometrics in CityGML)].
span:organization[SIG3D].
span:date[2014-11].
span:uri.citation[https://www.sig3d.org/files/media/downloads/SIG3D/AG-Qualitaet/201311_SIG3D_Modeling_Guide_for_3D_Objects_Part_1.pdf]

* [[[sig3d_model_2,1]]]
span:title[Modeling Guide for 3D Objects Part 2: Modeling of Buildings (LoD1, LoD2 and LoD3)].
span:organization[SIG3D].
span:date[2014-11].
span:uri.citation[https://www.sig3d.org/files/media/downloads/SIG3D/AG-Qualitaet/201311_SIG3D_Modeling_Guide_for_3D_Objects_Part_2.pdf]

* [[[gsi_building_data_manual,1]]]
span:title[建物三次元データ作成マニュアル（案）].
span:organization[国土交通省 国土地理院].
span:date[2016-03].
span:uri.citation[https://www.gsi.go.jp/kankyochiri/Laser_gijutusiryo.html].
// 平成28年3月

* [[[plateau_000,PLATEAU Handbook #00]]],
span:title[3D都市モデルの導入ガイダンス].
span:organization[国土交通省 都市局].
span:docid.PLATEAU[PLATEAU Handbook #00].
span:edition[第4.0版].
span:date[2023-04-07].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/].

* [[[plateau_003,PLATEAU Handbook #03]]],
span:title[3D都市モデル整備のためのBIM活用マニュアル].
span:organization[国土交通省 都市局].
span:docid.PLATEAU[PLATEAU Handbook #03].
span:edition[第3.0版].
span:date[2023-03-27].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/].

* [[[plateau_tr_03,PLATEAU Technical Report #03]]]
span:title[3D都市モデルLOD3データ作成実証レポート].
span:organization[国土交通省 都市局].
span:docid.PLATEAU[PLATEAU Technical Report #03].
span:edition[第1.0版].
span:date[2022-03-29].
span:uri.citation[https://www.mlit.go.jp/plateau/file/libraries/doc/plateau_tech_doc_0003_ver01.pdf].

* [[[plateau_tr_56,PLATEAU Technical Report #56]]]
span:title[AI等を活用したLOD2自動生成ツールの開発及びOSS化 技術検証レポート].
span:organization[国土交通省 都市局].
span:docid.PLATEAU[PLATEAU Technical Report #56].
span:edition[第1.0版].
span:date[2023-04-04].
span:uri.citation[https://www.mlit.go.jp/plateau/file/libraries/doc/plateau_tech_doc_0056_ver01.pdf].

* [[[jis_e_1001,JIS E 1001:2001]]]

* [[[iconstruction,1]]],
span:title[i-Construction推進のための3次元数値地形図データ作成マニュアル].
span:organization[国土交通省 国土地理院].
span:uri.citation[https://www.gsi.go.jp/gijyutukanri/gijyutukanri41029.html]
// https://psgsv2.gsi.go.jp/koukyou/public/3dmapping/index.html

* [[[citygml_30_encoding,OGC 21-006r2]]]

* [[[ogc_19-081,OGC 19-081]]]

* [[[ifc_bridge_wp2,1]]]
span:title[IFC Bridge Fast Track Project -- Report WP2: Conceptual Model].
span:organization[buildingSMART International].
span:date[2018-10-02].
span:uri.citation[https://www.buildingsmart.org/standards/domains/infrastructure/ifc-bridge/]

* [[[tunnel_diagram_oonabe,1]]]
span:title[雄勝地区トンネル詳細設計業務　設計図　【大鍋トンネル】（国道13号）].
span:organization[中央復建コンサルタンツ株式会社].
span:date[2020-03].
span:uri.citation[https://www.thr.mlit.go.jp/road/kouji/kouji-tunnel/tunnel-index.html]
// https://www.thr.mlit.go.jp/road/kouji/kouji-tunnel/24_R13_oonabe/data_05_.pdf

* [[[tunnel_diagram_asakawa,1]]]
span:title[令和2年度　平石地区トンネル詳細設計業務　設計図　【本坑（上 線）】（国道13号）].
span:organization[東北地方整備局 福島河川国道事務所]、
span:organization[セントラルコンサルタント株式会社].
span:date[2023-03].
span:uri.citation[https://www.thr.mlit.go.jp/road/kouji/kouji-tunnel/tunnel-index.html]
// https://www.thr.mlit.go.jp/road/kouji/kouji-tunnel/29_R13_asakawa/data_05.pdf

* [[[jp_water_prevention_law,1]]]
span:title[水防法（昭和二十四年法律第百九十三号）].
span:organization[日本国政府].
span:date[1949-06-04].
span:uri.citation[https://elaws.e-gov.go.jp/document?lawid=324AC0000000193]

* [[[cbr_road_sample_data,1]]]
span:title[道路施設台帳サンプルデータ].
span:organization[国土交通省 中部地方整備局].
span:date[2017-03-14].
span:uri.citation[https://www.cbr.mlit.go.jp/architecture/kensetsugijutsu/download/index.htm]