[[toc9_02]]
=== 製品仕様のプロファイル

標準製品仕様を拡張（標準製品仕様に地物や地物属性・地物関連役割を追加）や制限（標準製品仕様を制限し、その一部を使用）することができる。

標準製品仕様の拡張又は制限においては、以下に示す規則に従う。

[[toc9_02_01]]
==== 拡張規則

標準製品仕様に定義されていない地物や地物属性・地物関連役割を用いたい場合は、以下に示す規則に従う。

規則1：標準製品仕様に定義されておらず、i-URに定義されている地物又は地物属性・地物関連を使用したい場合は、i-URから必要な要素を抽出し、i-URの定義と矛盾なく使用する。

規則2：標準製品仕様に定義されておらず、CityGMLに定義されている地物又は地物属性・地物関連を使用したい場合は、CityGMLから必要な要素を抽出し、CityGMLの定義と矛盾なく使用する。

規則3：標準製品仕様に定義されておらず、i-UR及びCityGMLのいずれにも定義されていない地物を使用したい場合には、CityGMLに定義されたgen:GenericCityObjectを使用して、地物を追加する。

NOTE: i-UR又はCityGMLに該当する地物が存在する場合には、gen:GenericCityObjectを使用してはならない。

規則4：標準製品仕様、i-UR、又はCityGMLのいずれにも定義されていない地物属性を使用したい場合には、CityGMLに定義されたgen:_genericAttributeの下位型を使用して、これを該当する地物に追加する。

NOTE: 標準製品仕様、i-UR又はCityGMLに該当する属性が存在する場合には、gen:_genericAttributeを使用してはならない。

NOTE: 「建築物」にコード型の地物属性を追加したい場合には、「建築物」に定義された「拡張属性」の仕組みを利用し、コード型の地物属性を追加する。

規則5：規則1、2又は規則4に従い、地物属性を追加する場合において、コード型の属性を定義する場合には、必ず、参照すべきコードリストを作成しなければならない。

NOTE: コードリストの形式は、GML3.1.1 simple dictionary profile(1.0.0)に従う。

規則6：規則1から規則5までに示す拡張規則に従い、標準製品仕様を拡張する場合には、拡張の内容を示す製品仕様を作成しなければならない。

NOTE: 製品仕様の作成においては、<<gsi_geospatial_dps_manual,地理空間データ製品仕様書作成マニュアル>>に従うこと。

[[toc9_02_02]]
==== 制限規則

規則1：標準製品仕様に定められた地物、属性又は関連を使用しない場合には、応用スキーマクラス図及び応用スキーマ文書修正は行わない。標準製品仕様書に使用する地物、属性及び関連の一覧を付し、制限の内容を示す製品仕様を作成しなければならない。
