[[toc9_03]]
=== データ更新

[[toc9_03_01]]
==== 適用範囲

データ更新とは、既に3D都市モデルが存在する都市において、以下を行うことを指す。

* 1．データセットの追加
* 2．地物型の追加
* 3．地物の追加
* 4．空間属性の追加
* 5．主題属性の追加

「1．データセットの追加」は、既存のデータセットを全く使用せず、新しいデータセットを作成すること（以下、「全体更新」と呼ぶ）である。また、「2．地物型の追加」から「5．主題属性の追加」は、既存のデータセットの一部又は全部を残して新しいデータを統合すること（以下、「一部更新」と呼ぶ）である。

[[toc9_03_02]]
==== データ製品の範囲

全体更新の場合は、作成された新しいデータセットがデータ製品となる。

一部更新の場合は、更新したデータと更新しなかったデータを統合したデータセットがデータ製品となる。

[[toc9_03_03]]
==== 全体更新が準拠すべき標準製品仕様書の版

全体更新は、本標準製品仕様書に準拠すること。

[[toc9_03_04]]
==== 一部更新が準拠すべき標準製品仕様書の版

一部更新は、本標準製品仕様書に準拠することを基本とする。
ただし、以下の条件を満たす場合は、地物型ごとに準拠する標準製品仕様書の版が異なることを可とする。

* 既存のデータ製品が、標準製品仕様書第4.1版以降に準拠していること

地物型ごとに準拠する標準製品仕様書の版が異なる場合、更新する地物型は本標準製品仕様書に準拠し、更新しない地物型は、標準製品仕様書第4.1版以降に準拠する。

なお、一つのデータ製品が準拠する標準製品仕様書の版の数は、地物型ごとに最大1とする。

[[toc9_03_05]]
==== 一部更新における拡張製品仕様書及びメタデータの取り扱い

一部更新において、データ製品に含む拡張製品仕様書及びメタデータは、本標準製品仕様書に準拠すること。また、地物型ごとに準拠する標準製品仕様書の版を明確にするため、以下に従うこと。

[[toc9_03_05_01]]
===== 拡張製品仕様書

各地物型ごとに、当該地物が準拠する標準製品仕様書の版を、「準拠する標準製品仕様書の版」欄に示すこと。

[[toc9_03_05_02]]
===== メタデータ（JMP 2.0）

一部更新により更新した地物型について、JMP2.0に基づくメタデータを作成する。 +
このとき、「4．空間属性の追加」及び「5．主題属性の追加」を行う場合は、メタデータファイル名のオプションとして 「V``[一部更新の回数]``」 を付与する。

[[toc9_03_05_03]]
===== README
各地物型が準拠する標準製品仕様書の版を、『準拠する標準製品仕様書の版』欄に示すこと。

