[[toc1_05]]
=== 用語と定義

標準製品仕様書で使用する用語を示す。以下に記載のない用語とその定義については、JPGIS 2014付属書5（規定）定義に従う。

3D都市モデル

都市空間の地物及び属性を都市スケールで3次元的に再現したCityGML形式のデータ。

BIM（Building Information Modeling）

コンピュータ上に作成した主に三次元の形状情報に加え、室等の名称・⾯積、材料・部材の仕様・性能、仕上げ等、建築物の属性情報を併せ持つ建築物情報モデルを構築するもの。

［出典　3D都市モデル整備のためのBIM活⽤マニュアル第3.0版］

BIM モデル

コンピュータ上に作成した三次元の形状情報に加え、室等の名称・⾯積、材料・部材の仕様・性能、仕上げ等の建築物の属性情報を併せ持つ建築物情報モデル。

［出典　3D都市モデル整備のためのBIM活⽤マニュアル第3.0版］

IFC（Industry Foundation Classes）

buildingSMART International (以降 bSI) が策定した三次元モデルデータ形式。2013年にはISO 16739:2013:Ver.4.0.0.0(IFC4)として、国際標準として承認されている。2018年に改訂され、ISO 16739-1:2018:Ver.4.0.2.1(IFC4 ADD2 TC1)が最新である。当初は、建築分野でのデータ交換を対象にしていたが、2013年には bSI内にInfrastructure Roomが設置され、⼟⽊分野を対象にした検討が進められている。

［出典　3D都市モデル整備のためのBIM活用マニュアル第3.0版］

Levels Of Detail (LOD)

詳細さの度合い（詳細度）であり、CityGMLにおいて定義されている一つのオブジェクトの幾何を、その利用や可視化の目的に応じて、複数の段階に抽象化することを可能とする、マルチスケールなモデリングの仕組みである。

［参考　OpenGIS® OGC CityGML Encoding Standard］

応用スキーマ

一つ又は複数の応用システムによって要求されるデータのための概念スキーマ。

［出典　JPGIS］

数値地形図

都市、河川、道路、ダム等の計画、管理及び土木工事のために使用できる位置精度を有した地理空間情報及び数値地形図。

［作業規程の準則　付録７公共測量標準図式］

地物

現実世界の現象の抽象概念。

地物は型又はインスタンスとして存在できる。地物型又は地物インスタンスはいずれか一方を意味する場合に用いるべきである。

［出典　JPGIS］

地物属性

地物の特性。

［出典　JPGIS］

地物関連

地物間の関係。

［出典　JPGIS］

関連役割

関連において相手の地物に対する自分の役割を指す。

［参考　地理情報標準プロファイル（JPGIS） Ver. 1.0　解説書］

プロファイル

1つ以上の基本規格のセット又は基本規格のサブセット及び該当する場合には特定の機能を達成するために必要なそれらの基本規格から選択された条項、クラス、オプション及びパラメータの識別。

［出典　ISO 19106:2004］

補足

標準製品仕様書は、i-UR及びCityGMLから3D都市モデルとして必要な地物型等をi-UR及びCityGMLと矛盾なく抽出した、i-UR及びCityGMLのプロファイルである。また、各都市で作成される拡張製品仕様書も、i-UR及びCityGMLのプロファイルでなくてはならない。

