[title="Normative references"]
=== 引用規格等

標準製品仕様書は、以下の規格、規程及び仕様書を引用する。

// .標準製品仕様書が引用する規格等

* [[[iurban_des,1]]],
span:title[Data Encoding Specification of i-Urban Revitalization -Urban Planning ADE- ver.3.0（内閣府地方創生推進事務局）].
span:uri.citation[https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur/index.html].


* [[[ogc_12-019,(1)OGC 12-019]]],
span:title[OpenGIS® OGC City Geography Markup Language (CityGML) Encoding Standard, Version 2.0, OGC document 12-019 （Open Geospatial Consortium）].
span:uri.citation[https://www.ogc.org/standards/citygml]

* [[[ogc_05-099r2,(1)OGC 05-099r2]]],
span:title[OpenGIS® GML 3.1.1 simple dictionary profile, Version 1.0.0, OGC document 05-099r2 （Open Geospatial Consortium）].
span:uri.citation[https://www.ogc.org/standards/gml]

* [[[iso_iec_19501,(1)ISO/IEC 19501:2005]]],
span:title[ISO/IEC 19501:2005, Information technology — Open Distributed Processing — Unified Modeling Language(UML) Version 1.4.2].
span:uri.citation[https://www.iso.org/standard/32620.html]

* [[[jpgis_2014,1]]],
span:title[地理情報標準プロファイル（JPGIS）2014　（国土交通省国土地理院）].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

// TODO: This entry did not exist but we need it as a term reference
* [[[jpgis_v1,1]]],
span:title[地理情報標準プロファイル（JPGIS） Ver. 1.0　解説書 （国土交通省国土地理院）].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-rh.html]

* [[[jmp20,1]]],
span:title[JMP2.0仕様書（国土交通省国土地理院）].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[jpgis_spec_reqs,1]]],
span:title[品質の要求，評価及び報告のための規則（国土交通省国土地理院）].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]


また、標準製品仕様書は、以下の仕様書を参照し、整合を図っている。

// .標準製品仕様書が参照する仕様書等


* [[[city_data_ps_sample,1]]],
span:title[都市計画データ標準製品仕様書].
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/toshi_tosiko_tk_000187.html]

* [[[road_foundation_ps,1]]],
span:title[道路基盤地図情報（整備促進版）製品仕様書（案）].
span:uri.citation[http://www.nilim.go.jp/lab/bcg/siryou/tnn/tnn0848pdf/ks084811.pdf]

* [[[mapping_ps,1]]],
span:title[地図情報レベル2500数値地形図データ作成のための標準製品仕様書（案）].
span:uri.citation[https://psgsv2.gsi.go.jp/koukyou/public/seihinsiyou/seihinsiyou_index.html]

* [[[iconstruction,1]]],
span:title[i-Construction推進のための3次元数値地形図データ作成マニュアル].
span:uri.citation[https://psgsv2.gsi.go.jp/koukyou/public/3dmapping/index.html]

* [[[plateau_bim_annex,1]]],
span:title[3D都市モデル整備のためのBIM活用マニュアル（第3.0版）（別冊）3D都市モデルとの連携のためのBIMモデルIDM・MVD（第2.0版）].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/]

* [[[ifc_2x3_cv,1]]],
span:title[IFC2x3 Coordination View 2.0 (IFC2x3 CV2.0)].
span:uri.citation[https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/]

* [[[gsi_dps,1]]],
span:title[3次元屋内地理空間情報データ仕様書（案）].
span:uri.citation[https://www.gsi.go.jp/common/000212582.pdf]

* [[[iso_19106_2004,hidden(ISO 19106:2004)]]]

引用規格等のうち、版の記載があるものは、その版を適用し、その後の改正版（追補を含む。）は適用しない。版の記載がないものは、その最新版（追補を含む。）を適用する

