
[.preface]
== はじめに

* 本書は、各地方公共団体等が3D都市モデルを整備する際に、その製品仕様を容易に作成でき、かつ、整備された3D都市モデルを国際標準に適合したものとすることを目的として提供する標準文書である。

* 「3D都市モデル」は、都市空間をデータによって再現したもの、すなわち、現実の都市空間から必要な情報を取捨選択し、データとして記述したものである。あらゆるデータがそうであるように、3D都市モデルも何らかのソリューション（ユースケース）を創出するために整備されるものであるから、そのデータ内容や範囲等はユースケースに依存する。しかし、ユースケースごとに異なる仕様の3D都市モデルを整備することはデータ作成の観点から非効率であり、多用途への展開を考慮する場合は流通性や再利用性を阻害する懸念がある。

* 3D都市モデルの流通性・再利用性を高め、様々な分野・用途での利用に資するデータとするためには、「標準」に適合することが重要である。本書は、地理空間データに関する標準化団体であるOpen Geospatial Consortium（OGC）が策定した3D 都市モデルのためのオープンデータモデル及びデータ形式の国際標準である「CityGML」と、このCityGMLの拡張規則であるApplication Domain Extension（ADE）に基づき内閣府地方創生推進事務局が都市再生に必要なデータを拡張した「i-都市再生技術仕様（案）」（i-UR）を我が国における3D都市モデルの標準仕様として採用し、「標準製品仕様」として示すものである。

* 標準製品仕様は、CityGML及びi-URに準拠して作成され、Project PLATEAUの2020年度、2021年度及び2022年度の成果を踏まえ、様々な地物やその属性の定義、また、品質要求及び評価手順を示している。さらに、必要な地物等に過不足があった場合に、国際標準に準拠しつつ3D都市モデルをカスタマイズするための規則を示している。そのため、3D都市モデルを整備する場合には、本書を参照することで、国際標準に準拠した3D都市モデルの製品仕様（以下、「拡張製品仕様」と呼ぶ）を作成できる。

* 今後、3D都市モデルの整備主体が、本書を参照し、ユースケースに応じた拡張製品仕様を作成することで、国際標準に適合した3D都市モデルが整備され、様々な分野での利用が促進されることを期待する。

[.preface]
== 改定の概要

2021/3/26発行　3D都市モデル標準製品仕様書　第1.0版

* 2020年度に発行した標準製品仕様は、以下に示す三つのユースケースに3D都市モデルが使用されることを想定し、その製品仕様を定めている。
+
--
. 都市に関わる様々な地理空間データを格納する基盤（オープンデータ化を含む）
. 3次元空間における都市計画決定情報の可視化
. 災害リスク情報の3次元可視化
--

2022/3/29発行　3D都市モデル標準製品仕様書　第2.0版

* 2021年度は、以下の観点により2020年度の製品仕様を拡張し、標準製品仕様を改定した。
+
--
. 地物の拡充
** 道路空間を構成する「都市設備」、「植生」、「都市計画決定情報」を追加した。

. LOD（Level Of Detail：詳細度）の拡大及び精緻化
** 「建築物」及び「道路」について、 標準製品仕様が対象とするLODの段階を拡大した。
** データ品質の均一化を図る観点からLODの定義を精緻化した。

. 引用する仕様（i-UR）の更新
** 2020年度の標準製品仕様は、i-UR第1.4版をデータモデル及び符号化仕様として採用した。2021年度の標準製品仕様は、i-UR第2.0版（i-UR3.0）を採用する。なお、i-UR3.0は、i-UR1.4に2020年度及び2021年度のProject PLATEAUの検討成果が反映され、改定されたものである。
--

2023/4/7発行　3D都市モデル標準製品仕様書　第3.0版

* 2022年度は、以下の観点により2021年度の製品仕様を拡張し、標準製品仕様を改定した。
+
--
. 地物の拡充
** 都市空間の地物の網羅性を高めるため、「鉄道」、「徒歩道」、「広場」、「航路」、「橋梁」、「トンネル」、「その他の構造物」、「地下埋設物」、「地下街」、「水部」及び「区域」を追加した。

. LOD（Level Of Detail：詳細度）の拡大及び精緻化
** 「建築物」のLOD4を追加した。なお、LOD4の定義はBIMモデルの国際標準であるIFCとの整合させた。
** 各地物のLODの定義の記述方法を統一し、その内容を精緻化した（定義自体に変更はない）。

. 引用する仕様（i-UR）の更新
** 2022年度の標準製品仕様は、i-UR第3.0版（i-UR3.0）を採用する。i-UR3.0は、2022年度のProject PLATEAUの検討成果が反映され、改定されたものである。
--
