[[tocB_02]]
=== 空間参照系

空間参照系は、実世界における位置を識別するための体系であり、位置を座標により記述する場合には、原点や軸の方向、座標の単位等の取り決めが含まれる。座標が地球上のどこであるかを示すには、空間参照系を指定しなければならない。


[requirement]
.日本測地系2011に基づく3次元座標の空間参照系
====
[%metadata]
identifier:: /req/gm/1
subject:: 妥当な幾何オブジェクトの要件
description:: データ製品に含まれる幾何オブジェクトの3次元座標の空間参照系は、「日本測地系2011における経緯度座標系と東京湾平均海面を基準とする標高の複合座標参照系」とする。
====

3D都市モデルは日本全国を対象とすることから、日本全国を適用範囲とする空間参照系を適用する。水平方向は、「日本測地系2011における経緯度座標系」を採用する。また、高さ方向は、「東京湾平均海面を基準とする標高」を採用する。 +
2次元座標の取り扱いについては、<<tocB_04>>を参照すること。


[requirement]
.データ集合の範囲を示す空間参照系
====
[%metadata]
identifier:: /req/gm/2
subject:: 妥当な幾何オブジェクトの要件
description:: データ製品に適用する空間参照系は、データ集合（core:CityModel）の範囲（gml:boundedBy）を示すgml:EnvelopeのsrsName属性に記述する。
====

空間参照系の指定は、座標ごとに指定する、あるいは、これを含む幾何オブジェクトごとに指定するというように、いくつかの方法がある。3D都市モデルにおいては、空間参照系が一律に指定されることから、これらを包含するデータ集合であるcore:CityModelに対して空間参照系を指定する。 +
データ集合に記述する空間参照系は、これの定義を取得可能なURIにより指定する。

[example]
====
URIの例：http://www.opengis.net/def/crs/EPSG/0/6697
====

[example]
====
[source,xml]
----
<gml:boundedBy>
  <gml:Envelope srsName="http://www.opengis.net/def/crs/EPSG/0/6697" srsDimension="3">
    <gml:lowerCorner> 33.80 130.54 0.0 </gml:lowerCorner>
    <gml:upperCorner> 33.81 130.55 20.0 </gml:upperCorner>
  </gml:Envelope>
</gml:boundedBy>
----
====

gml:Envelopeの属性srsNameに空間参照系のURIを記述する。属性srsDimensionには次元数を入れる。gml:lowerCornerには、緯度、経度及び標高の最小値を記載し、gml:upperCornerには最大値を記載する。
