[[tocB_04]]
=== CityGMLにおける2次元の空間参照系の取り扱い

標準製品仕様書では、幾何オブジェクトの座標値に適用する空間参照系として、3次元の空間参照系である「日本測地系2011における経緯度座標系と東京湾平均海面を基準とする標高の複合座標参照系」を採用している。これは、標準製品仕様書が準拠する国際標準であるCityGMLが、3次元の都市空間を記述することを目的として設計されているためである。しかしながら、ユースケースによっては高さを必要とせず、幾何オブジェクトの座標値は2次元でよい場合も想定される。（例：3次元の地形データにドレープして使用するため、高さが不要）

CityGMLでは、採用すべき空間参照系は規定されていない。一方で、前述したようにCityGMLが3次元の都市空間を対象としていることから、CityGML対応ツールには3次元の座標値の読み込みにしか対応しておらず、2次元座標を正しく読み込めない場合がある。これを踏まえ、既存のCityGML対応ツールでの読み込みを可能とするための暫定的な処置となるが、2次元座標により記述された幾何オブジェクトを3D都市モデルに記述する方策を示す。以下で示す以外の事項については、前項までに示した要件に従うこと。

[[tocB_04_1]]
==== 空間参照系

3D都市モデルは日本全国を対象とすることから、日本全国を適用範囲とする空間参照系として、2次元の空間参照系においても、水平方向は「日本測地系2011における経緯度座標系」を採用する。

[recommendation]
.幾何オブジェクトの空間参照系条件
====
[%metadata]
identifier:: /rec/gm/1
subject:: 妥当な幾何オブジェクトの要件
description:: データ製品に含まれる幾何オブジェクトの2次元座標の空間参照系は、「日本測地系2011における経緯度座標系」とする。
====

ただし、前述のとおり、2次元の空間参照系に対応しないツールが多いことから、3D都市モデルでは以下のように空間参照系を指定する。


[recommendation]
.3D都市モデルの座標参照系条件
====
[%metadata]
identifier:: /rec/gm/2
subject:: 妥当な幾何オブジェクトの要件
description::
「日本測地系2011における経緯度座標系」により記述された2次元座標をもつ幾何オブジェクトを3D都市モデルに含めたい場合には、空間参照系として「日本測地系2011における経緯度座標系と東京湾平均海面を基準とする標高の複合座標参照系」を指定する。
+
ただし、2次元の座標値は標高に該当する値を持たないため、高さ方向の座標値として仮想的な高さ（0.0）を入れる。
====


[example]
====
[source,xml]
----
<gml:boundedBy>
	<gml:Envelope srsName="http://www.opengis.net/def/crs/EPSG/0/6697">
		<gml:lowerCorner srsDimension="3">33.80 130.54 0.0</gml:lowerCorner>
		<gml:upperCorner srsDimension="3">33.81 130.55 0.0</gml:upperCorner>
	</gml:Envelope>
</gml:boundedBy>
----
====

本来、「日本測地系2011における経緯度座標系」が適用された場合srsName属性で指定する空間参照系のURIは、「日本測地系2011における経緯度座標系」の定義を取得可能なURI +
（例：http://www.opengis.net/def/crs/EPSG/0/6668 ）であり、次元数を示すsrsDimension属性の値は2である。 +
しかしながら、CityGMLは3次元座標の地理空間データの記述を対象としていることからCityGML対応のソフトウェアの中には、2次元座標の地理空間データを読み込めないものもある。そのため、暫定的な対応として高さの最小範囲・最大範囲に0.0を入れ、次元数に3を記述する。

[[tocB_04_2]]
==== 座標値の記述

gml:pos又はgml:posListを用いて座標値を記述する場合、2次元座標により記述された幾何オブジェクトには仮想的な高さとして0.0を与える。


[recommendation]
.2次元幾何の高さ設定条件
====
[%metadata]
identifier:: /rec/gm/3
subject:: 妥当な幾何オブジェクトの要件
description:: 2次元座標の幾何オブジェクトを記述する場合には、架空の高さ方向の座標値として0.0を入れる。
====

[[tocB_04_3]]
==== 留意事項

本項で示す2次元座標により記述された幾何オブジェクトを3D都市モデルに記述する場合の推奨規則は、暫定的な対応である。そのため、これが適用されていることを3D都市モデルの利用者に明示する必要がある。


[recommendation]
.3Dモデルメタデータの仮想高さ明記条件
====
[%metadata]
identifier:: /rec/gm/4
subject:: 妥当な幾何オブジェクトの要件
description::
3D都市モデルのメタデータには、2次元座標により記述された幾何オブジェクトを3D都市モデルに含めるため、仮想的な高さを示す座標値として0.0が記述されていることを明記する。
+
また、その対象となる地物型を明記する。
====

具体的には、3D都市モデルの説明情報となるメタデータの要約（識別情報の要約）に以下の文言を記載する。 +
「3D都市モデルに含まれるすべての座標は、緯度・経度・標高の3つの座標値の組から構成されています。そのため、2次元の空間参照系が適用されている●●（対象となる地物型を列挙）の座標には、標高に0.0が記述されています。この場合の0.0が実際の標高ではないことに注意してください。」

