[[toc8_05]]
=== 原典資料リストの仕様

JMP2.0では、データ製品を作成する際に使用した原典資料の諸元を詳細に記述できないことから、標準製品仕様書では、原典資料リストのための仕様を定める。3D都市モデルを作成する際には、必ずこの原典資料リストを作成しなければならない。

[[toc8_05_01]]
==== 原典資料リストの記載項目

[cols="1a,3a,1a"]
.原典資料リストの記載項目
|===
| 原典資料リスト項目 | 記述する内容 | 記述例

| meshcode
| 標準地域メッシュのコードを記述する。

コードは、地物のファイル単位として指定されている3次メッシュ又は2次メッシュのメッシュコードとする。地下埋設物モデルの場合は、国土基本図の図郭コード（図郭の区画名）とする。

メッシュ毎又は図郭ごとに記述することを基本とする。

同一の地物・属性について、都市域全体で同一の原典資料が使用されている場合、メッシュコード又は図郭コードを省略する。

例えば、一つの洪水浸水想定区域図を都市域全体で使用している場合は、メッシュコードを省略する。

一方、LOD0の建築物の外形について、都市計画基本図を使用して作成しつつ、一部のメッシュは航空写真から図化した場合は、同一地物・属性について複数の原典資料が使用されているため、メッシュ毎に記述する。

また、都市計画基礎調査を複数年に分けて実施しており、場所によって作成時点の異なる都市計画基礎調査の成果が使用されている場合には、同一地物・属性について複数の原典資料が使用されているため、メッシュ毎に記述する。
| 50305455

| feature
| 地物名を記述する。 +
各モジュールに複数の地物が定義されている場合は、集成する地物（例：Building）を記述することを基本とする。集成する地物に束ねられ、部品として使われる地物（例：WallSurface, Door）は記述しなくてもよいが、特に明記したい場合は、記述してもよい。

なお、Appearance（地物に貼るテクスチャ）は、貼り付ける対象となる地物（例：Building）のプロパティとして本リストでは記述する。

地物名には接頭辞（例：Buildingの場合は、bldg）を付す。
| bldg:Building

| featureName
| "feature"で、"GenericCityObject"を記述した場合は、どのGenericCityObjectを使用したかを識別するため、name属性の値を記述する。GenericCityObject以外をfeatureに記述した場合は、空とする。
| 20

| property
| 地物の主題属性（データ型を含む）及び空間属性（幾何オブジェクトへの参照）を記述する。空間属性はLOD別とする。

地物の主題属性がデータ型として定義されている場合は、関連役割名とする。ただし、データ型に定義された各属性に異なる原典資料が使用されている場合は、"関連役割名.主題属性名"とする。

地物のテクスチャは、"property"を"app:appearance"とする。

属性名には、接頭辞を付す。

接頭辞は、応用スキーマ文書に示す地物の主題属性又は空間属性に付す接頭辞に一致させる。

例：bldg:function, bldg:lod1Solid, bldg:lod2Solid, bldg:buildingDetailAttribute, uro:buildingDetailAttribute.uro:vacancy, app:appearance
| bldg:lod0RoofEdge

| propertyName
| "property"で、"gen:stringAttribute"などの任意に追加した属性を記述した場合は、属性を識別するため、name属性（又はkey属性）の値を記述する。任意に追加した属性以外をpropertyに記述した場合は、空とする。
| 名称

| sourceName
| 原典として使用した資料の名称を記述する。
| 航空写真

| authority
| 原典資料の作成機関の名称を記述する。
| ●●県〇〇市

| date
| 原典資料が作成、公表又は改訂された日付を記述する。
| 2021-01-01

| dateType
| "date"で記述した日付の意味を記述する。作成日の場合は001、公表日の場合は002、改訂日の場合は003、不明な場合は004とする。
| 001

| srs
| 原典資料がGISデータ又は図面の場合に、適用されている座標参照系の識別子を、JIS X7115メタデータ附属書2に従い記述する。GISデータではない場合は空とする。
| JGD2011 / 2(X, Y)

| mapLevel
| 原典資料がGISデータの場合又は図面の場合に、地図情報レベルを記述する。数値のみの記載とする。例：地図情報レベル2500の場合は”2500”とする。
| 2500

| URL
| 原典資料又はその詳細な情報が入手可能なウェブサイトがある場合にはURLを記述する。
| https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A27-v3_0.html

|===

[[toc8_05_02]]
==== 原典資料リストの作成単位

データ製品に含まれる各都市に対して一つの原典資料リストを作成する。

[[toc8_05_03]]
==== 原典資料リストのファイル仕様

出力データ構造には、CSVを使用する。拡張子は、「.csv」とする。

(1)に示す記載項目の組を1レコードとし、以下に示す規則に従い出力する。

[cols="3a,2a"]
.原典資料リストのファイル仕様
|===
h| 文字コード | UTF-8 （BOM付）
h| 改行コード | CRLF
h| 区切り文字 | カンマ（,）
h| ヘッダ行の有無 | あり
h| ヘッダ行の行数 | 1
h| ヘッダ行の内容 | 原典資料リスト項目を使用する。
h| 文字列でのダブルクォートの有無 | あり
h| null値の指定方法 | ,, （区切り文字の連続）
h| 1項目内で、複数の値を列挙する場合に使用する区切り文字 | ;（セミコロン）
h| 禁則文字 | 指定しない

|===

[[toc8_05_04]]
==== 原典資料リストのファイル名称

`udx_[都市コード]_[整備年度]_resource`

``[都市コード]``及び``[整備年度]``は、成果品のルートフォルダ名に一致する。

[[toc8_06]]
==== READMEの仕様

データ製品の概要書として、READMEを作成する。READMEの仕様を以下に示す。

[[toc8_06_01]]
==== 形式

md（マークダウン）形式とする。ファイル拡張子は、.mdとする。

[[toc8_06_02]]
==== ファイル名

READMEとする。（拡張子を含めると、``README.md``）

[[toc8_06_03]]
==== 記載項目

READMEに含むべき項目は下表のとおりとする。

[cols="1a,3a"]
.READMEに含める項目
|===
| 記載項目 | 記述する内容

| 成果品名称
| 3D都市モデルの名称。以下のとおりとする。

`3D都市モデル（Project PLATEAU）[都市名]（[整備年度]）`

``[都市名]`` 整備対象都市の名称を入れる。市区町村の場合は、市区町村名、都道府県の場合は都道府県名とする。 ``[整備年度]`` 作成又は更新した年度（例：2022年度）を入れる。成果品のフォルダ名称に含める``[整備年度]``と一致させる。

| 都市名 | 都道府県及び市区町村の名称。
| 作成（更新）年月日 | データ製品の作成（又は更新）年月日。YYYY-MM-DDにより記述する。
| 3D都市モデルの概要
| 概要として、以下の文章を記述する。

「3D都市モデルとは、都市空間に存在する建物や街路といったオブジェクトに名称や用途、建設年といった都市活動情報を付与することで、都市空間そのものを再現する3D都市空間情報プラットフォームです。

様々な都市活動データが3D都市モデルに統合され、フィジカル空間とサイバー空間の高度な融合が実現します。これにより、都市計画立案の高度化や、都市活動のシミュレーション、分析等を行うことが可能となります。」

| 都市の面積 | データ製品の対象となる市区町村の面積。単位はkm2とする。
| 3D都市モデルの整備内容
| データ製品に含まれる地物を応用スキーマごとに示す。

また、以下に示す地物は、LOD別の整備範囲及び整備規模（面積、箇所数等）を記載する。

* 建築物モデル：LOD別の棟数、整備範囲及び整備面積。
* 交通（道路）モデル：LOD別の整備範囲及び整備面積。
* 交通（徒歩道）モデル：LOD別の整備範囲及び整備面積。
* 交通（広場）モデル：LOD別の整備範囲及び整備箇所数。
+
整備箇所数は、整備した広場の数とする。
* 交通（航路）モデル：LOD別の航路数。
+
航路数は、整備した航路の数とする。
* 土地利用モデル：整備範囲及び整備面積。
* 都市設備モデル：LOD別の整備範囲及び整備面積。
* 植生モデル：LOD別の整備範囲及び整備面積。
* 災害リスク（浸水）モデル：洪水浸水想定区域、高潮浸水想定区域、津波浸水想定ごとの区域図の名称。
* 災害リスク（土砂災害）モデル：区域種類及び区域数。
* 都市計画決定情報：整備対象とした都市計画の種類。
* 橋梁モデル：LOD別の箇所数。
* トンネルモデル：LOD別の箇所数。
* その他の構造物：LOD別の箇所数。
* 地下街モデル：LOD別の整備範囲及び箇所数。
* 水部モデル：LOD別の整備面積。
* 地形モデル：LOD別の整備面積。
* 区域モデル：LOD別の整備面積及び区域数。
+
LODは、「LOD2.0」「LOD3.0」「LOD3.1」のように、最小の区分を示す。 +
整備範囲は、「市街化区域」「用途地域」「○○駅周辺エリア」のように、整備範囲が分かる名称とする。 +
整備面積は、整備範囲の面積とする。単位は、km2を基本とするが、整備範囲が小さい場合はhaを使用してもよい。 +
例えば、整備範囲が都市計画区域の場合、整備面積は都市計画区域の面積とする。 +
+
なお、整備の対象とする地物や整備エリアを限定している場合に、その整備規模として施設数、整備面積、又は整備延長を記載する。

| 準拠する標準製品仕様書の版
| 拡張製品仕様書が準拠する標準製品仕様書の版を記述する。

「3D都市モデル標準製品仕様書　第4.0版」

| 地図情報レベル
| データ製品に含まれる地物の地図情報レベル。

「地図情報レベル2500」が基本となるが、地図情報レベル500や地図情報レベル1000の地物が含まれている場合には、対象とする地物やエリアを記述する。

| 索引図へのリンク | 成果品フォルダに含まれる索引図（PDFファイル）への相対パス。
| 製品仕様書へのリンク | 成果品フォルダに含まれる製品仕様書（PDFファイル及びExcelファイル）への相対パス。
| メタデータへのリンク | 成果品フォルダに含まれるメタデータ（XMLファイル）への相対パス。
| 原典資料リストへのリンク | 成果品フォルダに含まれる原典資料リスト（CSVファイル）への相対パス。
| 利用に関する留意事項
| オープンデータの場合は、以下を記入する。

「本データセットは[PLATEAU Site Policy 「３．著作権について」](https://www.mlit.go.jp/plateau/site-policy/)で定められた以下のライセンスを採用します。 +
+ 政府標準利用規約（第2.0版） +
+ [クリエイティブ・コモンズ・ライセンスの表示4.0国際](https://creativecommons.org/licenses/by/4.0/legalcode.ja) +
+ ODC BY（ https://opendatacommons.org/licenses/by/1-0/ ） +
+ ODbL（ https://opendatacommons.org/licenses/odbl/ ）

利用者は、いずれかのライセンスを選択し、商用利用も含め、無償で自由にご利用いただけます。 +
原典資料の位置の正しさの違いや、作成された時期の違いにより、現状を正確に反映していない場合があることにご注意ください。」

|===

[[toc8_06_04]]
==== 作成単位

データ製品に対して1つのファイルを作成する。

[[toc8_06_05]]
==== テンプレート

README.mdのテンプレートは、製品仕様書作成テンプレートセットに含めている。 +
製品仕様書作成テンプレートセットは、 https://www.mlit.go.jp/plateaudocument/より入手できる。

[[toc8_07]]
==== 索引図の仕様

索引図の仕様を下表に示す。

[cols="1a,3a"]
.索引図の仕様
|===
| 項目 | 仕様

| タイトル | 「〇〇　3D都市モデル整備範囲図」 〇〇の部分は整備範囲となる市区町村名又は都道府県名を記載する。
| 背景地図 | 国土地理院の地理院地図（地理院タイル）を標準とする。
| 縮尺 | 任意とする。（指定のサイズ・レイアウトに収める。）
| サイズ・レイアウト | 用紙サイズA4を基本とする。レイアウトは対象範囲の形状を考慮し縦又は横いずれも可とする。
| 記載項目
|
* ３D都市モデルの詳細度（LOD1～LOD4）ごとに色を分けて表示する。
** LOD3及びLOD4の整備範囲は、整備範囲の広さに応じて詳細図を表示する。

* 対象範囲の標準地域メッシュ（２次メッシュ、３次メッシュ）のメッシュとメッシュ番号を表示する。

* 凡例を表示する。主な記載項目は以下とする。
** 2次メッシュ及びそのメッシュ数：記号は水色（R:5,G:110,B:255）の太線の四角を標準とする。
** 3次メッシュ及びそのメッシュ数：記号は黒色（R:0,G: 0,B:0）の中太線の四角を標準とする。
** LOD1整備範囲（範囲の通称）及び面積km2：記号は黒色（R:0,G: 0,B:0）の太線の四角を標準とする。
** LOD2整備範囲（範囲の通称）及び面積km2：記号は赤色（R:240,G: 5,B:0）の太線の四角を標準とする。
** LOD3整備範囲（範囲の通称）及び数量（km2又はkm等）：記号は緑色（R:90,G:255,B:0）の太線の四角又は線を標準とする。
** LOD4整備範囲（範囲の通称）及び数量（km2又はkm等）：記号は青色（R:0,G:0,B:255）の太線の四角又は線を標準とする。
| 形式 | PDF

|===

