[[toc8_05]]
=== 原典資料リストの仕様

JMP2.0では、データ製品を作成する際に使用した原典資料の諸元を詳細に記述できないことから、標準製品仕様書では、原典資料リストのための仕様を定める。3D都市モデルを作成する際には、必ずこの原典資料リストを作成しなければならない。

[[toc8_05_01]]
==== 原典資料リストの記載項目

// this table is_common to both doc01 and doc02 slide16

.原典資料リストの記載項目
include::../../../common/sections/com_8_05_5_03_001.adoc[]

////
[cols="1a,3a,1a"]
|===
| 原典資料リスト項目 | 記述する内容 | 記述例

| meshcode
| 標準地域メッシュのコードを記述する。 +
コードは、地物のファイル単位として指定されている3次メッシュ又は2次メッシュのメッシュコードとする。地下埋設物モデルの場合は、国土基本図の図郭コード（図郭の区画名）とする。 +
メッシュ毎又は図郭ごとに記述することを基本とする。 +
同一の地物・属性について、都市域全体で同一の原典資料が使用されている場合、メッシュコード又は図郭コードを省略する。 +
例えば、一つの洪水浸水想定区域図を都市域全体で使用している場合は、メッシュコードを省略する。 +
一方、LOD0の建築物の外形について、都市計画基本図を使用して作成しつつ、一部のメッシュは航空写真から図化した場合は、同一地物・属性について複数の原典資料が使用されているため、メッシュ毎に記述する。 +
また、都市計画基礎調査を複数年に分けて実施しており、場所によって作成時点の異なる都市計画基礎調査の成果が使用されている場合には、同一地物・属性について複数の原典資料が使用されているため、メッシュ毎に記述する。
| 50305455

| feature
| 地物名を記述する。 +
各モジュールに複数の地物が定義されている場合は、集成する地物（例：Building）を記述することを基本とする。集成する地物に束ねられ、部品として使われる地物（例：WallSurface,Door）は記述しなくてもよいが、特に明記したい場合は、記述してもよい。 +
なお、Appearance（地物に貼るテクスチャ）は、貼り付ける対象となる地物（例：Building）のプロパティとして本リストでは記述する。 +
地物名には接頭辞を付する。

[example]
====
Buildingの場合は、bldg
====

| bldg:Building

| featureName
| "feature"で、"GenericCityObject"を記述した場合は、どのGenericCityObjectを使用したかを識別するため、name属性の値を記述する。GenericCityObject以外をfeatureに記述した場合は、空とする。
| 20

| property
| 地物の主題属性（データ型を含む）及び空間属性（幾何オブジェクトへの参照）を記述する。空間属性はLOD別とする。 +
地物の主題属性がデータ型として定義されている場合は、関連役割名とする。ただし、データ型に定義された各属性に異なる原典資料が使用されている場合は、"関連役割名.主題属性名"とする。 +
地物のテクスチャは、"property"を"app:appearance"とする。 +
属性名には、接頭辞を付す。 +
接頭辞は、応用スキーマ文書に示す地物の主題属性又は空間属性に付す接頭辞に一致させる。

[example]
====
bldg:function,bldg:lod1Solid,bldg:lod2Solid,uro:buildingDetailAttribute,uro:buildingDetailAttribute.uro:vacancy,app:appearance
====

| bldg:lod0RoofEdge

| propertyName
| "property"で、"gen:stringAttribute"などの任意に追加した属性を記述した場合は、属性を識別するため、name属性（又はkey属性）の値を記述する。任意に追加した属性以外をpropertyに記述した場合は、空とする。
| 名称

| sourceName
| 原典として使用した資料の名称を記述する。
| 航空写真

| authority
| 原典資料の作成機関の名称を記述する。
| ●●県〇〇市

| date
| 原典資料が作成、公表又は改訂された日付を記述する。
| 2021-01-01

| dateType
| "date"で記述した日付の意味を記述する。作成日の場合は001、公表日の場合は002、改訂日の場合は003、不明な場合は004とする。 +
作成日は原典資料の納品日とする。 +
公表日は原典資料がオープンデータとして公開された日とする。 +
改訂日は作成又は公開された原典資料が修正され、納品又は公開された日とする。
| 001

| srs
| 原典資料がGISデータ又は図面の場合に、適用されている座標参照系の識別子を、JIS X7115メタデータ附属書2に従い記述する。GISデータではない場合は空とする。
| JGD2011/2（X,Y）

| mapLevel
| 原典資料がGISデータの場合又は図面の場合に、地図情報レベルを記述する。数値のみの記載とする。例：地図情報レベル2500の場合は”2500”とする。 +
一つの原典資料に複数の地図情報レベルが混在している場合は、列挙してよい。ただし、その他の項目の内容が同一である場合に限る（その他の項目の内容は異なる場合は行を分ける）。
| 2500

列挙する場合 +
2500;1000

| URL
| 原典資料又はその詳細な情報が入手可能なウェブサイトがある場合にはURLを記述する。
| https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A27-v3_0.html

|===
////

[[toc8_05_02]]
==== 原典資料リストの作成単位

データ製品に含まれる各都市に対して一つの原典資料リストを作成する。

[[toc8_05_03]]
==== 原典資料リストのファイル仕様

出力データ構造には、CSVを使用する。拡張子は、「.csv」とする。 +
<<toc8_05_01>>に示す記載項目の組を1レコードとし、以下に示す規則に従い出力する。

.原典資料リストのファイル仕様
include::../../../common/sections/com_8_05_5_03_002.adoc[]

////
[cols="3a,2a"]
|===
h| 文字コード | UTF-8 （BOM付）
h| 改行コード | CRLF
h| 区切り文字 | カンマ（,）
h| ヘッダ行の有無 | あり
h| ヘッダ行の行数 | 1
h| ヘッダ行の内容 | 原典資料リスト項目を使用する。
h| 文字列でのダブルクォートの有無 | あり
h| null値の指定方法 | ,, （区切り文字の連続）
h| 1項目内で、複数の値を列挙する場合に使用する区切り文字 | ;（セミコロン）
h| 禁則文字 | 指定しない

|===
////

[[toc8_05_04]]
==== 原典資料リストのファイル名称

`udx_[都市コード]_[整備年度]_resource`

``[都市コード]``及び``[整備年度]``は、成果品のルートフォルダ名に一致する。

