[[toc8_02]]
=== メタデータの記載項目

メタデータの記載項目を<<tab-8-1>>に示す。

// this table is_common to both doc01 and doc02 slide08, slide09,
// slide10, slide11, slide12, slide13

[[tab-8-1]]
[cols="1a,3a,1a",options="header"]
.メタデータに含めるべき項目
|===
| メタデータ項目 | 記述する内容 | 記述例

| メタデータ>ファイル識別子 
| ``udx\_[都市コード]_[提供者区分]\_[整備年度]_[地物型]_[オプション]``とする。

``[都市コード]``、``[提供者区分]``及び``[整備年度]``は成果品のルートフォルダ名称と一致させる。 +
``[地物型]``は、地物型又はモジュールを示す接頭辞（3文字又は4文字のアルファベット）とする。 +
なお、``_[地物型]``は、メタデータを地物型又はモジュールごとに作成せず、まとめて作成した場合は省略する。 +
``[オプション]``は、成果品が複数種類作成される場合に、これらを識別するために使用する任意の文字列とする。半角英数字のみを使用可とする。成果品を格納するルートフォルダに使用する``[オプション]``の文字列に一致させること。成果品が1種類の場合は省略する。
| udx_27100_city_2020_fld

| メタデータ>言語 | メタデータの記述に使用する言語。日本語とする。
|
jpn（固定値）
| メタデータ>文字集合 | メタデータに使用する文字コード。UTF-8とする。
|
004（固定値）
| メタデータ>階層レベル | メタデータの作成対象。データ集合とする。
| 005　（固定値）
| メタデータ>問い合わせ先
| 発注者の問合せ先を記述する。役割、組織名、電話番号、 +
オンライン情報源（Project PLATEAUのURL等）を記述する。 +
役割は「010（刊行者）」とする。
| 010（固定値） +
国土交通省都市局 +
03-5253-8397 +
www.mlit.go.jp/plateau/

| メタデータ>日付 | メタデータの作成日付をYYYY-MM-DDにより記述する。
|
2021-02-25
| メタデータ>規格の名称 | メタデータの仕様。
|
JMP（固定値）
| メタデータ>規格の版 | メタデータの版。
|
2.0（固定値）
| 参照系情報 | データ集合に適用される空間参照系の識別子。製品仕様書で指定された空間参照系の識別子を記述する。識別子は、JMP2.0を参照する。

「日本測地系2011 における経緯度座標系と東京湾平均海面を基準とする標高の複合座標参照系」の場合は、JGD2011,TP/（B,L）,Hとなる。 +
「日本測地系2011 における平面直角座標系と東京湾平均海面を基準とする標高の複合座標参照系」の場合は、JGD2011,TP/n（X,Y）,Hとなる。 +
ここでは、平面直角座標系の系番号であり、拡張製品仕様書に使用する系番号を明記する。
|
JGD2011,TP/（B,L）,H
| 識別情報>題名 | ``3D都市モデル\_[都市コード]_[提供者区分]\_[整備年度]_[オプション]``

``[都市コード]``、``[提供者区分]``、``[整備年度]``及び``[オプション]``は、成果品フォルダの名称に一致する。
|
3D都市モデル_27100_city_2020
| 識別情報>日付及び日付型 | データの作成日付及び日付型を記述する。

作成日付はYYYY-MM-DDにより記述する。 +
日付型は以下より選択する。 +
001：作成日、002：刊行日、003：改訂日 | 2021-02-25, 003
| 識別情報 > 要約
| 3D都市モデルの概要を記載する。 +
以下の文章を入れる。 +
「3D都市モデルとは、都市空間に存在する建物や街路といったオブジェクトに名称や用途、建設年といった都市活動情報を付与することで、都市空間そのものを再現する3D都市空間情報プラットフォームです。

様々な都市活動データが3D都市モデルに統合され、フィジカル空間とサイバー空間の高度な融合が実現します。これにより、都市計画立案の高度化や、都市活動のシミュレーション、分析等を行うことが可能となります。」

また、データ集合に含まれる地物やそのLOD、作成に使用した原典資料、作成方法を示す。また、以下に示すデータの利用上の注意事項を入れること。

「ただし、原典資料の位置の正しさの違いや、作成された時期の違いにより、現状を正確に反映していない場合があることにご注意ください。」

また、同一の地物型について、複数のモデル整備事業者がモデルを作成した場合は、ファイル名のオプションに使用する文字列の説明を記載すること。
| 複数のモデル整備事業者がモデルを作成した場合の記載例：

本データに含まれる建築物モデルのうち、オプション値にpscとあるものは令和5年度に株式会社パスコが、aacとあるものは令和5年度に朝日航洋株式会社が作成したデータを意味します。
| 識別情報>目的 | 各都市において想定される3D都市モデルのユースケースを記述する。
|
災害リスクの三次元可視化
| 識別情報>状態 | 「完成」を示す固定値とする。
|
001（固定値）
.2+| 識別情報>問い合わせ先 | 発注者の問合せ先を記述する。役割、組織名、電話番号、オンライン情報源（ProjectPLATEAUのURL）等を記述する。 +
役割は「010（刊行者）」とする。
|
010（固定値） +
国土交通省都市局 +
03-5253-8397 +
www.mlit.go.jp/plateau/
| 作成者の問合せ情報を記述する。 +
役割名は「060（創作者）」とする。
|
060 +
○○株式会社 +
www.sample.co.jp
| 識別情報>記述的キーワード
|
キーワードを、複数グループ化して記述する。

* 「type=002」として、データ製品に含まれる都市の名称を入れる。
* 「type=005」として、データ製品に含まれる地物型の名称を入れる。
* 「type=005」として、データ製品に含まれるLODのレベルを入れる。
* 「type=005」として、データ製品に想定されるユースケースを入れる。
* 「type=005」として、データ製品の作成に使用した原典資料の名称を入れる。
* 「type=005」として、データ製品に含まれる都市の名称を入れる。
|
東京23区,002 +
建築物,005 +
LOD1,005 +
景観シミュレーション,005 +
都市計画基本図,005
| 識別情報>利用制限 | 固定値とし、「Licensed under CC BY 4.0」を記述する。
|
Licensed under CC BY 4.0（固定値）
| 識別情報>空間表現型 | ベクトルを意味する「001」を入力する。
|
001（固定値）
| 識別情報>空間解像度 | 等価縮尺の分母にデータ集合に適用する地図情報レベルを入力する。

複数のレベルが混在する場合は、それぞれ記述する。
|
2500
| 識別情報>言語 | メタデータの記述に使用する言語。日本語とする。
|
jpn（固定値）
| 識別情報>文字集合 | メタデータに使用する文字コード。UTF-8とする。
|
004（固定値）
| 識別情報>主題分類 | 構造物を意味する「017」を入力する。
|
017（固定値）
| 識別情報>範囲
|

* 作成範囲を包含する最小の矩形を、東西の経度、南北の緯度により記述する。
* 地物やLODにより整備範囲が異なる場合は、作成範囲の違いを自由記述により明記する。
* 地理記述には、都道府県及び市区町村名を記述する。

| LOD1の作成範囲は●●市全域、LOD2の作成範囲は、△△駅を中心とする半径約300m内。

| 配布情報>配布書式 | 固定値「CityGML 2.0」及び「i-UR 3.1」 +
をそれぞれ書式情報として入れる。
| CityGML 2.0 +
i-UR 3.1

| 配布情報>オンライン | G空間情報センターのURLを記述する。
|
https://front.geospatial.jp/ （固定値）
| データ品質情報>データ品質 
| 製品仕様書に示す品質要求の各項目について品質評価結果を記述する。 +
系譜（データが作成されるまでの過去の記録や履歴、原典資料の概要）には、主題属性の作成方法や図形と属性のアンマッチへの対処方法等、データ品質に記載できないが、データ製品の利用にあたり注意が必要となるデータの品質に係る事項を記述する。 +
また、公共測量成果の対象となる建築物モデル、交通モデル、橋梁モデル、トンネルモデル、その他の構造物モデル、植生モデル、地形モデル及び水部モデルについて、公共測量成果ではない都市オブジェクトが含まれている場合は、該当しない理由を記載する。
| （系譜の例）

一部の橋梁モデルは、厚みを推定で作成しているため、公共測量成果ではありません。

|===

