[[toc2_04]]
=== 作成計画の立案

前項で決定した地物型ごとの作成方法に基づき、作成計画を立案する。このとき、使用する資料間の不整合が生じた場合への対処方法を検討・決定すること。また、一部の地物型等を新規に取得する必要が生じた場合に、他の地物型等も同時に新規取得とするほうが効率的と判断できる場合には、作成方法の見直しを行うこと。 

なお、基盤地図情報や空中写真等の測量成果を使用する場合には、測量成果の複製・使用承認の申請が必要となる。また、国や地方公共団体等が整備主体となり、((3D都市モデル))を整備する場合において、航空写真測量等の測量により、((建築物))の外形線や高さの取得を行う場合は、公共測量の手続きが必要となる。これらの手続きについても計画に含めること。

(((LOD1)))(((LOD2)))(((3D都市モデル)))(((建築物)))(((作成制限施設)))

* 【手順】
* 手順1．作成計画を立案する。
** 作成計画は、対象となる地域、原典資料の収集内容、対象とする地物型とその空間属性を踏まえた作業量、完成時期を考慮して立案する。
** また、LOD1やLOD2のように、各LODで3D都市モデルを整備する範囲・対象が異なる場合には、それぞれについて、範囲・対象を決定する。
*** 例えば、建築物のうち、ランドマークのみをLOD2で整備する場合には、ランドマークとして扱うべき建築物を特定する。
** 作成制限施設についても<<toc1_05_03>>に示す規則に従い、特定する。
* 手順2．使用する資料間の不整合への対処方法を決定する。
** 複数の資料を組み合わせて使用する場合、資料が作成された時点や取得基準の違いにより、データの対応付けができない場合（<<fig-2-1>>）がある。このような不整合に備え、あらかじめその対処方法を決定する。
** なお、不整合への対処方法は、作成した3D都市モデルのメタデータ（データ品質情報>データ品質）に記載すること（<<toc5_03_02>>参照）。

[cols="1a,4a"]
.資料間の不整合の例
|===
^h| 不整合の内容 ^h| 例
.4+| 対応付ける対象がない +
（1：0）
| 基盤地図情報に建物外周線はあるが、この建物に対応する都市計画基礎調査のデータがない。

| 基盤地図情報に建物外周線はあるが、航空レーザ測量等により得られた点群データに、この建物の高さを示す点群が存在しない。
| 都市計画基礎調査のデータがあるが、該当する場所に基盤地図情報の建物外周線がない。
| 航空レーザ測量等により得られた点群データに建物の高さを示す点群が存在するが、該当する場所に基盤地図情報の建物外周線がない。
.2+| 対応付ける対象が複数ある +
（1：N）
| 基盤地図情報には一つの建物外周線はあるが、この建物に対応する都市計画基礎調査のデータが二つある。

| 都市計画基礎調査のデータは一つしかないが、該当する場所に基盤地図情報の建物外周線が複数ある。

|===

　

[NOTE,type=commentary]
--
資料間の不整合への対処方法として、資料の優先順位を決定し、必要な情報が不足する場合にこれを補完する方法（他の既存資料の収集、新規データの取得又は便宜的な対応※）を決定する。ただし、3D都市モデルの整備主体において不足する情報を補完する作業が不要と判断した場合には、この限りではない。

資料の優先順位付けとしては、「いつ時点の地物が資料に反映されているか」（データの取得時点や調査時点）がその判断基準となりうるが、各資料の取得基準の違いにより、必ずしも最新の資料が正しいとは限らない。建築物は都市計画基礎調査を優先する、というように地物型等により優先すべき資料を決定してもよい。

※便宜的な対応とは、Web配信地図等を参考に建築物の形状（外形線、高さ）を取得する、又は属性を未入力とする方法である。他の既存資料の収集、新規データの取得ができない場合の対応となる。ただし品質要求を満たすデータにならないことに注意する必要がある。
--
