[.preface,type=publication-history]
== 改定の概要

2021/3/26 発行 3D都市モデル標準作業手順書 第1.0版

* 2020年度に発行した標準作業手順書は、同年度に発行した標準製品仕様書第1.0版に準拠した拡張製品仕様書を作成する手順や、これに適合する3D都市モデルを整備する標準的な手順を示した。

2022/3/29 発行 3D都市モデル標準作業手順書 第2.0版

* 2021年度は、標準製品仕様書の改定により、3D都市モデルが対象とする地物やそのLOD及び属性が拡張されたため、作業手順書についてもこの改定を反映した。さらに、2020年度の成果を踏まえ、より活用性の高い3D都市モデルとするために内容の見直しを図っている。

* 主な改定の内容は、以下の通りである。

.. 追加した地物についての解説の追加

*** 標準製品仕様書に追加した「都市設備」、「植生」、「都市計画決定情報」及び「テクスチャ」について、国際標準に適合した3D都市モデルとするため、作業時に遵守すべき事項、注意すべき事項を整理した。

.. LODを拡大した地物についての解説の追加

*** 標準製品仕様書に追加した「建築物LOD3」及び「道路のLOD2及びLOD3」について、国際標準に適合した3D都市モデルとするため、作業時に遵守すべき事項、注意すべき事項を整理した。

.. 成果品のファイル命名規則及びフォルダ構成の厳密化

*** 各都市で作成された3D都市モデルの統一性を高めるため、成果品に適用すべきファイル命名規則及びフォルダ構成についての規則を追加した。

.. 作成制限施設の追加

*** 国の安全保障又は警備上の理由から作成を制限すべき3D都市モデルの地物とその対応を規則として追加した。


2023/4/7 発行 3D都市モデル標準作業手順書 第3.0版

* 2022年度は、標準製品仕様書の改定により、3D都市モデルが対象とする地物やそのLOD及び属性が拡張されたため、作業手順書についてもこの改定を反映した。

* 主な改定内容は、以下のとおりである。

.. 追加した地物についての解説の追加

*** 標準製品仕様書に追加した「鉄道」、「徒歩道」、「広場」、「航路」、「橋梁」、「トンネル」、「その他の構造物」、「地下埋設物」、「地下街」、「水部」及び「区域」について、国際標準に適合した3D都市モデルとするため、作業時に遵守すべき事項、注意すべき事項及び標準的な作業手順を整理した。

2024/03/22 発行 3D都市モデル標準作業手順書 第4.0版

* 2023年度は、標準製品仕様書の改定により、LOD定義の見直しや成果品の見直しがあったため、作業手順書についてもこの改定を反映した。

* 主な改定内容は、以下のとおりである。

.. LOD定義の見直しに伴う作業手順の修正

*** 地下埋設物モデルのLOD定義の見直しに伴い、作業手順や原典資料を修正した。

.. 成果品の見直し

*** 整備年度の考え方や、拡張した地物のファイル命名規則及びフォルダ構成についての規則を追加した。

.. 解説・事例の拡充

*** データ整備やユースケース実証の結果を踏まえ、複雑な地物の形状の取得方法や属性の付与方法に関する解説・事例を追加した。
