[[toc0_03]]
[bibliography]
== 参考文献

* [[[plateau_002,PLATEAU Handbook #02]]],
span:organization[国土交通省 都市局].
span:title[3D都市モデル標準作業手順書].
span:docid.PLATEAU[PLATEAU Handbook #02].
span:date[2024-09-30].
span:edition[第5.0版].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/].

* [[[plateau_010,PLATEAU Handbook #10]]],
span:organization[国土交通省 都市局].
span:title[3D都市モデル整備のための測量マニュアル].
span:docid.PLATEAU[PLATEAU Handbook #10].
span:date[2024-04-02].
span:edition[第3.0版].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/handbooks/].

* [[[gsi_geospatial_dps_manual,1]]]
span:title[地理空間データ製品仕様書作成マニュアル JPGIS 2014版].
span:organization[国土交通省 国土地理院].
span:date[2020-11].
span:uri.citation[https://www.gsi.go.jp/common/000250810.pdf]
// https://psgsv2.gsi.go.jp/koukyou/public/seihinsiyou/seihinsiyou_index.html

* [[[rfc_4122,IETF RFC 4122]]]

* [[[gml_311,OGC 07-036]]]

* [[[citygml_20,OGC 12-019]]]

* [[[citygml_30,OGC 20-010]]]

* [[[citygml_30_encoding,OGC 21-006r2]]]

* [[[iso_6707-1,ISO 6707-1]]]

* [[[jis_e_1001,JIS E 1001:2001]]]

* [[[mlit_green_roads,4]]]
span:organization[国土交通省 道路局].
span:title[道路緑化技術基準].
span:uri.citation[https://www.mlit.go.jp/road/sisaku/ryokuka/index.html]

* [[[mlit_greenery_std,5]]]
span:organization[国土交通省 都市局].
span:title[公共用緑化樹木等品質寸法規格基準（案）].
span:date[2010-02].
span:uri.citation[https://www.mlit.go.jp/notice/noticedata/sgml/035/76000224/76000224.html]

* [[[nilim_street_trees,6]]]
span:title[わが国の街路樹Ⅷ],
span:organization[国土交通省 国土技術政策総合研究所].
span:date[2018-01]
span:uri.citation[http://www.nilim.go.jp/lab/bcg/siryou/tnn/tnn1050.htm]

* [[[mlit_ks_ps_a31,7]]]
span:organization[国土交通省 国土政策局].
span:title[国土数値情報（洪水浸水想定区域）製品仕様書].
span:version[第2.1版]
span:date[2020-03].
span:uri.citation[https://nlftp.mlit.go.jp/ksj/gml/product_spec/KS-PS-A31-v2_1.pdf]

* [[[mlit_ks_ps_a33,8]]]
span:organization[国土交通省 不動産・建設経済局].
span:title[国土数値情報（土砂災害警戒区域）製品仕様書]
span:version[第 2.0 版].
span:date[2021-03].
span:uri.citation[https://nlftp.mlit.go.jp/ksj/gml/product_spec/KS-PS-A33-v2_0.pdf]

* [[[mlit_flooding_guidelines,9]]]
span:organization[国土交通省 水管理・国土保全局 河川環境課 水防企画室 下水道部 海岸室].
span:title[浸水想定区域図データ電子化ガイドライン（第4版）].
span:edition[4].
span:date[2023-02].
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/index.html]

* [[[mlit_deluge_guidelines,10]]]
span:organization[国土交通省 水管理・国土保全局 河川環境課 水防企画室],
span:organization[国土技術政策総合研究所 河川研究部 水害研究室].
span:title[洪水浸水想定区域図作成マニュアル（第4版）].
span:edition[4].
span:date[2017-01].
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/index.html]

* [[[mlit_tsunami_guidelines,11]]]
span:organization[国土交通省 水管理・国土保全局 海岸室],
span:organization[国土技術政策総合研究所 河川研究部 海岸研究室].
span:title[津波浸水想定の設定の手引き].
span:version[ver 2.11].
span:date[2023-04].
span:uri.citation[https://www.mlit.go.jp/sogoseisaku/point/content/001621078.pdf]

* [[[mlit_tide_guidelines,12]]]
span:organization[農林水産省 農村振興局 整備部 防災課],
span:organization[農林水産省 水産庁 漁港漁場整備部 防災漁村課],
span:organization[国土交通省 水管理・国土保全局 河川環境課],
span:organization[国土交通省 水管理・国土保全局 海岸室],
span:organization[国土交通省 港湾局 海岸・防災課].
span:title[高潮浸水想定区域図作成の手引き].
span:version[Ver 2.11].
span:date[2023-04].
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/kaigan/takashioshinsui_manual.pdf]

* [[[mlit_int_flood_guidelines,13]]]
span:organization[国土交通省 水管理・国土保全局 下水道部].
span:title[内水浸水想定区域図作成マニュアル（案）].
span:date[2021-07].
span:uri.citation[https://www.mlit.go.jp/river/shishin_guideline/pdf/naisui_manual.pdf]

* [[[inspire_data_spec,14]]]
span:organization[European Commission Joint Research Centre].
span:title[D2.8.III.6 INSPIRE Data Specification on Utility and Government Services -- Technical Guidelines].
span:date[2013-01-10].
span:uri.citation[https://inspire.ec.europa.eu/Themes/136/2892]

* [[[ogc_23-024,OGC 23-024]]],
span:organization[Open Geospatial Consortium].
span:title[OGC Model for Underground Data Definition and Integration (MUDDI) Part 1: Conceptual Model].
span:docid.OGC[OGC 23-024].
span:date[2024-01-31].
span:uri.citation[https://portal.ogc.org/files/106383]

* [[[ifc_bridge_wp2,16]]]
span:title[IFC Bridge Fast Track Project -- Report WP2: Conceptual Model].
span:organization[buildingSMART International].
span:date[2018-10-02].
span:uri.citation[https://www.buildingsmart.org/standards/domains/infrastructure/ifc-bridge/]

* [[[iana_media_types,IANA media-types]]]

* [[[maff_reservoir_hazard_maps,18]]]
span:title[ため池ハザードマップ作成の手引き].
span:organization[農林水産省 農村振興局 防災課].
span:date[2013-05].
span:uri.citation[https://www.maff.go.jp/j/nousin/bousai/bousai_saigai/b_tameike/pdf/tameike_manual_1rev.pdf]

* [[[mlit_emergency_roads,1]]]
span:title[緊急輸送道路].
span:organization[国土交通省].
span:uri.citation[https://www.mlit.go.jp/road/bosai/measures/index3.html]

* [[[mlit_local_disaster,1]]]
span:title[地域防災計画の作成の基準].
span:organization[国土交通省　水管理・国土保全局　防災課].
span:uri.citation[https://www.mlit.go.jp/common/001618459.pdf]

* [[[mlit_road_upkeep,1]]]
span:title[道路保守・管理].
span:organization[国土交通省　道路局].
span:uri.citation[https://www.mlit.go.jp/road/soudan/soudan_08b_01.html]

* [[[mlit_foundation_reqs,1]]],
span:title[都市計画基礎調査実施要領].
span:organization[国土交通省 都市局].
span:edition[第4版].
span:date[2021-05].
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/kisotyousa001.html]

* [[[gsi_building_data_manual,1]]]
span:title[建物三次元データ作成マニュアル（案）].
span:organization[国土交通省 国土地理院].
span:date[2016-03].
span:uri.citation[https://www.gsi.go.jp/kankyochiri/Laser_gijutusiryo.html].

* [[[nlftp,1]]]
span:title[国土数値情報].
span:organization[国土交通省 政策統括官付 地理空間情報課].
span:date[2024].
span:uri.citation[https://nlftp.mlit.go.jp].

* [[[mlit_cyberport,1]]]
span:title[Cyber Port サイバーポート].
span:organization[国土交通省].
span:date[2024].
span:uri.citation[https://www.cyber-port.mlit.go.jp].

* [[[mlit_road_damage_map,1]]]
span:title[全国道路施設点検データベース 損傷マップ].
span:organization[国土交通省].
span:date[2024].
span:uri.citation[https://road-structures-map.mlit.go.jp].

* [[[mlit_city_plan_investigation,1]]]
span:title[都市計画現況調査].
span:organization[国土交通省 都市局 都市計画課 都市計画調査室].
span:date[2023].
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/genkyou.html]

* [[[inspire_registry,1]]]
span:title[INSPIRE registry].
span:organization[European Commission, Joint Research Centre].
span:date[2024].
span:uri.citation[https://inspire.ec.europa.eu/registry]

* [[[jp_road_law,1]]]
span:title[道路法（昭和二十七年法律第百八十号）].
span:organization[日本国政府].
span:date[1952-06-10].
span:uri.citation[https://elaws.e-gov.go.jp/document?lawid=327AC1000000180]

* [[[jp_building_law,1]]]
span:title[建築基準法（昭和二十五年法律第二百一号）].
span:organization[日本国政府].
span:date[1950-05-24].
span:uri.citation[https://elaws.e-gov.go.jp/document?lawid=325AC0000000201]
// https://elaws.e-gov.go.jp/document?lawid=327AC1000000180

* [[[jp_water_prevention_law,1]]]
span:title[水防法（昭和二十四年法律第百九十三号）].
span:organization[日本国政府].
span:date[1949-06-04].
span:uri.citation[https://elaws.e-gov.go.jp/document?lawid=324AC0000000193]

* [[[uniclass,1]]]
span:title[Uniclass]
span:organization[NBS Enterprises Ltd].
span:date[2024].
span:uri.citation[https://uniclass.thenbs.com]

* [[[jis_x_7107,JIS X 7107]]]

* [[[mlit_urban_digitization,1]]]
span:title[都市計画情報のデジタル化・オープン化ガイダンス].
span:organization[国土交通省 都市局].
span:edition[第1.0版].
span:date[2024-06].
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/genkyou.html]

* [[[jswa_sewage_system,1]]]
span:title[下水道台帳管理システム標準仕様（案）・導入の手引き]
span:organization[日本下水道協会].
span:edition[Ver.5].
span:date[2021-09].
span:uri.citation[https://www.jswa.jp/publication/list/]

* [[[stat_regional_mesh,1]]]
span:title[地域メッシュ統計について].
span:organization[総務省　統計局].
span:date[2024-03-14].
span:uri.citation[https://www.stat.go.jp/data/mesh/m_tuite.html]

* [[[cbr_road_build_manual,1]]]
span:title[道路施設台帳作成マニュアル].
span:organization[国土交通省 中部地方整備局].
span:date[2009-03].
span:edition[第1.3版].
span:uri.citation[https://www.cbr.mlit.go.jp/architecture/kensetsugijutsu/download/index.htm]

* [[[real_estate_id_guidelines,1]]]
span:title[不動産 ID ルールガイドライン].
span:organization[国土交通省 不動産・建設経済局].
span:date[2022-03-31]
span:uri.citation[https://www.mlit.go.jp/tochi_fudousan_kensetsugyo/content/001594268.pdf]
