[[toc3_02]]
=== 既存資料の収集

<<toc2_04>>作成計画の立案の結果に基づき、原典資料とする既存資料を収集する。

(((3D都市モデル)))(((オープンデータ)))

* 【手順】
* 手順1．既存資料を入手する。必要に応じて使用申請等の手続きをとること。また、各既存資料について、測量成果の種類、内容、構造、品質等を示す製品仕様書や品質を確認できるメタデータも併せて入手すること。
+
特に、民間企業が販売するアーカイブデータを原典資料とする場合には、二次利用（データの加工編集）の可否、また、これに基づき作成した3D都市モデルのオープンデータ化の可否を確認すること。なお、オープンデータを原典資料とする場合についても、利用規約を確認し、3D都市モデルの作成及びこのオープンデータ化に支障がないことを利用規約により確認すること。

* 手順2．入手した資料の内容を確認し、3D都市モデルの製品仕様を満たす原典資料となるか否かを判定する。原典資料として使用不可との判定をした場合には、以下のいずれかの対応をとる。

. 「<<toc2_04>>作成計画の立案」に戻り、作成方法を再検討する
. 品質要求を満たさないデータ製品を許容する
. <<toc1_05_01>>に戻り、品質要求を下げる

なお、b又はcの対応は、データ製品の品質を下げることになるため、ユースケースの要件をデータ製品が満たさない恐れがある。そのため、原則としてaの対応をとる。しかしながら、費用や工期等の制約によりb又はcの対応しかとることができない場合には、((3D都市モデル))の整備主体はユースケースへの影響の程度を考慮し、b又はcいずれの対応をとるかを決定しなければならない。入手資料の確認における留意事項を以下に示す。

[requirement]
.仕様確認とデータ整合性確認
====
[%metadata]
identifier:: /att/collection/1
subject:: 標準作業手順
class:: 留意事項
[statement]
--
製品仕様書やメタデータ等、その仕様や品質を確認できる内容であることを確認する。

* 航空写真やレーザ点群データの場合は、想定されている地図情報レベルや撮影諸元（地上画素寸法、オーバーラップ率、サイドラップ率）が妥当であることを確認すること。
** 各LODの作成に必要な航空写真やレーザ点群データの撮影諸元は、「<<plateau_010,3D都市モデル整備のための測量マニュアル>>」を参考にできる。
* 図形を含む原典資料の場合には、適用されている空間参照系や地図情報レベル、図形データの取得基準等を確認すること。
* 属性を含む原典資料の場合には、値の単位やコードの内容等の記載された定義文書の有無を確認すること。
* 原典資料に不整合（例：定義域に含まれない値の存在）がある場合にはその対応を確認すること。

--
====

// (((3D都市モデル)))

[requirement]
.対象範囲の網羅性確認
====
[%metadata]
identifier:: /att/collection/2
subject:: 標準作業手順
class:: 留意事項
[statement]
--
対象範囲が網羅されたデータであることを確認する。

* 3D都市モデルの整備の対象範囲の一部が原典資料のデータ取得範囲から漏れている、あるいは、データ取得範囲には含まれているが、取得条件等によりデータが欠落している場合があるため、原典資料に含まれる範囲を確認すること。

--
====

[requirement]
.原典資料間の不整合確認
====
[%metadata]
identifier:: /att/collection/3
subject:: 標準作業手順
class:: 留意事項
[statement]
--
原典資料間の位置のずれ、時点の差異、取得基準の差異は、許容できる範囲におさまっていることを確認する。

* 既存資料間の不整合に対する対処方法として「<<toc2_04>>作成計画の立案」において決定した以外の不整合が確認された場合には、その不整合への対処方法を決定すること。

--
====

[requirement]
.データ構造の適用可否確認
====
[%metadata]
identifier:: /att/collection/4
subject:: 標準作業手順
class:: 留意事項
[statement]
--
想定していた作成手順を適用できるデータ構造となっていることを確認する。

* 数値地形図データを原典資料として使う場合、データの構造化（例：分断された図形の結合、外形線の閉合による面の作成）が必要な場合がある。構造化の要否、また、構造化にどの程度の作業が必要となるかを確認すること。

--
====
