[[tocC_07]]
=== bldg:Room

bldg:Roomは、部屋を記述するために使用する地物型である。bldg:Roomは、建築物の内部空間の表現に使用し、LOD4のみに出現する。建築物モデル（LOD4）において、bldg:Roomは、bldg:Buildingに含まれる地物として記述する。このとき、bldg:Roomは、複数の地物の集まりとして表現する。bldg:Roomに含まれる地物とは、以下である。

* 部屋を区切る境界面（bldg:_BoundarySurfaceの下位型）
* 部屋に付属する固定的な設備（bldg:InteriorBuildingInstallation）
* 部屋の中に設置された移動可能な家具（bldg:BuildingFurniture）

[[tocC_07_01]]
==== 部屋の空間属性

bldg:Roomは立体（bldg:lod4Solid）として表現する。このとき、立体の境界となる面は、天井面（bldg:CeilingSurface）、床面（bldg:FloorSurface）、内壁面（bldg:InteriorWallSurface）又は閉鎖面（bldg:ClosureSurface）のいずれかとなる。

[[tocC_07_02]]
==== 部屋の主題属性

bldg:Roomは、建築物の内部の部屋の総称となる。そのため、部屋の機能や用途は、主題属性bldg:class及びbldg:functionにより区分する。


[requirement]
.bldg:Roomの機能区分方法
====
[%metadata]
identifier:: /req/bldg/24
subject:: 妥当な建築物データセットの要件
description:: bldg:Roomは、bldg:class及びbldg:functionによりその機能や用途を区分する。
====

bldg:class及びbldg:functionが取りうる値は、コードリストにより定義されている。標準製品仕様書では、bldg:class及びbldg:functionの定義域として建築生産で必要とする建築部位、工法及び設備などの名称を体系的に整理したUniclass2015のうち、Space/Locationのカテゴリを採用している。これは、建築物モデル（LOD4）は、BIMモデルからの変換によるデータ作成が進むと想定され、bldg:Roomに対応するIFCのクラスとして、IfcSpaceが存在するからである。

