[[tocC_01]]
=== 概要

本付属書では、「3D都市モデル標準製品仕様書」（以下、「標準製品仕様書」という）に適合したデータ製品について、「建築物モデル」に従って作成されるべき都市オブジェクト（以下、「建築物オブジェクト」という）が満たすべき要件と、妥当な建築物オブジェクトを作成するための標準的な作業手順を示す。


[requirements_class]
.妥当な建築物オブジェクト作成
====
[%metadata]
identifier:: /req/bldg
subject:: 妥当な建築物オブジェクトの要件
description:: 建物の説明とLODの要件
requirement:: /req/bldg/1
requirement:: /req/bldg/2
requirement:: /req/bldg/3
requirement:: /req/bldg/4
requirement:: /req/bldg/5
requirement:: /req/bldg/6
requirement:: /req/bldg/7
requirement:: /req/bldg/8
requirement:: /req/bldg/9
requirement:: /req/bldg/10
requirement:: /req/bldg/11
requirement:: /req/bldg/12
requirement:: /req/bldg/13
requirement:: /req/bldg/14
requirement:: /req/bldg/15
requirement:: /req/bldg/16
requirement:: /req/bldg/17
requirement:: /req/bldg/18
requirement:: /req/bldg/19
requirement:: /req/bldg/20
requirement:: /req/bldg/21
requirement:: /req/bldg/22
requirement:: /req/bldg/23
requirement:: /req/bldg/24
requirement:: /req/bldg/25
requirement:: /req/bldg/26
requirement:: /req/bldg/27
requirement:: /req/bldg/28
requirement:: /req/bldg/29
requirement:: /req/bldg/30
requirement:: /req/bldg/31
requirement:: /req/bldg/32
requirement:: /att/bldg/1
requirement:: /att/bldg/2
requirement:: /att/bldg/3
requirement:: /att/bldg/4
requirement:: /att/bldg/5
requirement:: /att/bldg/6
requirement:: /att/bldg/7
====

