[[tocD_04]]
=== tran:TrafficArea

tran:TrafficAreaは、車道や歩道のように通行可能な領域（交通領域）を示す。CityGMLでは、地物型として車道や歩道は用意されておらず、tran:TrafficAreaの属性tran:functionを用いて区分する。3D都市モデルでは、LODに応じて交通領域を区分するために、LODごとに属性tran:functionの定義域を定めている。この定義域は、<<nilim_kiban_dps,道路基盤地図情報（整備促進版）製品仕様書（案）>>において道路面を構成する地物の区分との整合を考慮している。


[requirement]
.交通領域の区分方法
====
[%metadata]
identifier:: /req/tran/8
subject:: 妥当な交通（道路）データセットの要件
description:: LODに応じた交通領域の区分には、属性tran:functionを用いる。
====

LOD2及びLOD3.0では、交通領域は、車道部、車道交差部及び歩道部に区分する（<<tab-D-7>>）。

// this table is_common to both doc01 and doc02 slide27

[[tab-D-7]]
.LOD2及びLOD3.0での交通領域の区分

[cols="3a,3a,3a,3a,13a"]
|===
| ファイル名 4+| TrafficArea_function.xml

h| ファイルURL 4+| https://www.geospatial.jp/iur/codelists/3.2/TrafficArea_function.xml
2+^h| 大分類 2+^h| 小分類 .2+^h| 定義
^h| コード ^h| 説明 ^h| コード ^h| 説明
.2+| 1000 .2+| 車道部 2+| | 主として自動車が利用する道路の部分。
| 1020 | 車道交差部 | 十字路、丁字路、その他二つ以上の車道が交わる部分。
| 2000 | 歩道部 2+| | 自転車や歩行者のために供される道路の部分。歩道上の植栽を含む。

|===

[.source]
<<nilim_kiban_dps>>

// RWP commented out table below 20240917

////

[[tab-D-7]]
[cols="2a,2a,2a,3a,11a",options="noheader"]
.LOD2及びLOD3.0での交通領域の区分
|===
2+^h| 大分類 2+|  小分類 .2+|  定義
^h| コード |  説明 |  コード |  説明
.2+| 1000 .2+| 車道部 2+| | 主として自動車が利用する道路の部分。
| 1020 | 車道交差部 | 十字路、丁字路、その他二つ以上の車道が交わる部分。
| 2000 3+| 歩道部 | 自転車や歩行者のために供される道路の部分。歩道上の植栽を含む。

|===

////

車道部（コード1000）は、車道内の車道交差部（コード1020）以外の全ての部分となる。LOD2及びLOD3.0では、車道部には、車線だけではなく車線と一体的に舗装されている路肩や非常駐車帯のように、本来は車両の通行の用に供されない場所が含まれる。また、歩道部（コード2000）には、歩道上に設けられた植栽が含まれる。 +
LOD3.1では、LOD3.0の区分に加え、車道内の車線を区分する（<<tab-D-8>>）。車線を区分することで、車両が通行可能な範囲が明らかとなる。

// this table is_common to both doc01 and doc02 slide28

[[tab-D-8]]
.LOD3.1での交通領域の区分
[cols="3a,3a,3a,3a,13a"]
|===
| ファイル名 4+| TrafficArea_function.xml

h| ファイルURL 4+| https://www.geospatial.jp/iur/codelists/3.2/TrafficArea_function.xml
2+^h| 大分類 2+^h| 小分類 .2+^h| 定義
^h| コード ^h| 説明 ^h| コード ^h| 説明
.3+| 1000 .3+| 車道部 2+| | 主として自動車が利用する道路の部分のうち、自動車の通行の用に供される部分。
| 1010 | 車線 | 一縦列の自動車を安全かつ円滑に通行させるために設けられる帯状の車道の部分。
| 1020 | 車道交差部 | 十字路、丁字路、その他二つ以上の車道が交わる部分。
| 2000 | 歩道部 2+| | 自転車や歩行者のために供される道路の部分。歩道上の植栽を含む。

|===

// RWP commented out table below 20240917

////

[[tab-D-8]]
[cols="2a,2a,2a,3a,11a",options="noheader"]
.LOD3.1での交通領域の区分
|===
2+^h| 大分類 2+|  小分類 .2+|  定義
^h| コード |  説明 |  コード |  説明
.3+| 1000 .3+| 車道部 2+| | 主として自動車が利用する道路の部分のうち、自動車の通行の用に供される部分。
| 1010 | 車線 | 一縦列の自動車を安全かつ円滑に通行させるために設けられる帯状の車道の部分。
| 1020 | 車道交差部 | 十字路、丁字路、その他二つ以上の車道が交わる部分。
| 2000 3+| 歩道部 | 自転車や歩行者のために供される道路の部分。植栽を含む。

|===

////

なお、車道部（コード1000）は、車道内の車線（コード1010）、車道交差部（コード1020）以外の全ての部分となる。つまり、LOD3.0と同様に、車線と一体的に舗装されている路肩や非常駐車帯のような、本来は車両の通行の用に供されない場所が含まれる。また、歩道部には歩道上の植栽が含まれる。 +
LOD3.2及びLOD3.3では、LOD3.1の区分に加え、歩道上の植栽を区分する（<<tab-D-9>>）。歩道部から植栽の範囲が除かれることで、歩道上の通行可能な領域が明らかとなる。

// this table is_common to both doc01 and doc02 slide29

[[tab-D-9]]
.LOD3.2及びLOD3.3での交通領域の区分
[cols="3a,3a,3a,3a,13a"]
|===
| ファイル名 4+| TrafficArea_function.xml

h| ファイルURL 4+| https://www.geospatial.jp/iur/codelists/3.2/TrafficArea_function.xml
2+^h| 大分類 2+^h| 小分類 .2+^h| 定義
^h| コード ^h| 説明 ^h| コード ^h| 説明
.3+| 1000 .3+| 車道部 2+| | 主として自動車が利用する道路の部分のうち、自動車の通行の用に供される部分。
| 1010 | 車線 | 一縦列の自動車を安全かつ円滑に通行させるために設けられる帯状の車道の部分。
| 1020 | 車道交差部 | 十字路、丁字路、その他二つ以上の車道が交わる部分。
| 2000 | 歩道部 2+| | 自転車や歩行者のために供される道路の部分。植栽を含まない。

|===

[.source]
<<nilim_kiban_dps>>

// RWP commented out table below 20240917

////
[[tab-D-9]]
[cols="2a,2a,2a,3a,11a",options="noheader"]
.LOD3.2及びLOD3.3での交通領域の区分
|===
2+^h| 大分類 2+|  小分類 .2+|  定義
^h| コード |  説明 |  コード |  説明
.3+| 1000 .3+| 車道部 2+| | 主として自動車が利用する道路の部分のうち、自動車の通行の用に供される部分。
| 1010 | 車線 | 一縦列の自動車を安全かつ円滑に通行させるために設けられる帯状の車道の部分。
| 1020 | 車道交差部 | 十字路、丁字路、その他二つ以上の車道が交わる部分。
| 2000 3+| 歩道部 | 自転車や歩行者のために供される道路の部分。植栽を含まない。

|===

////


車道部（コード1000）は、車道内の車線（コード1010）、車道交差部（コード1020）以外の全ての部分となる。 +
さらに、LOD3.4では、より詳細に道路内を区分できる（<<tab-D-10>>）。この区分は、<<nilim_kiban_dps,道路基盤地図情報（整備促進版）製品仕様書（案）>>において道路面を構成する地物の区分に一致する。どこまで詳細な区分を行うかは、ユースケースに応じて決定してよい。

// this table is_common to both doc01 and doc02 slide30
[[tab-D-10]]
.LOD3.4での交通領域の区分
[cols="3a,3a,3a,3a,13a"]
|===
| ファイル名 4+| TrafficArea_function.xml

h| ファイルURL 4+| https://www.geospatial.jp/iur/codelists/3.2/TrafficArea_function.xml
2+^h| 大分類 2+^h| 小分類 .2+^h| 定義
^h| コード ^h| 説明 ^h| コード ^h| 説明
.8+| 1000
.8+| 車道部
2+|
| 主として自動車が利用する道路の部分のうち、自動車の通行の用に供される部分。 +
車線やすりつけ区間等区分されている以外の場所を全て車道部として取得する。

| 1010 | 車線 | 一縦列の自動車を安全かつ円滑に通行させるために設けられる帯状の車道の部分。
| 1020 | 車道交差部 | 十字路、丁字路、その他二つ以上の車道が交わる部分。
| 1030 | すりつけ区間 | 車線の数が増加もしくは減少する、又は道路が接続する場合に設けられる車道の部分。
| 1040 | 踏切道 | 鉄道と交差する道路の部分。
| 1050 | 軌道敷 | 路面電車が走行する道路の部分。
| 1070 | 待避所 | 一車線の道路において、車両のすれ違いのために車道の幅員を拡げる部分。
| 1130 | 副道 | 道路の構造により沿道との出入りが妨げられる場合に、沿道への出入りを確保するために本線車道に並行して設置される道路。
.4+| 2000 .4+| 歩道部 2+| | 自転車や歩行者のために供される道路の部分。
| 2010 | 自転車歩行者道 | 自転車及び歩行者の通行の用に供される道路の部分。
| 2020 | 歩道 | 歩行者の通行の用に供される道路の部分。
| 2030 | 自転車道 | 自転車の通行の用に供される道路の部分。
| 6000 | 自転車駐車場 2+| | 自転車駐車場のうち、走路部分。
| 7000 | 自動車駐車場 2+| | 自動車駐車場のうち、走路部分。

|===

[.source]
<<nilim_kiban_dps>>

// RWP commented out table below 20240917

////

[[tab-D-10]]
[cols="2a,2a,2a,3a,11a",options="noheader"]
.LOD3.4での交通領域の区分
|===
2+^h| 大分類 2+|  小分類 .2+|  定義
^h| コード |  説明 |  コード |  説明
.8+| 1000
.8+| 車道部
2+|
| 主として自動車が利用する道路の部分のうち、自動車の通行の用に供される部分。 +
車線やすりつけ区間等区分されている以外の場所を全て車道部として取得する。

| 1010 | 車線 | 一縦列の自動車を安全かつ円滑に通行させるために設けられる帯状の車道の部分。
| 1020 | 車道交差部 | 十字路、丁字路、その他二つ以上の車道が交わる部分。
| 1030 | すりつけ区間 | 車線の数が増加もしくは減少する場合又は道路が接続する場合に設けられる車道の部分。
| 1040 | 踏切道 | 鉄道と交差する道路の部分。
| 1050 | 軌道敷 | 路面電車が走行する道路の部分。
| 1070 | 待避所 | 一車線の道路において、車両のすれ違いのために車道の幅員を拡げる部分。
| 1130 | 副道 | 道路の構造により沿道との出入りが妨げられる場合に、沿道への出入りを確保するために本線車道に並行して設置される道路。
.4+| 2000 .4+| 歩道部 2+| | 自転車や歩行者のために供される道路の部分。
| 2010 | 自転車歩行者道 | 自転車及び歩行者の通行の用に供される道路の部分。
| 2020 | 歩道 | 歩行者の通行の用に供される道路の部分。
| 2030 | 自転車道 | 自転車の通行の用に供される道路の部分。
| 6000 3+| 自転車駐車場 | 自転車駐車場のうち、走路部分。
| 7000 3+| 自動車駐車場 | 自動車駐車場のうち、走路部分。

|===

////

車道部（コード1000）は、車道内の通行可能な範囲のうち、車線（コード1000）や車道交差部（コード1020）等、細分された道路の範囲以外の全てとなる。例えば、車両が転回するために設けられた、中央分離帯の切れ目などの部分がこれに該当する。


==== 交通領域の空間属性

道路面は一体的な面であり、その一体的な面を機能により交通領域や交通補助領域に区分している。そのため、道路を構成する交通領域は、他の交通領域や交通補助領域と重なることはない。また、道路を構成する交通領域は、隣接する他の交通領域や交通補助領域と隙間が空いていてはならない。

[requirement]
.tran:TrafficAreaの重なり禁止条件
====
[%metadata]
identifier:: /req/tran/9
subject:: 妥当な交通（道路）データセットの要件
description:: 同一のtran:Roadに含まれるtran:TrafficAreaの空間属性は、他のtran:TrafficAreaやtran:AuxiliaryTrafficAreaの空間属性と重なってはならない。 +
また、同一のtran:Roadに含まれるtran:TrafficAreaの空間属性は、隣接するtran:TrafficAreaやtran:AuxiliaryTrafficAreaの空間属性と、境界線の座標が一致しなければならない。
====


ただし、立体交差を2次元で表現する場合には空間属性が互いに重なってしまう。空間属性の重なりが妥当であるのか否かを判定するために、立体交差では必ず道路のインスタンスを分けなければならない。


==== 交通領域の主題属性

===== 機能（tran:function）

tran:functionは、区画線や路面標示、道路標識等により示された交通領域の機能であり、歩道や車道、分離帯のように、道路を横断方向に区分する属性である。 +
道路基盤地図情報が得られる場合にはこれが利用できる。道路基盤地図情報が得られない場合、LOD3.0までは道路台帳から取得できる。また、LOD3.1以上では航空写真やMMSから取得した画像や点群からの判読が必要となる。

===== 表面材質（tran:surfaceMaterial）

tran:surfaceMaterialは、表層舗装の有無及び材質である。同一の交通領域内に複数の表層舗装が混在している場合は、最も面積を占める表層舗装の材質とする。 +
舗装の材質は、工事完成図書、道路台帳又は現地調査により取得できる。ただし、埋設物管理に伴う掘削や車両乗り入れ口の設置に伴う歩道の切り下げ等の部分的な舗装工事が行われることが多く、最新の状態を把握可能な資料を網羅的に収集することは難しいこと、また、現地調査により最新の状態を把握できるが、広域を対象とする場合にはコストがかかることに注意が必要である。

===== 車線数（uro:numberOfLanesInArea）

uro:numberOfLanesInAreaは、交通領域内の車線数である。分離帯により上下が分離されている場合、この属性は当該交通領域（上り又は下り）に含まれる車線の合計数となる。 +
想定される取得方法を以下に示す。

. 都市計画基礎調査で収集されている場合は、これを使用する。

. 道路基盤地図情報より得られる場合は、これを使用する。

. 全国道路・街路交通量情勢調査（一般交通量調査）で収集されている場合は、これを使用する。

既存資料より得られない場合には、航空写真やMMSから取得した画像や点群を用いて判読する。 +
車線数は交通領域が車線に分離されていないLOD2及びLOD3.0において、車線数を把握したい場合に、車道部に対して作成する属性である。

