[[anchor-id]]
[heading="Normative references"]
[bibliography]

=== 引用規格等

// 20241211 rwp original === 引用文献

[.boilerplate]
--
本書が引用する規格・仕様・マニュアルを以下に示す。3D都市モデルの整備に際しては、これらの文献を理解することが前提となる。 +
引用文献のうちで、版の記載があるものは、その版を適用し、その後の改正版（追補を含む）は適用しない。版の記載がないものは、その最新版（追補を含む）を適用する。 +
また本書において、「i-UR」は、特段の指定がない限り、<<iurban_des>> を指す。また、「CityGML」についても同様に <<ogc_12-019>> を指す。
--

// .本書が準拠する規格等

* [[[plateau_prod_spec_4,PLATEAU Handbook #01]]],
span:organization[国土交通省 都市局].
span:title[3D都市モデル標準製品仕様書].
span:docid.PLATEAU[PLATEAU Handbook #01].
span:date[2024-03-29].
span:edition[第4.1版].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/].

* [[[plateau_010,PLATEAU Handbook #10]]],
span:organization[国土交通省 都市局].
span:title[3D都市モデル整備のための測量マニュアル].
span:docid.PLATEAU[PLATEAU Handbook #10].
span:date[2024-04-02].
span:edition[第3.0版].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/].

// 20250202 rwp single use xref in doc2; was missing in normrefs;

* [[[ifc_2x3_cv,IFC2x3 CV2.0]]],
span:title[IFC 2x3 Coordination View 2.0].
span:organization[buildingSMART International].
span:uri.citation[https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/]

// 20250202 end

* [[[iurban_des,i-UR 3.1]]],
span:title[Data Encoding Specification of i-Urban Revitalization -Urban Planning ADE- ver.3.1（内閣府地方創生推進事務局）].
span:uri.citation[https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur/index.html].

* [[[ogc_12-019,OGC 12-019]]],
span:title[OpenGIS® OGC City Geography Markup Language (CityGML) Encoding Standard, Version 2.0, OGC document 12-019].
span:uri.citation[https://www.ogc.org/standards/citygml]

* [[[ogc_05-099r2,OGC 05-099r2]]],
span:title[OpenGIS® GML 3.1.1 simple dictionary profile, Version 1.0.0, OGC document 05-099r2 ].
span:uri.citation[https://www.ogc.org/standards/gml]

* [[[ogc_19-008r4,OGC 19-008r4]]],
span:title[OpenGIS® OGC GeoTIFF Standard, Version 1.1, OGC document 19-008r4 ].
span:uri.citation[http://www.opengis.net/doc/IS/GeoTIFF/1.1]

* [[[jpgis_2014,JPGIS 2014]]],
span:title[地理情報標準プロファイル（JPGIS）2014].
span:organization[国土交通省 国土地理院].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[jmp20,JMP 2.0]]],
span:title[JMP2.0仕様書].
span:organization[国土交通省 国土地理院].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[jpgis_spec_reqs,JPGIS 品質の要求，評価及び報告のための規則]]],
span:title[品質の要求，評価及び報告のための規則].
span:organization[国土交通省 国土地理院].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

//* [[[gsi_ops,1]]],
//span:title[作業規程の準則].
* [[[gsi_ops,作業規程の準則について]]],
span:title[作業規程の準則].
span:organization[国土交通省 国土地理院].
span:uri.citation[https://www.gsi.go.jp/gijyutukanri/gijyutukanri41018.html]
// https://psgsv2.gsi.go.jp/koukyou/jyunsoku/

//* [[[mlit_foundation_reqs,1]]],
//span:title[都市計画基礎調査実施要領].
* [[[mlit_foundation_reqs,都市計画基礎調査実施要領]]],
span:title[都市計画基礎調査].
span:organization[国土交通省 都市局].
span:edition[第4版].
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/kisotyousa001.html]

//* [[[nilim_kiban_dps,1]]]
//span:title[道路基盤地図情報（整備促進版）製品仕様書（案）].
* [[[nilim_kiban_dps,道路基盤地図情報（整備促進版）製品仕様書（案）]]]
span:title[道路基盤地図情報製品仕様].
span:organization[国土交通省 国土技術政策総合研究所].
span:date[2014-05].
span:uri.citation[https://www.nilim.go.jp/lab/bcg/siryou/tnn/tnn0848pdf/ks084811.pdf]

* [[[iso_19101,ISO 19101]]]


