[title="Normative references"]
[bibliography]
=== 引用文献

本書が引用する規格・仕様・マニュアルを以下に示す。3D都市モデルの整備に際しては、これらの文献を理解することが前提となる。

// .本書が準拠する規格等

* [[[plateau_prod_spec_4,1]]],
span:title[3D都市モデル標準製品仕様書（国土交通省都市局）第4.0版].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/].

* [[[plateau_measure,1]]],
span:title[3D都市モデル測量マニュアル 第3.0版].
span:uri.citation[https://www.mlit.go.jp/plateau/libraries/].

* [[[iurban_des,1]]],
span:title[Data Encoding Specification of i-Urban Revitalization -Urban Planning ADE- ver.3.0（内閣府地方創生推進事務局）].
span:uri.citation[https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur/index.html].

* [[[ogc_12-019,(1)OGC 12-019]]],
span:title[OpenGIS® OGC City Geography Markup Language (CityGML) Encoding Standard, Version 2.0, OGC document 12-019 （Open Geospatial Consortium）].
span:uri.citation[https://www.ogc.org/standards/citygml]

* [[[ogc_05-099r2,(1)OGC 05-099r2]]],
span:title[OpenGIS® GML 3.1.1 simple dictionary profile, Version 1.0.0, OGC document 05-099r2 （Open Geospatial Consortium）].
span:uri.citation[https://www.ogc.org/standards/gml]

* [[[ogc_19-008r4,(1)OGC 19-008r4]]],
span:title[OpenGIS® OGC GeoTIFF Standard, Version 1.1, OGC document 19-008r4 （Open Geospatial Consortium）].
span:uri.citation[http://www.opengis.net/doc/IS/GeoTIFF/1.1]

* [[[jpgis_2014,1]]],
span:title[地理情報標準プロファイル（JPGIS）2014　（国土交通省国土地理院）].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[jmp20,1]]],
span:title[JMP2.0仕様書（国土交通省国土地理院）].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[jpgis_spec_reqs,1]]],
span:title[品質の要求，評価及び報告のための規則（国土交通省国土地理院）].
span:uri.citation[https://www.gsi.go.jp/GIS/jpgis-downloads.html]

* [[[gsi_ops,1]]],
span:title[作業規程の準則（国土交通省国土地理院）].
span:uri.citation[https://psgsv2.gsi.go.jp/koukyou/jyunsoku/]

* [[[mlit_foundation_reqs,1]]],
span:title[都市計画基礎調査実施要領（国土交通省都市局）].
span:uri.citation[https://www.mlit.go.jp/toshi/tosiko/kisotyousa001.html]

* [[[nilim_product_spec_sample,1]]],
span:title[道路基盤地図情報（整備促進版）製品仕様書（案）（国土交通省国土技術政策総合研究所）].
span:uri.citation[http://www.nilim-cdrw.jp/pv_std.html]

* [[[iso_19101,hidden(ISO 19101)]]]

引用文献のうちで、版の記載があるものは、その版を適用し、その後の改正版（追補を含む）は適用しない。版の記載がないものは、その最新版（追補を含む）を適用する。

また本書において、「i-UR」は、特段の指定がない限り、 <<iurban_des>> を指す。また、「CityGML」についても同様に <<ogc_12-019>> を指す。
