[[toc7_01]]
=== 配布書式情報

[[toc7_01_01]]
==== 書式名称

3D都市モデルの書式（データフォーマット）には、i-UR3.2及びCityGML2.0を採用する。

[[toc7_01_02]]
==== 符号化仕様

符号化仕様は、応用スキーマから交換データを導き出すための具体的な方法を示す。

===== 符号化要件

====== 符号化の対象とする応用スキーマとスキーマ言語

符号化の対象とする応用スキーマは、標準製品仕様の第4章において、UMLクラス図(ISO/IEC 19505-2:2012, Information technology — Object Management Group Unified Modeling Language (OMG UML) — Part 2:Superstructure)を用いて示す。

====== 使用する文字レパートリ

使用する文字レパートリはi-UR3.2及びCityGML2.0が採用しているUTF-8とし、W3C XML Schema及びそれに従って作成されるインスタンス文書のヘッダに以下の文を記述する。

[source,xml]
----
<?xml version=”1.0” encoding=”UTF-8” ?>
----

====== データ集合とオブジェクトの識別

データ集合とオブジェクトの識別はCityGML2.0に従う。

すなわち、基本となるオブジェクト単位は、CityGML2.0又はi-UR3.2に定義されたcore:_CityObjectを継承する地物型及びGMLに定義された幾何オブジェクトとする。また、データ集合は、core:CityModelとする。さらに、データ集合とオブジェクトの識別には、gml:idを用いる。

===== 入力データ構造

入力データ構造は、応用スキーマクラス図と実装される個々のインスタンスとの関係を示すものである。入力データ構造は、CityGMLが参照する<<gml_311,GML>>において定義されるAnnex F GML-to-UML Application Schema Encoding Rulesに従う。

===== 出力データ構造

出力データ構造には、i-UR3.2及びCityGML2.0を使用する。拡張子は、「.gml」とする。

===== 変換規則

====== スキーマ変換規則

スキーマ変換規則は、i-UR3.2及びCityGML2.0に従う。

なお、標準製品仕様書は、応用スキーマクラス図及びこれに対応するXMLSchemaを新規に作成するのではなく、i-UR3.2及びCityGML2.0から必要な部分のみを選択し、使用している。 +
応用スキーマクラス図に示す、クラス名、属性名及び関連役割名は、i-UR3.2及びCityGML2.0において定義されたタグに一致させている。

また、複数の名前空間から選択しているため、全てのクラス名に、i-UR3.2又はCityGML2.0名前空間の接頭辞を付ける。

====== インスタンス変換規則

GMLに準拠する。

* オブジェクト識別子（gml:id）
+
--
データ製品に含まれる全ての地物には、gml:idによる識別可能な値を与えることとし、その値には``[接頭辞]_[UUID]``を使用する。 +
``[接頭辞]``は、CityGML及びi-URの各パッケージに与えられた接頭辞（<<tab-7-4>>）を使用する。 +
``[UUID]``は、<<rfc_4122,Universally Unique Identifier（UUID）>>とする。UUIDとは、ソフトウェア上でオブジェクトを一意に識別するための識別子であり、128ビット（16バイト）の値で表す。先頭から4ビットごとに16進数の値（0～f）に変換し、8桁-4桁-4桁-4桁-12桁に区切って表現する。
--

* 集成の実装
+
--
応用スキーマに示された地物型間の集成は、部品となるオブジェクトを、全体となるオブジェクトの子要素として記述する。 +
この時、部品となるオブジェクトの識別子（gml:id）を、全体となるオブジェクト以外のオブジェクトが参照してもよい。
--

* 空間参照系の識別
+
--
幾何オブジェクトに適用される空間参照系は、都市モデル（core:CityModel）に挿入されるEnvelop要素の属性snsNameにおいて、以下のEPSGコードを挿入することにより識別する。

[cols="9a,4a"]
|===
| 空間参照系の名称 | srsNameに挿入する値

| 日本測地系2011 における経緯度座標系と東京湾平均海面を基準とする標高の複合座標参照系 | http://www.opengis.net/def/crs/EPSG/0/6697

|===
--

* schemaLocationの指定
+
--
i-URの符号化仕様は、3D都市モデル内のschemasフォルダ（7.2.4）に格納したXMLSchemaファイルへの相対パスによりschemaLocationを指定する。
--

* 出力すべきタグ
+
--
データ製品に含まれる全ての拡張製品仕様書において作成対象とする全ての主題属性及び空間属性のタグを出力しなければならない。
--

[[toc7_01_03]]
==== 文字集合

符号化したデータ集合を記述する文字集合には、「UTF-8」を使用する。

[[toc7_01_04]]
==== 言語

地物の属性の値を記述する言語は、日本語とする。

