[[tocI_02]]
=== 土地利用の記述とLOD


==== 使用可能な地物型とLOD

土地利用とは、都市計画基礎調査の土地利用現況をいう。 +
土地利用の記述には、CityGMLのLandUseモジュールに定義された、luse:LandUseを使用する。luse:LandUseは、詳細度（LOD）ごとに、使用すべき地物型やその空間属性が異なる。

標準製品仕様書では、土地利用モデルのLODは、LOD1のみを対象とする。


[requirement]
.土地利用モデル記述のLOD対応条件
====
[%metadata]
identifier:: /req/luse/1
subject:: 妥当な土地利用データセットの要件
description:: 土地利用モデルの記述には、指定されたLODに対応する地物型及び空間属性を使用する。
====

土地利用モデルの各LODにおいて使用可能な地物型と空間属性を、<<tab-I-1>>に示す。

[[tab-I-1]]
include::../../../common/sections/com_4_08_I_02_001.adoc[]

////
[cols="3a,3a,^a,^a,^a,^a,6a"]
.土地利用モデルの記述に使用する地物型と空間属性
|===
| 地物型 |  空間属性 |  LOD0 |  LOD1 |  LOD2 |  LOD3 |  適用

.5+| luse:LandUse | | |  ● | | | LOD1のみを対象とする。
| lod0MultiSurface | | | | |
| lod1MultiSurface | |  ● | | |
| lod2MultiSurface | | | | |
| lod3MultiSurface | | | | |

|===

[%key]
●:: 必須
■:: 条件付必須
〇:: 任意（ユースケースに応じて要否を決定してよい）
////

==== 土地利用モデルのLOD

土地利用モデル（LOD1）では、土地の形状を、高さをもたない面として表現する。


==== 土地利用の空間属性

===== LOD1

土地利用モデル（LOD1）では、土地利用の形状を、高さをもたない面として表現する。

標準製品仕様書において、土地利用は都市計画基礎調査の土地利用現況を指すことから、土地利用の空間属性は、都市計画基礎調査の土地利用現況の面と一致する。


==== 土地利用の主題属性

土地利用の主題属性は、都市計画基礎調査の土地利用現況により得られた情報である。原典資料として、GISデータ（土地利用現況）又は調書（土地利用現況）を使用できる。また、作成したデータの品質に関する情報を格納するための属性（uro:DataQualityAttribute）がある。

===== 土地利用分類（luse:class）

土地利用の用途の区分を指す。土地利用分類の区分は、<<mlit_foundation_reqs,都市計画基礎調査実施要領（国土交通省都市局）>>による区分（<<tab-I-2>>）とする。属性classは、全国共通の土地利用の区分に基づき各土地利用にコードを割り振ることで、広域での集計や地域の比較を行うことを目的としている。各都市独自の土地利用の区分に基づく分類は、土地利用詳細属性（uro:LandUseDetailAttribute）を使用して記述する。

[[tab-I-2]]
[cols="a,5a"]
.土地利用分類の区分
lutaml_gml_dictionary::iur/codelists/3.2/Common_landUseType.xml[template="gml_dict_template.liquid",context=dict]

////
|===
| コード | 説明

| 201 | 田（水田）
| 202 | 畑（畑、樹園地、採草地、養鶏（牛・豚）場）
| 203 | 山林（樹林地）
| 204 | 水面（河川水面、湖沼、ため池、用水路、濠、運河水面）
| 205 | その他自然地（原野・牧野、荒れ地（耕作放棄地等自然的状況のもの）、低湿地、河川敷・河原、海浜、湖岸）
| 211 | 住宅用地（住宅、共同住宅、店舗等併用住宅、店舗等併用共同住宅、作業所併用住宅）
| 212 | 商業用地（業務施設、商業施設、宿泊施設、商業系複合施設）
| 213 | 工業用地（工場）
| 219 | 農林漁業施設用地（農林漁業用施設）
| 214 | 公益施設用地（官公庁施設、文教厚生施設、供給処理施設）
| 215 | 道路用地（道路、駅前広場、私有地内に存在する沿道用途の「私道」または、私有地の一部分であるものの公共の通行に供されている土地の部分）
| 216 | 交通施設用地（運輸倉庫施設）
| 217 | 公共空地（公園・緑地、広場、運動場、墓園）
| 218 | その他公的施設用地（防衛施設用地）
| 220 | その他①（ゴルフ場）
| 221 | その他②（太陽光発電のシステムを直接整備している土地）
| 222 | その他③（平面駐車場）
| 223 | その他④（その他①～③以外の用途に供されている都市的土地利用（建物跡地、資材置場、改変工事中の土地）、法面（道路、造成地等の主利用に含まれない法面））
| 224 | 低未利用土地（用途に供されていない空地、空家・空き店舗・空施設の存する土地等）
| 231 | 不明
| 251 | 可住地
| 252 | 非可住地
| 260 | 農地（田、畑の区分がない）
| 261 | 宅地（住宅用地、商業用地等の区分が無い）
| 262 | 道路・鉄軌道敷（道路と交通施設用地が混在）
| 263 | 空地（その他の空地①～④の区分が無い）

|===
////

===== 土地利用詳細属性（uro:landUseDetailAttribute）

都市計画基礎調査の土地利用現況として記録された情報を格納するための属性である。属性の型であるuro:LandUseDetailAttributeには都市独自の土地利用の区分（uro:orgLandUse）の他、面積（uro:nominalArea）や建ぺい率（uro:buildingCoverageRate）など、様々な属性の箱が用意されている。都市計画基礎調査でこれらの情報が収集されている場合には、定義済みの属性を使用する。また、該当する属性が無い場合には、汎用属性を使用して拡張できる。

なお、都市独自の土地利用の区分（uro:orgLandUse）を作成する場合には、区分を示すコードリスト（LandUseDetailAttribute_orgLandUse.xml）を作成しなければならない。

===== データ品質属性（uro:DataQualityAttribute）

使用した原典資料やそれに基づくデータの品質、また、採用したLODは、データセットのメタデータに記録できる。ただし、データセット全体に対して一つのメタデータを作成することが基本となり、個々の都市オブジェクトの品質を記録することは困難である。

そこで、標準製品仕様書では、個々のデータに対してデータ品質に関する情報を記述するための属性として、「データ品質属性」（uro:DataQualityAttribute）を定義している。データ品質属性は、属性としてデータ作成に使用した原典資料の地図情報レベル、その他原典資料の諸元及び精緻化したLODをもつ。

3D都市モデルに含まれる全ての土地利用オブジェクトは、このデータ品質属性を必ず作成しなければならない。

