[[toc1_04]]
=== 標準製品仕様書の拡張
(((標準製品仕様書)))

((3D都市モデル))のユースケースに必要な地物等が標準製品仕様書に定義されておらず、地物型等の追加が必要な場合は、標準製品仕様書を拡張する。拡張のパターン（<<toc1_04_01>>）により、拡張の手順（<<toc1_04_02>>）が異なる。

[[toc1_04_01]]
==== 製品仕様の拡張パターン

追加したい地物型等の拡張パターンを<<tab-1-2>>に示す。

[[tab-1-2]]
[cols="4a,2a,7a,7a,3a",options="header"]
.標準製品仕様書の拡張パターン
|===
3+^| 拡張パターン ^| 例 ^| 手順書の箇条

.2+^| a +
属性又は関連役割を追加する
^| a-1 | コード型の地物属性を追加する | 建築物に属性として「新築区分」を追加する ^| <<toc1_04_02_01>>
^| a-2 | コード型以外の地物属性または地物関連を追加する | 建築物に属性として「建物1階面積」を追加する ^| <<toc1_04_02_02>>

.2+^| b +
標準製品仕様書に定義されていない地物型等を追加する
^| b-1 | i-URに存在する地物型等を追加する | 地物型として「都市再生緊急整備地域」を追加する ^| <<toc1_04_02_03>>
^| b-2 | i-URやCityGMLに存在しない地物型を追加する | 地物型として「通学区域」を追加する ^| <<toc1_04_02_04>>

|===

((i-UR))及び((CityGML))では、地物型として定義されていないが、地物属性を使うと表現できる場合がある。地物型及びその地物属性で区分可能な場合は、((i-UR))又は((CityGML))に存在するものとして扱う。例えば、((i-UR))及び((CityGML))には、「鳥獣保護区」という地物型はない。しかし、((i-UR))には、区域（urf:Zone）という地物型は定義されており、この地物型の定義は「法令により定められた区域」である。そこで、この地物型の属性functionの定義域に「鳥獣保護区」を追加することで、鳥獣保護区を表現可能となる。 +
このような場合には、<<tab-1-2>>の[underline]##b-2ではなく、b-1のパターンに該当するとして製品仕様を拡張##すること。
前述の例の場合、「鳥獣保護区」という新しい地物型を追加するのではなく、((i-UR))に定義されている「urf:Zone」の属性の定義域を拡張する。

[NOTE,type=commentary]
--
不足する地物型等を拡張製品仕様として追加する場合、i-URやCityGMLに定義されている地物型等を引用する。特にCityGMLには、都市を構成する様々な地物型が定義されているため、地物型については、概ねCityGMLから引用できる。また、概念的な区域を追加したい場合は、「urf:Zone」を拡張することで記述可能となる。

一方で、CityGMLでは、特定のユースケースが想定されておらず、基本的な地物属性しか定義されていない。そのため、ユースケースが要求する詳細な地物属性は、拡張手順に従い追加が必要になる場合がある。
--

[[toc1_04_02]]
==== 製品仕様の拡張手順

製品仕様の拡張手順を、<<toc1_04_01>>で示したパターンごとに示す。

[[toc1_04_02_01]]
===== コード型の地物属性を追加する場合

コード型の地物属性を追加したい場合は、以下の手順に従う。

(((拡張属性)))(((建築物)))(((標準製品仕様書)))
手順：

1）<<tocA_03_03>>に示す様式に従い、追加したいコード型の属性（拡張属性）のリストを作成する。作成例を<<tab-1-3>>に示す。

拡張属性のリストは、以下に示す事項を守り、作成すること。

* 拡張属性には「key」を与える。
** 「key」は、拡張属性の中で、一意となる番号とする。
** 「key」は、半角数字とし、100以降の連番を使用する。
* 追加した拡張属性ごとに、「説明」「定義」「多重度」「型」「定義域」「注釈」を記述する。
** 「説明」は、拡張属性の内容が分かる、簡潔な語句（名称）を記述する。
** 「定義」は、拡張属性の詳細な内容を示す。
** 「多重度」は、その拡張属性が一つの地物インスタンスに出現しうる回数を示す。
** 「型」は、コード型を示す「uro:codeValue」とする。この値は固定値である。
** 「定義域」には、次項で示す、拡張属性が取りうる値を格納するコードリストのファイル名を記述する。
** 「注釈」には、必要に応じて、当該拡張属性について特筆すべき事項を記述する。

[[tab-1-3]]
[cols="8a,17a,17a,7a,17a,17a,17a",options="header"]
.建築物の拡張属性リストの作成例（様式A.3.3）
|===
| key | 説明 | 定義 | 多重度 | 型 | 定義域 | 注釈

| 100
| 建築面積区分
| 建築物の建築面積の広さによる分類。

| 1
| uro::codeValue
| `keyValuePairAttribute_key100.xml`
|

|===

2）<<tocA_03_02>>に示す様式に従い、追加した拡張属性ごとに、定義域を示すコードリストを作成する。作成例を<<tab-1-4>>に示す。

コードリストは、以下に示す事項を守り、作成すること。

* 取りうる「コード」とその「説明」を対として記述する。
** 「説明」は、コードの内容が分かるように記述すること。
*** 例えば、建築物の用途を定義する際に、コードの説明が「娯楽施設1」では、対象となる施設に何が含まれるのか分からない。このような場合には、「娯楽施設1（劇場、映画館、演芸場、観覧場、料理店）」というように、説明や事例を付する。
* 「コード」の値は半角数字とする。
* 一つのコードリストには「コード」を一つ以上作成しなければならない。
* 一つのコードリストにおいて、「コード」及びその「説明」は一意でなければならない。
* コードリストのファイル名は以下とする。
** "`KeyValuePairAttribute_keyX.xml`" ： "`X`" は、拡張属性を識別するkeyの値（半角数字）と一致する。

[[tab-1-4]]
[cols="1a,3a"]
.拡張コードリストの作成例（様式 A.3.2）
|===
h| ファイル名 | KeyValuePairAttribute_key100.xml
h| コード h| 説明
| 701 | 50㎡以下
| 702 | 75㎡以下
| 703 | 150㎡以下
| 704 | 500㎡以下
| 705 | 1500㎡以下
| 706 | 1500㎡超
| 711 | 不明

|===


　


[NOTE,type=commentary]
--
コード型（gml:CodeType）とは、取りうる値があらかじめコードとしてリスト化され、その中からコードを選択して記述するデータ型である。コード型の属性を追加する場合は、追加した属性ごとに「コード及びコードに対応する説明のリスト」（コードリスト）が必要となる。

CityGMLでは、定義済みの地物型に地物属性を追加するための汎用的な属性が、値の型ごとに用意されている（<<anchor-id>>参照）が、コード型をとる汎用的な属性の型は用意されていない。コード型は取りうる値をコードリストに定義することでデータの品質管理を容易にする利点があることから、本書では、コード型の属性を追加する場合は、i-URに定義されている拡張属性を採用することとしている。

なお、i-UR3.0（標準製品仕様書第3.5版までに対応）では、建築物にのみコード型の属性を追加する拡張属性の仕組みが定義されていたが、i-UR3.1（標準製品仕様書第4.1版に対応）では、道路や土地利用など、様々な地物型にこの拡張属性の仕組みが追加されたことから、本書では、全ての地物型について、コード型の属性を追加する場合は、拡張属性を採用する。
--

[[toc1_04_02_02]]
===== コード型以外の地物属性又は地物関連を追加する場合

コード型以外の地物属性を追加したい場合、また、地物関連を追加したい場合は、((汎用属性))（gen:_GenericAttribute）の下位型を使用し、以下の手順により拡張する。

(((汎用属性)))(((汎用属性)))(((汎用属性セット)))(((CityGML)))(((3D都市モデル)))
手順：

1）<<tocA_03_06>>の様式「汎用属性」に従い、地物ごとに追加する地物属性及び地物関連のリストを作成する。

* 地物型には、地物属性及び地物関連を追加する地物型の名称を記述する。
+
ただし、汎用都市オブジェクト（gen:GenericCityObject）に地物属性及び地物関連を追加する場合は、追加の対象を明確にするため、gen:GenericCityObjectのgml:nameの値を注釈として記述する。

* 地物属性の型は汎用属性の下位型である以下のいずれかから選択する。
** gen:stringAttribute（文字列型）
** gen:intAttribute（整数型）
** gen:doubleAttribute（実数型）
** gen:dateAttribute（日付型）
** gen:uriAttribute（URI型）
** gen:measureAttribute（単位付き計測値型）
*** gen:measureAttributeを使用する場合は、uom属性により、その単位を指定しなければならない。長さの単位は「メートル」（uom=”m”）、大きさの単位は「平方メートル」（uom=”m2”）又は「ヘクタール」（uom=”ha”）、時間の単位は「時間」（uom=”hour”）を基本とする。
** gen:genericAttributeSet（汎用属性セット型）
*** gen:genericAttributeSetは、複数の汎用属性の集まりである。gen:genericAttributeSetは、gen:stringAttributeやgen:intAttributeなどの汎用属性を複数個組み合わせてひとまとめにできる。
* 地物関連の型は汎用属性の下位型である以下を選択する。
** gen:uriAttribute（URI型）
* 「名称」には、追加したい地物属性又は関連役割の名称を記述する。このとき、同じ地物型に、同じ地物属性や関連役割の名称を与えてはならない。
* 「定義」には、追加する地物属性又は地物関連の説明を記述する。
* 取りうる値が限定される場合には「定義域」に記述する。
* その他特筆事項がある場合には「注釈」に記述する。
+
--
<<tab-1-5>>に、汎用属性を用いて属性を追加する場合の例を示す。

[[tab-1-5]]
[cols="a,a,a,a,a,a,a,a"]
.汎用属性の追加例
|===
| 地物型 2+| gen::GenericCityObject | 注釈 4+| gml:name=20の場合に適用

.5+h| 汎用属性 h| 属性の型 h| 名称 h| 定義 h| 多重度 h| 定義域 h| 単位 h| 注釈
| gen::stringAttribute | 通学区域名称 | 通学区域に指定された就学校の名前 | 1 | 全角20文字以内 | － |
|  |  |  |  |  |  | 
|  |  |  |  |  |  | 
|  |  |  |  |  |  | 

|===
--

* 汎用都市オブジェクト（gen:GenericCityObject）は、拡張属性（<<toc1_04_02_01>>参照）を使用することができない。そのため、汎用都市オブジェクトにコード型の属性を追加する場合は、コードと参照するコードリストの対をgen:genericAttributeSetとして追加することを推奨する。
** コードを格納する汎用属性の名称は、codeとする。
** コードリストのファイル名称を格納する汎用属性の名称は、codeSpaceとする。
** いずれも属性の型は文字列型（gen:stringAttribute）とする。
** コードリストの名称は、``[地物型名称]_generic-[オプション]``とする。``[地物型名称]``は、応用スキーマクラス図に示される地物型の名称（接頭辞は除く）とする。``[オプション]``は任意の半角英数字とするが、同じ地物型の中では重複してはならない。
** なお、gen:GenericCityObjectにコード型の属性を追加する場合、コードリストの名称は +
``GenericCityObject_generic-[オプション]`` +
となる。gen:GenericCityObjectを用いて複数種類の地物を追加する場合は、どの地物に対するコードリストであるかが分かりづらくなるため、``[オプション]``は追加する +
``[地物の名称]-[属性の名称]`` +
とする。
*** 地物の名称は、gml:nameにおいて指定されるコードとする。
*** 属性の名称は、半角英数字で構成される任意の文字列とする。ただし、gml:nameが同じとなる地物に定義する属性の中では一意でなければならない。
*** 例えば、gen:GenericCityObjectを使用して「通学区域」（gml:name=”20”）を追加し、かつ、汎用属性セットを使って「通学区域」の種類をコード型の属性として追加する場合、コードリストの名称は、GenericCityObject_generic-20-typeとなる。
** コードリストの名称は、gen:stringAttributeとして追加したcodeSpaceの定義域に記載する。
** コード型を追加する場合の汎用属性セットの使用例を<<tab-1-6>>に示す。
+
--
[[tab-1-6]]
[cols="2a,3a,2a,4a,1a,4a,1a,4a"]
.汎用属性セットの使用例
|===
^h| 名称 2+| 施設一覧 ^h| 注釈 4+| 汎用都市オブジェクトのうち、name=20の場合に適用する。
^h| 汎用属性セット
7+| 市内に存在する公共施設の名称を一覧から選択し記述するための汎用属性セット。 +
コード型の代替として使用することを目的とし、codeSpaceに公共施設名称のコードリストへの相対パスを記述し、codeに当該コードリストに定義された値を記述する。
.3+^h| 汎用属性セットに含まれる汎用属性 ^h| 属性の型 ^h| 名称 ^h| 定義 ^h| 多重度 h| 定義域 ^h| 単位 h| 注釈
| gen::stringAttribute | codeSpace | 公共施設名称一覧への参照。
| 1 | 相対パスにより記述する。
| |
| gen::stringAttribute | code | 公共施設を示すコード。
| 1 | 公共施設名称一覧に定義されたコード。
| |

|===
--
* gen:genericAttributeSetには、gen:genericAttributeSetを含めてはならない。
** CityGMLでは、gen:genericAttributeSetがgen:genericAttributeSetをもつこと（ネスト構造）が可能である。ただし、データ構造の階層が深くなるため、3D都市モデルではネスト構造を使用しない。

[NOTE,type=commentary]
--
i-URでは、拡張属性としてコード型の属性を追加する仕組みをADEに定義している。しかしながら、gen:GenericCityObjectは、CityGMLにおいて暫定的な拡張方法という位置づけから、ADEで追加された属性等をもつ仕組みが用意されていない。そのため、汎用属性セットを使って、コードの値とコードリストへの参照をひとかたまりとして追加する方法を推奨している。

「汎用属性セット」を用いると、複数の汎用属性をひとかたまりとして追加できる。例えば、建物の改修履歴に関する情報として、改修時期、改修内容、改修事業者名を追加したいとする。この場合、改修履歴という汎用属性セットを作成し、この汎用属性セットに改修時期、改修内容、改修事業者名をそれぞれ汎用属性として加えればよい。これにより、建物に複数回の改修工事があった場合でも、改修工事ごとにまとめて改修履歴として改修時期、改修内容、改修事業者名を記述できるようになる。

同様にして、汎用属性セットを使用すると、コードとこれが参照するコードリストをまとめて記述できる。これにより、プログラムによるコードリストを使った論理検査の実施が容易になる。また、今後CityGML3.0に移行する際に、追加したコード型の汎用属性に変換することができる。
--

[[toc1_04_02_03]]
===== i-UR又はCityGMLに存在する地物型等を追加する場合

((標準製品仕様書))に定義されていないが、((i-UR))又は((CityGML))のいずれかに定義されている地物型等を追加する場合には、以下の手順により拡張する。

(((i-UR)))(((CityGML)))
手順：

1）追加したい地物型等について、応用スキーマクラス図及び応用スキーマ文書を作成する。応用スキーマクラス図は、i-UR及びCityGMLの仕様（<<anchor-id>>参照）に従う。また、応用スキーマ文書の作成には、<<tocA_03_04>>に示す様式を用いる。

応用スキーマ文書は、以下の事項を守り作成すること。

* 地物型等の名称には、i-URやCityGMLで定義された名称を使用する。
* 多重度や地物属性/地物関連の型はi-UR及びCityGMLの定義を変更してはならない。
** より厳密にしたい場合には注釈にその内容を記述する。
** コード型属性を追加する場合、コードリストの名称は、``[地物型名称]\_[属性名称]``（拡張子を含めると``[地物型名称]_[属性名称].xml``）とする。
** ``[地物型名称]``は応用スキーマクラス図に記載された地物型の名称（接頭辞は除く）とし、``[属性名称]``は応用スキーマクラス図に記載された属性名称（接頭辞は除く）とする。

[NOTE,type=commentary]
--
追加したい地物型等が、i-UR又はCityGMLに存在する場合には、これらから矛盾なく引用しなければならない。属性の型や多重度は原則として変更できないが、より制限を強めることはできる。例えば、多重度が[0..1]となっている地物属性を[1]としてもよい。また、文字列型となっている属性の定義域を「全角10文字以内」というように制限してもよい。ただし、i-URやCityGMLそのものを変更することはできないため、符号化仕様（XMLSchema）についても修正は行えない。よって、符号化仕様を使った妥当性の検証ができないことに注意すること。

例：多重度が[0..1]となっている属性を、応用スキーマ文書で[1]にした場合であっても、符号化仕様では、[0..1]のままとなるため、当該属性が記述されていなくてもエラーとしては検出されない。別途検証ツールを作成する必要がある。

本書では、3D都市モデルが様々な用途・ソフトウェア上で利用され、より普及していくことを目指し、複数の選択肢がある場合には、より実装例の多い選択肢の使用を推奨している。
--

[[toc1_04_02_04]]
===== i-URやCityGMLに存在しない地物型を追加する場合

((標準製品仕様書))に定義されておらず、((i-UR))及び((CityGML))にも定義されていない地物型を追加する場合には、CityGMLに定義されているgen:GenericCityObjectを使用し、以下の手順により拡張する。

(((標準製品仕様書)))
手順：

1）様式に示される汎用都市オブジェクトの名称リスト（GenericCityObject_name.xml）に、追加する地物型のコード及び説明を追加する。<<tab-1-7>>に例を示す。

汎用都市オブジェクトの名称リストは、以下の事項を守り作成すること。

* 「コード」は、20以上の半角数字とする。
* 「説明」に、追加する地物型の名称を記述する。
* 追加する汎用都市オブジェクトのコード及び説明は、汎用都市オブジェクトの名称リストの中で一意でなければならない。

[[tab-1-7]]
[cols="1a,3a"]
.汎用都市オブジェクトの追加例
|===
| ファイル名 | GenericCityObject_name.xml
h| コード h| 説明
| 20 | 通学区域

|===

2）追加する地物型の応用スキーマ文書を作成する。応用スキーマ文書の作成は、<<tocA_03_05>>に示すgen:GenericCityObjectの応用スキーマ文書を加工する。
これは、[underline]##追加する地物型ごと##に行う。

汎用都市オブジェクトの応用スキーマ文書は、以下の事項を守り作成すること。

* 汎用都市オブジェクトの定義欄に、追加したい地物型の定義を記述する。
* 「gml:name」は必須とし、定義域に追加したい地物型に該当するコードを記述する。
* その他の地物属性/地物関連のうち、作成対象とするものは、その定義を記述する。特に、空間属性は、使用する幾何オブジェクトの型（幾何型）及び取得基準を必ず記述する。
** 幾何型の詳細な定義は、標準製品仕様書の空間スキーマ及び本書の<<tocB>>を参照すること。
* 作成対象としないものは、作成対象としないことが分かるように記述する。
** 作成対象としない属性及び関連役割は、属性名称及び関連役割名称を括弧で囲む。

汎用都市オブジェクトの応用スキーマ文書の作成例を、<<tab-1-8>>に示す。 +
属性名又は関連役割名が括弧で囲まれているものは、本データ製品仕様書の対象外とする属性又は関連役割である。

[[tab-1-8]]
[cols="1a,1a,2a"]
.汎用都市オブジェクトの応用スキーマ文書の作成例
|===

h| クラスの定義 2+| CityGMLに定義されていない地物を定義するための汎用的な地物型。

h| 上位の型 2+| core:_CityObject 

h| ステレオタイプ 2+| << FeatureType >> 

3+h| 継承する属性 

h| 属性名 h| 属性の型及び多重度 h| 定義

| (gml:description) | gml:StringOrRefType [0..1] | 汎用都市オブジェクトの説明。
| gml:name
| gml:CodeType [0..1]
| 汎用都市オブジェクトを識別する名称。

コードリスト（GenericCityObject_name.xml）から選択する。

「通学区域」は20とする。

| (gml:boundedBy) | gml:Envelope [0..1] |
| (core:creationDate) | xs:date [0..1] | 汎用都市オブジェクトが発生した年月日。
| (core:terminationDate) | xs:date [0..1] | 汎用都市オブジェクトが消滅した年月日。
3+h| 自身に定義された属性
h| 属性名 h| 属性の型及び多重度 h| 定義
| gen:class
| gml:CodeType [0..1]
| 汎用都市オブジェクトの区分。

小学校区か中学校区かの区分。コードリスト（GenericCityObject_class.xml）から選択する。

| (gen:function) | gml:CodeType [0..*] | 汎用都市オブジェクトの機能。
| (gen:usage) | gml:CodeType [0..*] | 汎用都市オブジェクトの用途。
3+h| 継承する関連役割
h| 関連役割名 h| 関連役割の型及び多重度 h| 定義
| gen:stringAttribute
| gen:stringAttribute [0..*]
| 汎用都市オブジェクトの文字列型属性。

通学区域が設定された学校の名称。

| (gen:intAttribute) | gen:intAttribute [0..*] | 汎用都市オブジェクトの整数型属性。
| (gen:doubleAttribute) | gen:doubleAttribute [0..*] | 汎用都市オブジェクトの実数型属性。
| (gen:dateAttribute) | gen:dateAttribute [0..*] | 汎用都市オブジェクトの日付型属性。
| (gen:uriAttribute) | gen:uriAttribute [0..*] | 汎用都市オブジェクトのURI型属性。
| (gen:measureAttribute) | gen:measureAttribute [0..*] | 汎用都市オブジェクトの単位付き数値型属性。
| (gen:genericAttributeSet) | gen:genericAttributeSet[0..*] | 汎用オブジェクトの汎用属性セット。
3+h| 自身に定義された関連役割
h| 関連役割名 h| 関連役割の型及び多重度 h| 定義
| (gen:lod0Geometry) | gml:_Geometry [0..1] | 汎用都市オブジェクトの形状。
| gen:lod1Geometry
| gml:_Geometry [0..1]
| 汎用都市オブジェクトの形状。

通学区域の外形線により囲まれた面とする。高さは0とする。

gml:MultiSurfaceを使用する。

| (gen:lod2Geometry) | gml:_Geometry [0..1] | 汎用都市オブジェクトの形状。
| (gen:lod3Geometry) | gml:_Geometry [0..1] | 汎用都市オブジェクトの形状。
| (gen:lod4Geometry) | gml:_Geometry [0..1] | 汎用都市オブジェクトの形状。

|===

NOTE: 赤字は記載例

3）前項において、コード型の属性を選択する場合には、拡張コードリスト（<<tab-1-9>>）を作成する。

[[tab-1-9]]
[cols="1a,3a"]
.汎用都市オブジェクトのためのコードリスト作成例
|===
| ファイル名 | genericCityObject_function.xml
h| コード h| 説明
| 1 | 小学校
| 2 | 中学校

|===

4）新しく追加した地物型に、gen:GenericCityObjectに定義されていない地物属性及び地物関連を追加する場合には、次項に示す地物属性/地物関連を追加する手順に従う。

