[[tocW_06]]
=== 一部更新における拡張製品仕様書及びメタデータの作成

一部更新においても、データ製品に含む拡張製品仕様書及びメタデータは、最新の版に準拠して作成しなければならない。このとき、更新する地物型と更新しない地物型を統合したデータセットがデータ製品となるため、作成する拡張製品仕様書及びメタデータは、更新する地物型と更新しない地物型の両方を網羅する記述としなければならない。

加えて、地物型ごとに準拠する標準製品仕様書の版を明確にするため、拡張製品仕様書及びメタデータにおいて、地物型ごとに準拠する標準製品仕様書の版を記述する。

[[tocW_06_01]]
==== 拡張製品仕様書

拡張製品仕様書は最新の版のテンプレートを用いて作成する。例えば、標準製品仕様書第4.1版に準拠する地物型と標準製品仕様書第5.1版に準拠する地物型が混在するデータ製品となる場合は、標準製品仕様書第5.1版のテンプレートを用いて拡張製品仕様書を作成する。

各地物型に準拠する標準製品仕様書の版は、拡張製品仕様書の「4.1.1 本製品仕様書が対象とする地物とLOD」に示す表「本製品仕様書が対象とするLODと準拠する標準製品仕様書の版」に記述する。記述する箇所は、「準拠する標準製品仕様書の版」の欄とし、記述する内容は標準製品仕様書の版を示す番号とする。

例えば、ある都市において、標準製品仕様書第4.1版に準拠した基本セットが整備されており、交通（道路）モデルのみ標準製品仕様書第5.1版に準拠して更新するとする。このとき、データ製品には、標準製品仕様書第5.1版に準拠した「交通（道路）モデル」と、標準製品仕様書第4.1版に準拠した建築物モデル等が含まれることになる。この場合、交通（道路）の「準拠する標準製品仕様書の版」の欄に「5.1」を記述し、「交通（道路）」以外の地物型には「4.1」を記述する。記述例を<<tab-W-1>>に示す。

[[tab-W-1]]
[cols="4a,^a,^a,^a,^a,^a,^5a"]
.本製品仕様書が対象とするLODと準拠する標準製品仕様書の版の例
|===

^| LOD | LOD0 | LOD1 | LOD2 | LOD3 | LOD4 | 準拠する +
標準製品仕様書の版

| 建築物 | 〇 | 〇 | 〇 | 　 | 　 | 4.1
| 交通（道路） | 　 | 〇 | 　 | 　 | 　 | 5.1
| 交通（徒歩道） | 　 | 　 | 　 | 　 | 　 | 　
| 交通（広場） | 　 | 　 | 　 | 　 | 　 | 　
| 交通（鉄道） | 　 | 　 | 　 | 　 | 　 | 　
| 交通（航路） | 　 | 　 | 　 | 　 | 　 | 　
| 都市計画決定情報 | 　 | 〇 | 　 | 　 | 　 | 4.1 
| 土地利用 | 　 | 〇 | 　 | 　 | 　 | 4.1
| 災害リスク | 　 | 〇 | 　 | 　 | 　 | 4.1
| 都市設備 | 　 | 　 | 　 | 　 | 　 | 　
| 植生 | 　 | 　 | 　 | 　 | 　 | 　
| 水部 | 　 | 　 | 　 | 　 | 　 | 　
| 地形 | 　 | 〇 | 　 | 　 | 　 | 4.1
| 橋梁 | 　 | 　 | 　 | 　 | 　 | 　
| トンネル | 　 | 　 | 　 | 　 | 　 | 　
| その他の構造物 | 　 | 　 | 　 | 　 | 　 | 　
| 地下街 | 　 | 　 | 　 | 　 | 　 | 　
| 地下埋設物 | 　 | 　 | 　 | 　 | 　 | 　
| 区域 | 　 | 　 | 　 | 　 | 　 | 　
| 汎用都市オブジェクト | 　 | 　 | 　 | 　 | 　 | 　

|===

[%key]
〇:: LOD対応


[[tocW_06_02]]
==== メタデータ（JMP2.0）

一部更新により更新した地物型について、JMP2.0に基づくメタデータを作成する。このメタデータは、既存の3D都市モデルのメタデータとは分け、新たに作成する。つまり、一部更新をした際は、成果品のフォルダに更新前の3D都市モデルのメタデータと、更新後のメタデータとの複数のメタデータが存在する。

一部更新において作成するメタデータの記述項目は、最新の標準製品仕様書に従う。ただし、記述する内容は、更新の内容が反映されてなければならない。一部更新を行った場合のメタデータの記述例と留意事項を<<tab-W-2>>に示す。

[[tab-W-2]]
[cols="1a,4a,4a"]
.作成すべきメタデータ項目
|===
^| メタデータ項目 ^| 記述する内容 ^| 記述例

| メタデータ>ファイル識別子 
| 最新の標準製品仕様書に準拠する。

一部更新の内容に応じて、以下に留意すること。なお、他のメタデータのファイル識別子と重複が生じる場合は``[オプション]``を使用し、重複がないようにすること。

* 地物型を追加する場合 +
``[整備年度]``は、更新を行った年度とする。 +
``[地物型]``として、追加した地物型の接頭辞を付ける。
+
　
+
なお、二つ以上の地物型を追加した場合は、``[地物型]``を省略し、まとめて一つのメタデータファイルとしてよい。
+
　

* 地物を追加する場合 +
``[整備年度]``は、更新を行った年度とする。 +
``[地物型]``として、追加した地物に対応する地物型の接頭辞を付ける。
+
　
+
なお、二つ以上の地物型を追加した場合は、``[地物型]``を省略し、まとめて一つのメタデータファイルとしてよい。
+
　

* 空間属性を追加する場合 +
``[整備年度]``は、更新前のメタデータファイル名の``[整備年度]``に一致させる。 +
``[地物型]``として、追加した地物に対応する地物型の接頭辞を付ける。
+
　
+
なお、二つ以上の地物型を追加した場合は、``[地物型]``を省略し、まとめて一つのメタデータファイルとしてよい。
+
　
+
``[オプション]``として、「V``[一部更新の回数]``」を付与する。``[一部更新の回数]``は半角数字とする。
+
　

* 主題属性を追加する場合 +
``[整備年度]``は、更新前のメタデータファイル名の``[整備年度]``に一致させる。 +
``[地物型]``として、追加した地物に対応する地物型の接頭辞を付ける。
+
　
+
なお、二つ以上の地物型を追加した場合は、``[地物型]``を省略し、まとめて一つのメタデータファイルとしてよい。
+
　
+
``[オプション]``として、「V``[一部更新の回数]``」を付与する。``[一部更新の回数]``は半角数字とする。
+
　

* メタデータファイル名の ``[整備年度]``を更新を行った年度とする一部更新と、更新前のメタデータファイル名の``[整備年度]``に一致させる一部更新を同時に行った場合 +
``[整備年度]``は、更新を行った年度とする。 +
``[地物型]``として、追加した地物に対応する地物型の接頭辞を付ける。
+
　
+
なお、二つ以上の地物型を追加した場合は、``[地物型]``を省略し、まとめて一つのメタデータファイルとしてよい。
| 2025年度に基本セットが新規整備されたデータ製品を、2026年度に一部更新した場合の記述例を以下に示す。

* 地物型の追加 [都市設備モデルを新規に整備した場合] +
udx_27100_city_2026_frn +
udx_27100_city_2026_frn_op
+
　

* 地物の追加 [建築物モデルの整備エリアを拡大した場合] +
udx_27100_city_2026_bldg +
udx_27100_city_2026_bldg_op
+
　

* 空間属性の追加 [建築物モデルにLOD2を追加した場合] +
udx_27100_city_2025_bldg_V1 +
udx_27100_city_2025_bldg_V1_op
+
　

* 主題属性の追加[建築物モデルに都市計画基礎調査の情報を属性として追加した場合] +
udx_27100_city_2025_bldg_V1 +
udx_27100_city_2025_bldg_V1_op
+
　

* 地物型の追加 [都市設備モデルを新規に整備した場合]と空間属性の追加 [建築物モデルにLOD2を追加した場合] +
udx_27100_city_2026 +
udx_27100_city_2026 _op

| メタデータ>日付 
| 最新の標準製品仕様書に準拠する。

新しく作成したメタデータの作成日付をYYYY-MM-DDにより記述する。
| 2026-03-19

| 参照系情報 
| 最新の標準製品仕様書に準拠する。

更新した地物の空間参照系の識別子を記述する。識別子は、JMP2.0を参照する。
| JGD2011, TP / (B, L), H

| 識別情報>題名 
| 最新の標準製品仕様書に準拠する。 
| 3D都市モデル_27100_city_2025

| 識別情報>日付及び日付型 
| 最新の標準製品仕様書に準拠する。 
| 2026-03-19, 003

| 識別情報 >目的 
| 最新の標準製品仕様書に準拠し、更新した内容を反映する。 
| 災害リスクの３次元可視化

.2+| 識別情報>問い合わせ先 
.2+| 最新の標準製品仕様書に準拠し、更新した内容を反映する。

作成者の問合せ情報は更新を行った整備事業者を記述する。
| 010（固定値） +
国土交通省都市局 +
03-5253-8397 +
http://www.mlit.go.jp/plateau/

| 060（固定値） +
○○株式会社 +
www.sample.co.jp

| 識別情報 > 記述的キーワード
| 最新の標準製品仕様書に準拠し、更新した内容を反映する。
| 東京23区, 002 +
建築物, 005 +
LOD1, 005 +
景観シミュレーション, 005 +
都市計画基本図, 005

| 識別情報>空間解像度
| 最新の標準製品仕様書に準拠し、更新した内容を反映する。
| 2500

| 識別情報> 範囲
| 最新の標準製品仕様書に準拠し、更新した内容を反映する。
| LOD1の作成範囲は●●市全域、LOD2の作成範囲は、△△駅を中心とする半径約300m内。

| データ品質情報>データ品質
| 最新の標準製品仕様書に準拠し、更新した内容を反映する。

なお、一部更新を行った場合、データ製品には更新前のメタデータも格納することから、更新前のメタデータには、更新した内容が反映されていない。そのため、系譜には、以下を含む説明を記述すること。

* 更新前のデータ製品の名称
* 更新の年度
* 更新の内容：「地物型の追加」、「地物の追加」、「空間属性の追加」、「主題属性の追加」のいずれか
* 更新の対象となる地物型
* 更新の対象となる範囲（更新したエリア、追加となるLODや主題属性等）
| 

* 地物型の追加 ``[都市設備モデルを新規に整備した場合]``
+
本データ製品は、「3D都市モデル_27100_city_2025」の一部更新として、2026年度に整備した都市設備モデルを追加したものです。 +
都市設備モデル以外のデータは、「3D都市モデル_27100_city_2025」から更新されていないことに注意してください。
+
　

* 地物の追加 ``[建築物モデルの整備エリアを拡大した場合]``
+
本データ製品は、「3D都市モデル_27100_city_2025」の一部更新として、2026年度に整備した都市計画区域外の建築物モデルを追加したものです。 +
都市計画区域外の建築物モデル以外のデータは、「3D都市モデル_27100_city_2025」から更新されていないことに注意してください。
+
　

* 空間属性の追加 ``[建築物モデルにLOD2を追加した場合]``
+
本データ製品は、「3D都市モデル_27100_city_2025」の一部更新として、2026年度に整備した建築物モデル（LOD2）を追加したものです。一部更新の範囲は、△△駅を中心とする半径約300m内です。 +
一部更新により追加した建築物モデル（LOD2）以外のデータは、「3D都市モデル_27100_city_2025」から更新されていないことに注意してください。
+
　

* 主題属性の追加``[建築物モデルに都市計画基礎調査の情報を属性として追加]``
+
本データ製品は、「3D都市モデル_27100_city_2025」の一部更新として、2026年度に建築物モデルの属性として、都市計画基礎調査から得られた情報を追加したものです。 +
追加した建築物モデルの属性以外のデータは、「3D都市モデル_27100_city_2025」から更新されていないことに注意してください。
+
　

* 複合的な一部更新を行った場合の記述例``[交通（道路）モデルの地物の追加と建築物モデルの主題属性を追加]``
+
本データ製品は、「3D都市モデル_27100_city_2025」の一部更新として、2026年度に都市計画区域の交通（道路）モデルの追加と建築物モデルの主題属性（高潮浸水リスク：説明、浸水リスク）を追加したものです。 +
交通（道路）モデルと建築物モデル以外のデータは、「3D都市モデル_27100_city_2025」から更新されていないことに注意してください。

|===

[[tocW_06_03]]
==== READMEへの記載

READMEは、最新版のテンプレートを用いて作成する。『準拠する標準製品仕様書の版』欄に、各地物型が準拠する標準製品仕様書の版を記載する。例えば、標準製品仕様書第4.1版に準拠して基本セットが作成されており、建築物モデルと交通（道路）モデルを標準製品仕様書第5.1版に準拠して更新する際は、<<fig-W-4>>の記述内容とする。

[[fig-W-4]]
.READMEへの記述例
----
##準拠する標準製品仕様書の版

3D都市モデル標準製品仕様書　第4.1版（土地利用、都市計画決定情報、災害リスク、地形）
3D都市モデル標準製品仕様書　第5.1版（建築物、交通（道路））
----


[[tocW_06_04]]
==== 取得項目一覧への記載

拡張製品仕様書に格納する取得項目一覧（様式A.3.1取得項目一覧）は最新版のテンプレートを用いて作成する。

取得項目一覧には、更新した地物型の内容を反映する。また、更新しなかった地物型については、既存のデータ製品に含まれる取得項目一覧（ルートフォルダ直下に作成されたspecificationフォルダに格納）から作成対象を転記すること。

