[[toc5_03]]
=== メタデータの作成

メタデータとは、データ（ここでは、「((3D都市モデル))」）を説明するための情報である。((3D都市モデル))のメタデータとして、以下の四種類を作成する。それぞれ作成手順や内容を示す。

* JMP2.0形式のメタデータ（<<toc5_03_02>>）
* md形式のREADME（<<toc5_03_03>>）
* 原典資料リスト（<<toc5_03_04>>）
* 索引図（<<toc5_03_05>>）


[[toc5_03_01]]
==== メタデータの作成単位

((3D都市モデル))のメタデータは、((CityGML))形式で作成する全てのデータを一式として作成する。メタデータは、拡張製品仕様書に従った3D都市モデルと、((3D都市モデル))((オープンデータ))のそれぞれについて作成する。

メタデータ作成における留意点を以下に示す。

// (((建築物)))

[requirement]
.拡張地物のメタデータ一括作成
====
[%metadata]
identifier:: /att/deliverable/1
subject:: 標準作業手順
class:: 留意事項
statement:: 拡張製品仕様書に、地物型を追加した場合は、建築物や道路等とまとめて一式としてメタデータを作成してよい。
====

// (((3D都市モデル)))(((建築物)))

[requirement]
.3D都市モデルのメタデータ分割ルール
====
[%metadata]
identifier:: /att/deliverable/2
subject:: 標準作業手順
class:: 留意事項
[statement]
--
3D都市モデルの管理上必要な場合にはメタデータを分ける。 +
メタデータは、3D都市モデル全体について、一つのメタデータを作成することを原則とする。 +
ただし、以下の場合には3D都市モデル全体のメタデータとは別に、対象を限定したメタデータを作成する。

* 原典資料の管理者が3D都市モデルの整備主体とは異なる場合（ただし、原典資料がオープンデータである場合は除く。）
** 洪水浸水想定区域、津波浸水想定、高潮浸水想定区域、内水浸水想定区域及び土砂災害警戒区域にかかる原典資料として、<<nlftp,国土数値情報（オープンデータ）>>ではなく、河川管理者等から貸与されたデータを使用した場合は、それぞれメタデータを作成する。
** 建築物モデル（LOD4）の原典資料として、整備主体以外の施設管理者から貸与されたBIMモデル等を使用した場合は、建築物モデル（LOD4）に対するメタデータを作成する。
* モデル整備事業者が対象地物によって異なる場合
** モデル整備事業者毎に作成する。

--
====

// (((3D都市モデル)))

[requirement]
.3D都市モデル関連データのメタデータ作成ルール
====
[%metadata]
identifier:: /att/deliverable/3
subject:: 標準作業手順
class:: 留意事項
[statement]
--
3D都市モデルとは別に、関連するデータを納める場合には、それぞれにメタデータを作成する。

* 3D都市モデルとして作成した地形にドレープするための航空写真や衛星画像等の画像を成果品として納める場合には、画像用のメタデータを作成する。
* 3D都市モデルから変換したデータ（例：OBJ形式）を成果品として納める場合には、これのためのメタデータを作成する。このとき、3D都市モデルから変換したデータであることを明記すること。

--
====

[[toc5_03_02]]
==== JMP2.0形式メタデータの作成手順

((3D都市モデル))を説明するための情報として、メタデータを作成する。メタデータの仕様は、国土地理院が定めた「JMP2.0」を使用する。JMP2.0は、JPGISに準拠したメタデータ記述形式である。

メタデータの作成には、国土地理院が提供するメタデータエディタを使用する。

* 【手順】
* 手順1．メタデータエディタをインストールする。
** https://www.gsi.go.jp/gijyutukanri/gijyutukanri41027.html より入手可能
// https://psgsv.gsi.go.jp/koukyou/public/seihinsiyou/seihinsiyou_meta.html

* 手順2．メタデータエディタの詳細入力モードを使用し、各項目を入力する。
** 入力する必須項目を<<table-5-1>>に示す。
+
--
[[table-5-1]]
.作成すべきメタデータ項目
include::../../../common/sections/com_8_02_5_03_001.adoc[]
--

// this table is_common to both doc01 and doc02 slide08, slide09,
// slide10, slide11, slide12, slide13
////
[cols="11a,28a,11a"]
|===
h| メタデータ項目 h| 記述する内容 h| 記述例
| メタデータ>ファイル識別子
| ``udx\_[都市コード]_[整備年度]\_[地物型]_[オプション]``とする。

``[都市コード]``及び``[整備年度]``成果品のフォルダ名称に一致する。 +
``[地物型]``は、地物型またはモジュールを示す接頭辞（3文字又は4文字のアルファベット）とする。 +
なお、``_[地物型]``は、メタデータを地物型又はモジュールごとに作成せず、まとめて作成した場合は省略する。 +
``[オプション]``は、成果品が複数種類作成される場合に、これらを識別するために使用する任意の文字列とする。半角英数字のみを使用可とする。成果品を格納するルートフォルダに使用する``[オプション]``の文字列に一致させること。成果品が1種類の場合は省略する。
| udx_27100_city_2020_fld

| メタデータ>言語 | メタデータの記述に使用する言語。日本語とする。
| jpn　（固定値）
| メタデータ>文字集合 | メタデータに使用する文字コード。UTF-8とする。
| 004　（固定値）
| メタデータ>階層レベル | メタデータの作成対象。データ集合とする。
| 005　（固定値）
| メタデータ>問い合わせ先
| 発注者の問合せ先を記述する。役割、組織名、電話番号、オンライン情報源（Project PLATEAUのURL等）を記述する。 +
役割は「010（刊行者）」とする。
| 010（固定値） +
国土交通省都市局 +
03-5253-8397 +
https://www.mlit.go.jp/plateau/[www.mlit.go.jp/plateau/]

| メタデータ>日付 | メタデータの作成日付をYYYY-MM-DDにより記述する。
| 2021-02-25
| メタデータ>規格の名称 | メタデータの仕様。
| JMP　（固定値）
| メタデータ>規格の版 | メタデータの版。
| 2.0　（固定値）
| 参照系情報 | データ集合に適用される空間参照系の識別子。製品仕様書で指定された空間参照系の識別子を記述する。識別子は、JMP2.0を参照する。 +
「日本測地系2011における経緯度座標系と東京湾平均海面を基準とする標高の複合座標参照系」の場合は、JGD2011,TP/（B,L）,Hとなる。 +
「日本測地系2011における平面直角座標系と東京湾平均海面を基準とする標高の複合座標参照系」の場合は、JGD2011,TP/n（X,Y）,Hとなる。 +
ここでは、平面直角座標系の系番号であり、拡張製品仕様書に使用する系番号を明記する。
|
JGD2011,TP/（B,L）,H
| 識別情報>題名
| ``3D都市モデル\_[都市コード]_[提供者区分]\_[整備年度]_[オプション]``

``[都市コード]``、``[提供者区分]``、``[整備年度]``及び``[オプション]``は、成果品のフォルダ名称に一致する。
| 3D都市モデル_27100_city_2020

| 識別情報>日付及び日付型
| データの作成日付及び日付型を記述する。 +
作成日付はYYYY-MM-DDにより記述する。 +
日付型は以下より選択する。 +
001：作成日、002：刊行日、003：改訂日
| 2021-02-25, 003

| 識別情報 > 要約
| 3D都市モデルの概要を記載する。 +
以下の文章を入れる。 +
「3D都市モデルとは、都市空間に存在する建物や街路といったオブジェクトに名称や用途、建設年といった都市活動情報を付与することで、都市空間そのものを再現する3D都市空間情報プラットフォームです。様々な都市活動データが3D都市モデルに統合され、フィジカル空間とサイバー空間の高度な融合が実現します。これにより、都市計画立案の高度化や、都市活動のシミュレーション、分析等を行うことが可能となります。」 +
また、データ集合に含まれる地物やそのLOD、作成に使用した原典資料、作成方法を示す。また、以下に示すデータの利用上の注意事項を入れること。 +
「ただし、原典資料の位置の正しさの違いや、作成された時期の違いにより、現状を正確に反映していない場合があることにご注意ください。」 +
また、同一の地物型について、複数のモデル整備事業者がモデルを作成した場合は、ファイル名のオプションに使用する文字列の説明を記載すること。
| 複数のモデル整備事業者がモデルを作成した場合の記載例：

本データに含まれる建築物モデルのうち、オプション値にpscとあるものは令和5年度に株式会社パスコが、aacとあるものは令和5年度に朝日航洋株式会社が作成したデータを意味します。

| 識別情報 >目的 | 各都市において想定される3D都市モデルのユースケースを記述する。
| 災害リスクの３次元可視化
| 識別情報>状態 | 「完成」を示す固定値とする。
| 001　（固定値）
.2+| 識別情報>問い合わせ先
| 発注者の問合せ先を記述する。役割、組織名、電話番号、オンライン情報源（Project PLATEAUのURL等）を記述する。 +
役割は「010（刊行者）」とする。
| 010（固定値） +
国土交通省都市局 +
03-5253-8397 +
https://www.mlit.go.jp/plateau/[www.mlit.go.jp/plateau/]

| 作成者の問合せ情報を記述する。 +
役割名は「060（創作者）」とする。
| 060（固定値） +
○○株式会社 +
www.sample.co.jp

| 識別情報 > 記述的キーワード
| キーワードを、複数グループ化して記述する。

* 「type=002」として、データ製品に含まれる都市の名称を入れる。
* 「type=005」として、データ製品に含まれる地物型の名称を入れる。
* 「type=005」として、データ製品に含まれるLODのレベルを入れる。
* 「type=005」として、データ製品に想定されるユースケースを入れる。
* 「type=005」として、データ製品の作成に使用した原典資料の名称を入れる。
* 「type=005」として、データ製品に含まれる都市の名称を入れる。

| 東京23区, 002 +
建築物, 005 +
LOD1, 005 +
景観シミュレーション, 005 +
都市計画基本図, 005

| 識別情報>利用制限 | 固定値とし、「Licensed under CC BY 4.0」を記述する。
| Licensed under CC BY 4.0（固定値）
| 識別情報>空間表現型 | ベクトルを意味する固定値「001」を入力する。
| 001　（固定値）
| 識別情報>空間解像度
| 等価縮尺の分母にデータ集合に適用する地図情報レベルを入力する。 +
複数のレベルが混在する場合は、それぞれ記述する。
| 2500

| 識別情報>言語 | メタデータの記述に使用する言語。日本語とする。
| jpn　（固定値）
| 識別情報>文字集合 | メタデータに使用する文字コード。UTF-8とする。
| 004　（固定値）
| 識別情報>主題分類 | 構造物を意味する「017」を入力する。
| 017　（固定値）
| 識別情報> 範囲
|

* 作成範囲を包含する最小の矩形を、東西の経度、南北の緯度により記述する。
* 地物やLODにより整備範囲が異なる場合は、作成範囲の違いを自由記述により明記する。
* 地理記述には、都道府県及び市区町村名を記述する。

| LOD1の作成範囲は●●市全域、LOD2の作成範囲は、△△駅を中心とする半径約300m内。

| 配布情報>配布書式
| 固定値「CityGML 2.0」及び「i-UR 3.1」を +
それぞれ書式情報として入れる。
| CityGML 2.0 +
i-UR 3.1

| 配布情報>オンライン | G空間情報センターのURLを記述する。
| https://front.geospatial.jp/ （固定値）
| データ品質情報>データ品質
| 製品仕様書に示す品質要求の各項目について品質評価結果を記述する。 +
系譜(データが作成されるまでの過去の記録や履歴、原典資料の概要)には、主題属性の作成方法や図形と属性のアンマッチへの対処方法等、データ品質に記載できないが、データ製品の利用にあたり注意が必要となるデータの品質に係る事項を記述する。 +
また、公共測量成果の対象となる建築物モデル、交通モデル、橋梁モデル、トンネルモデル、その他の構造物モデル、植生モデル、地形モデル及び水部モデルについて、公共測量成果ではない都市オブジェクトが含まれている場合は、該当しない理由を記載する。
| （系譜の例）

一部の橋梁モデルは、厚みを推定で作成しているため、公共測量成果ではありません。

|===
////

* 手順3．メタデータエディタを用いてJMP2.0形式にて出力する。

** ファイル名称は、<<toc5_04_04>>に従う。

[NOTE,type=commentary]
--
<<table-5-1>>に示す項目は、3D都市モデルの利用者がメタデータにより3D都市モデルの概要を得ようとした場合に、利用者が想定したユースケースに適合したデータであるか否かを判断する重要な情報である。そのため、必須項目とする。

メタデータは、3D都市モデルを再利用する場合に、3D都市モデルの概要を把握するために必要な情報である。メタデータを充実させることでより価値の高いデータ製品となり、様々な人に使ってもらえるようになる。そのため、必須としない項目についても、可能な限り記述することが望ましい。
--

[[toc5_03_03]]
==== READMEファイルの作成手順

データ製品の概要書として、READMEを作成する。

===== READMEの仕様
(((3D都市モデル)))(((建築物)))(((標準製品仕様書)))(((都市計画決定情報)))

. 作成単位
** データ製品に対して一つのREADMEファイルを作成する。
. ファイルフォーマット
** md（マークダウン）形式とする。ファイル拡張子は、.mdとする。
. ファイル名称
** README（拡張子を含めると、README.md）
. 記載項目
** READMEに含むべき項目は<<tab-5-2>>のとおりとする。

[[tab-5-2]]
include::../../../common/sections/com_8_06_5_03_001.adoc[]

////
[cols="1a,5a,4a"]
.READMEに含める項目
|===
| 記載項目 | 記述する内容 | 記述例

| 成果品名称
| 3D都市モデルの名称。以下のとおりとする。

`3D都市モデル（Project PLATEAU）[都市名]（[整備年度]）`

``[都市名]`` 整備対象都市の名称を入れる。市区町村の場合は、市区町村名、都道府県の場合は都道府県名とする。 +
``[整備年度]``作成又は更新した年度（例：2022年度）を入れる。西暦とする。成果品のフォルダ名称に含める``[整備年度]``と一致させる。
| 3D都市モデル（Project PLATEAU）大阪市（2023年度）

| 都市名
| 都道府県及び市区町村の名称。
| 大阪市

| 作成（更新）年月日
| データ製品の作成（又は更新）年月日。YYYY-MM-DDにより記述する。
| 2024-02-18

| 3D都市モデルの概要
| 概要として、以下の文章を記述する。

「3D都市モデルとは、都市空間に存在する建物や街路といったオブジェクトに名称や用途、建設年といった都市活動情報を付与することで、都市空間そのものを再現する3D都市空間情報プラットフォームです。 +
様々な都市活動データが3D都市モデルに統合され、フィジカル空間とサイバー空間の高度な融合が実現します。これにより、都市計画立案の高度化や、都市活動のシミュレーション、分析等を行うことが可能となります。」
| 3D都市モデルとは、都市空間に存在する建物や街路といったオブジェクトに名称や用途、建設年といった都市活動情報を付与することで、都市空間そのものを再現する3D都市空間情報プラットフォームです。 +
様々な都市活動データが3D都市モデルに統合され、フィジカル空間とサイバー空間の高度な融合が実現します。これにより、都市計画立案の高度化や、都市活動のシミュレーション、分析等を行うことが可能となります。

| 都市の面積
| データ製品の対象となる市区町村の面積。単位はkm2とする。
| 225.3km2

| 3D都市モデルの整備内容
| データ製品に含まれる地物を応用スキーマごとに示す。

また、以下に示す地物は、LOD別の整備範囲及び整備規模（面積、箇所数等）を記載する。

* 建築物モデル：LOD別の棟数、整備範囲及び整備面積。
* 交通（道路）モデル：LOD別の整備範囲及び整備面積。
* 交通（徒歩道）モデル：LOD別の整備範囲及び整備面積。
* 交通（広場）モデル：LOD別の整備範囲及び整備箇所数。整備箇所数は、整備した広場の数とする。
* 交通（航路）モデル：LOD別の航路数。航路数は、整備した航路の数とする。
* 土地利用モデル：整備範囲及び整備面積。
* 都市設備モデル：LOD別の整備範囲及び整備面積。
* 植生モデル：LOD別の整備範囲及び整備面積。
* 災害リスク（浸水）モデル：洪水浸水想定区域、高潮浸水想定区域、津波浸水想定ごとの区域図の名称。
* 災害リスク（土砂災害）モデル：区域種類及び区域数。
* 都市計画決定情報：整備対象とした都市計画の種類。
* 橋梁モデル：LOD別の箇所数。
* トンネルモデル：LOD別の箇所数。
* その他の構造物モデル：LOD別の箇所数。
* 地下街モデル：LOD別の箇所数及び整備範囲。整備範囲は地下街の名称とする。
* 水部モデル：LOD別の整備面積。
* 地形モデル：LOD別の整備面積。
* 区域モデル：LOD別の区域数及び整備面積。

LODは、「LOD2.0」「LOD3.0」「LOD3.1」のように、最小の区分を示す。 +
整備範囲は、都市全域、都市計画区域、市街化区域等、整備した地域の説明とする。「○○市全域」「市街化区域」「用途地域」「○○駅周辺エリア」のように、整備範囲が分かる名称とする。 +
整備面積は、整備範囲の面積とする。単位は、km2を基本とするが、整備範囲が小さい場合はhaを使用してもよい。 +
整備範囲の記載がない場合は、整備した地物の総面積とする。 +
例えば、整備範囲が都市計画区域の場合、整備面積は都市計画区域の面積とする。

なお整備範囲内において、整備の対象とする地物や整備エリアを限定している場合に、その整備規模として施設数、整備面積、又は整備延長を記載する。

| 建築物モデル

LOD1:: 797965棟、市域全域、225.3km2
LOD2:: 20棟、新大阪駅周辺、1.19km2

交通（道路）モデル

LOD1:: 225.3km2、市域全域

交通（広場）モデル

LOD2:: 新大阪駅周辺、1か所、0.4ha

| 準拠する標準製品仕様書の版
|
拡張製品仕様書が準拠する標準製品仕様書の版を記述する。

「3D都市モデル標準製品仕様書　第4.1版」
| 3D都市モデル標準製品仕様書　第4.1版

| 地図情報レベル
|
データ製品に含まれる地物の地図情報レベル。

「地図情報レベル2500」が基本となるが、地図情報レベル500や地図情報レベル1000の地物が含まれている場合には、対象とする地物やエリアを記述する。
|
データセット全体の位置正確度 +
　地図情報レベル2500 +
上記以外の位置正確度 +
　建築物モデルLOD3: 地図情報レベル500 +
　建築物モデルLOD4: 地図情報レベル500 +
　交通（道路）モデル（LOD3）: 地図情報レベル500

| 索引図へのリンク | 成果品フォルダに含まれる索引図（PDFファイル）への相対パス。
|　
| 製品仕様書へのリンク | 成果品フォルダに含まれる製品仕様書（PDFファイル及びEXCELファイル）への相対パス。
|　
| メタデータへのリンク | 成果品フォルダに含まれるメタデータ（XMLファイル）への相対パス。
|　
| 原典資料リストへのリンク | 成果品フォルダに含まれる原典資料リスト（CSVファイル）への相対パスとする。
|　
| 利用に関する留意事項
| オープンデータの場合は、以下を記入する。

「本データセットは https://www.mlit.go.jp/plateau/site-policy/[PLATEAU Site Policy 「3．著作権について」] で定められた以下のライセンスを採用します。 +
+ 政府標準利用規約（第2.0版） +
+ https://creativecommons.org/licenses/by/4.0/legalcode.ja[クリエイティブ・コモンズ・ライセンスの表示4.0国際] +
+ ODC BY（ https://opendatacommons.org/licenses/by/1-0/ ） +
+ OdbL（ https://opendatacommons.org/licenses/odbl/ ）

利用者は、いずれかのライセンスを選択し、商用利用も含め、無償で自由にご利用いただけます。 +
原典資料の位置の正しさの違いや、作成された時期の違いにより、現状を正確に反映していない場合があることにご注意ください。」

| 本データセットは https://www.mlit.go.jp/plateau/site-policy/[PLATEAU Site Policy 「3．著作権について」] で定められた以下のライセンスを採用します。 +
+ 政府標準利用規約（第2.0版） +
+ https://creativecommons.org/licenses/by/4.0/legalcode.ja[クリエイティブ・コモンズ・ライセンスの表示4.0国際] +
+ ODC BY（ https://opendatacommons.org/licenses/by/1-0/ ） +
+ OdbL（ https://opendatacommons.org/licenses/odbl/ ）

利用者は、いずれかのライセンスを選択し、商用利用も含め、無償で自由にご利用いただけます。 +
原典資料の位置の正しさの違いや、作成された時期の違いにより、現状を正確に反映していない場合があることにご注意ください。

|===
////

===== 作成手順

* 【手順】
* 手順1．テキストエディタ―等を使用し、READMEファイルに入力する。
** 製品仕様書作成用テンプレートセットの、README.md（テンプレート）を使用する。
*** 製品仕様書作成用テンプレートは、以下のURLよりダウンロードできる +
https://www.mlit.go.jp/plateau/file/libraries/doc/template.zip[]


[[toc5_03_04]]
==== 原典資料リストの作成手順

JMP2.0は、データ製品を作成する際に使用した原典資料の諸元を詳細に記述できないことから、((標準製品仕様書))では、原典資料リストのための仕様を定めている。((3D都市モデル))を作成する際には、必ずこの原典資料リストを作成しなければならない。

===== 原典資料リストの仕様
(((3D都市モデル)))(((LOD0)))(((テクスチャ)))

. 作成単位
** データ製品に対して一つの原典資料リストを作成することを基本とする。
** ただし、行政界を跨ぐ都市オブジェクトを、隣接する市区町村の3D都市モデルから取得し、これを当該市区町村の3D都市モデルに重複して含めた場合、隣接する市区町村の3D都市モデルから取得した都市オブジェクトの原典資料リストは分けることができる。
. ファイルフォーマット
** CSV形式とする。拡張子は、「.csv」とする。
. ファイル名称
** ``udx\_[都市コード]_[整備年度]_resource``
** ``[都市コード]``は、成果品のルートフォルダの名称に含める``[都市コード]``とする。
** 隣接する市区町村の3D都市モデルから取得した都市オブジェクトの原典資料リストの名称に使用する``[都市コード]``は、隣接する市区町村の都市コードとする。
. 記載項目

// this table is_common to both doc01 and doc02 slide16

include::../../../common/sections/com_8_05_5_03_001.adoc[]

////
[cols="a,a,a"]
|===
| 原典資料リスト項目 | 記述する内容 | 記述例

| meshcode
| 標準地域メッシュのコードを記述する。地物のファイル単位として指定されている、3次メッシュ又は2次メッシュのメッシュコードとする。地下埋設物モデルの場合は、国土基本図の図郭コード（図郭の区画名）とする。

メッシュ毎（地下埋設物モデルの場合は図郭毎）に記述することを基本とする。

同一の地物・属性について、都市域全体で同一の原典資料が使用されている場合、メッシュコード又は図郭コードを省略する。

例えば、一つの洪水浸水想定区域図を都市域全体で使用している場合は、メッシュコードを省略する。

一方、LOD0の建築物の外形について、都市計画基本図を使用して作成しつつ、一部のメッシュでは航空写真から図化した場合は、同一地物・属性について複数の原典資料が使用されているため、メッシュ毎に記述する。

また、都市計画基礎調査を複数年に分けて実施しており、場所によって作成時点の異なる都市計画基礎調査の成果が使用されている場合には、同一地物・属性について複数の原典資料が使用されているため、メッシュ毎に記述する。

| 50305455

| feature
| 地物名を記述する。 +
各モジュールに複数の地物が定義されている場合は、集成する地物（例：Building）を記述することを基本とする。集成する地物に束ねられ、部品として使われる地物（例：WallSurface, Door）は記述しなくてもよいが、特に明記したい場合は、記述してもよい。

なお、Appearance（地物に貼るテクスチャ）は、貼り付ける対象となる地物（例：Building）のプロパティとして記述する。 +
地物名には接頭辞を付する。

[example]
====
Buildingの場合は、bldg
====

| bldg:Building

| featureName | “feature”で、”GenericCityObject”を記述した場合は、どのGenericCityObjectを使用したかを識別するため、name属性の値を記述する。GenericCityObject以外をfeatureに記述した場合は、空とする。
| 20
| property
|
地物の主題属性（データ型を含む）及び空間属性（幾何オブジェクトへの参照）を記述する。空間属性はLOD別とする。 +
地物の主題属性がデータ型として定義されている場合は、関連役割名とする。ただし、データ型に定義された各属性に異なる原典資料が使用されている場合は、“関連役割名.主題属性名”とする。 +
地物のテクスチャは、"property"を"app:appearance"とする。 +
属性名には、接頭辞を付す。 +
接頭辞は、応用スキーマ文書に示す地物の主題属性又は空間属性に付す接頭辞に一致させる。

[example]
====
bldg:function,bldg:lod1Solid,bldg:lod2Solid,uro:buildingDetailAttribute,uro:buildingDetailAttribute.uro:vacancy,app:appearance
====

| bldg:lod0RoofEdge

| propertyName 
| “property”で、”gen:stringAttribute”などの任意に追加した属性を記述した場合は、属性を識別するため、name属性（又はkey属性）の値を記述する。任意に追加した属性以外をpropertyに記述した場合は、空とする。
| 名称

| sourceName 
| 原典として使用した資料の名称を記述する。
| 航空写真

| authority 
| 原典資料の作成機関の名称を記述する。
| ●●県〇〇市

| date 
| 原典資料が作成、公表又は改訂された日付。
| 2021-01-01

| dateType
| “date”で記述した日付の意味。作成日の場合は001、公表日の場合は002、改訂日の場合は003、不明な場合は004とする。

作成日は原典資料の納品日とする。 +
公表日は原典資料がオープンデータとして公開された日とする。 +
改訂日は作成又は公開された原典資料が修正され、納品又は公開された日とする。
| 001

| srs 
| 原典資料がGISデータ又は図面の場合に、適用されている座標参照系の識別子を、JIS X7115メタデータ附属書2に従い記述する。GISデータではない場合は空とする。
| JGD2011/2（X,Y）

| mapLevel
| 原典資料がGISデータの場合又は図面の場合に、地図情報レベルを記述する。数値のみの記載とする。例：地図情報レベル2500の場合は”2500”とする。

一つの原典資料に複数の地図情報レベルが混在している場合は、列挙してよい。ただし、その他の項目の内容が同一である場合に限る（その他の項目の内容は異なる場合は行を分ける）。
| 2500

列挙する場合 +
2500;1000

| URL 
| 原典資料又はその詳細な情報が入手可能なウェブサイトがある場合にはURLを記述する。
| https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A27-v3_0.html

|===
////

===== 作成手順

* 【手順】
* 手順1．表管理ソフト等を使用し、原典資料リストのリストを作成する。
** 製品仕様書作成用テンプレートセットの、原典資料リストテンプレートを使用する。
*** 製品仕様書作成用テンプレートは、以下のURLよりダウンロードできる +
https://www.mlit.go.jp/plateau/file/libraries/doc/template.zip[]

* 手順2．以下に示すCSVファイルの仕様に従い、CSVファイルフォーマットで保存する。
** 記載項目の組を1レコードとし、以下に示す規則に従い出力する。
** CSVファイル仕様
+
--
include::../../../common/sections/com_8_05_5_03_002.adoc[]
--
////
[cols="a,a"]
|===
| 文字コード | UTF-8 （BOM付）

h| 改行コード | CRLF
h| 区切り文字 | カンマ（,）
h| ヘッダ行の有無 | あり
h| ヘッダ行の行数 | 1
h| ヘッダ行の内容 | 原典資料リスト項目を使用する。
h| 文字列でのダブルクォートの有無 | あり
h| null値の指定方法 | ,, （区切り文字の連続）
h| 1項目内で、複数の値を列挙する場合に使用する区切り文字 | ;（セミコロン）
h| 禁則文字 | 指定しない

|===
////

// (((建築物)))

[requirement]
.異なる原典資料の地物属性は行を分ける
====
[%metadata]
identifier:: /att/deliverable/4
subject:: 標準作業手順
class:: 留意事項
[statement]
--
同一メッシュ内の同じ地物の同じ属性に対して異なる原典資料が使用されている場合は、行を分ける。 +
あるメッシュに含まれる建築物のLOD1が、都市計画基本図のDMデータから作成した場合と、都市計画基礎調査のGISデータから作成した場合と混在していた場合、行を分ける。
--
====

[requirement]
.複数値の列挙は、他項目が同一の場合のみ
====
[%metadata]
identifier:: /att/deliverable/5
subject:: 標準作業手順
class:: 留意事項
[statement]
--
一つの項目内で複数の値を列挙する場合は、その他の項目の値が同一である場合に限る。 +
例えば、<<nlftp,国土数値情報>>のように、1つの原典資料であるが、複数の地図情報レベルが混在している場合がある。この場合は、地図情報レベルを;（セミコロン）により区切り、複数の地図情報レベルを列挙することができる。 +
ただし、一つの項目内で複数の値を列挙する場合は、その他の項目（作成日、座標参照系等）は同一でなければならない。
--
====

[[toc5_03_05]]
==== 索引図

索引図は、3D都市モデルの空間範囲を、LOD別に地図上で示す。

===== 索引図の仕様
(((3D都市モデル)))

. 索引図のタイトルは、「〇〇3D都市モデル整備範囲図」（〇〇の部分は整備範囲となる市区町村名又は都道府県名を記載）とする。
. 3D都市モデルの詳細度（LOD1～4）ごとに色を分けて表示する。 +
LOD3及びLOD4の整備範囲は、整備範囲の広さに応じて詳細図を表示する。
. 対象範囲の標準地域メッシュ（２次メッシュ、３次メッシュ）のメッシュとメッシュ番号を表示する。
. 凡例を表示する。主な項目は次の通りとする。
.. 2次メッシュ及びそのメッシュ数：記号は水色（R:5,G:110,B:255）の太線の四角を標準とする。
.. 3次メッシュ及びそのメッシュ数：記号は黒色（R:0,G:0,B:0）の中太線の四角を標準とする。
.. LOD1整備範囲（範囲の通称）及び面積km2：記号は黒色（R:0,G:0,B:0）の太線の四角を標準とする。
.. LOD2整備範囲（範囲の通称）及び面積km2：記号は赤色（R:240,G:5,B:0）の太線の四角を標準とする。
.. LOD3整備範囲（範囲の通称）及び数量（km2又はkm等）：記号は緑色（R:90,G:255,B:0）の太線の四角又は線を標準とする。
.. LOD4整備範囲（範囲の通称）及び数量（km2又はkm等）：記号は青色（R:0,G:0,B:255）の太線の四角又は線を標準とする。
+
面積及び数量は、README.mdに記載する整備面積及び棟数・箇所数に一致する。

. 背景地図は、国土地理院の地理院地図（地理院タイル）を標準とする。
. 縮尺は任意とし用紙サイズA4を基本とする。レイアウトは対象範囲の形状を考慮し縦又は横いずれも可とする。
. ファイル形式はPDFとする。

===== 作成手順

* 【手順】
* 手順1．GISやCAD等で図を作成し、画像形式にしたものをテンプレート（WORD形式）に張り付ける。
** 製品仕様書作成用テンプレートセットに含まれる、索引図テンプレートを使用することを基本とする。
*** 製品仕様書作成用テンプレートは、以下のURLよりダウンロードできる +
https://www.mlit.go.jp/plateau/file/libraries/doc/template.zip[]
** 使用するGISやCADの出力機能を用いて、索引図の仕様1から7に示す仕様に従った索引図を出力してもよい。
* 手順2．PDF形式に変換する。