[[toc6_03]]
=== 品質要求及び品質評価手順

データ製品に対する品質要求及び品質評価手順を示す。

[[toc6_03_01]]
==== 完全性

完全性とは、データ集合内の過剰なデータの存在（過剰）とデータ集合内のデータの欠落（漏れ）である。

[cols="1a,6a"]
|===
| No | C01

h| 品質要求 h| データ製品内に、gml:idが同一となるインスタンスがない。
h| 品質要素 | 完全性・過剰
h| 品質適用範囲 | データ製品内の全てのgml:idをもつインスタンス。
h| 品質評価尺度 | インスタンスに与えられたgml:idと同じgml:idをもつ他のインスタンスがデータ製品内に存在しない。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．データ製品に含まれる全てのインスタンスについて、gml:idの値が同じインスタンスの数をエラーとして数える。

|===

[cols="1a,6a"]
|===
| No | C02：参照データに含まれるデータを分割・統合・追加・削除せずに使用する場合

h| 品質要求 h| 参照データとインスタンス数が等しい。
h| 品質要素 | 完全性・過剰/漏れ
h| 品質適用範囲 | データ集合内の全ての地物型のインスタンス。
h| 品質評価尺度 | 参照データと都市モデルに含まれる各地物のインスタンス数が等しい。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．参照データに含まれるデータ数を、地物型ごとに数える。
* 手順2．都市モデルに含まれるインスタンス数を地物型ごとに数える。
* 手順3．手順1．と手順2．の結果より、地物型ごとに差を計算し、その絶対値の和をエラーの数とする。

|===

[cols="1a,6a"]
|===
| No | C03：参照データに含まれるデータを分割・統合・追加・削除し使用する場合、又は新規にデータを作成する場合

h| 品質要求 h| 参照データと比較して過剰・漏れが許容誤差の範囲内である。
h| 品質要素 | 完全性・過剰/漏れ
h| 品質適用範囲 | データ集合内の全ての地物型のインスタンス。
h| 品質評価尺度 | 参照データに存在しないのに地物インスタンスが存在する場合、あるいは参照データに存在するのに地物インスタンスが存在しない場合をエラーとする。1個以上のエラーが存在するサブメッシュをエラーサブメッシュとする。

// [stem]
// ++++
// "誤率（％）" = "エラーサブメッシュの数" / 100 xx 100
// ++++
式：誤率（%） = (エラーサブメッシュの数 / 100) x 100

h| 適合品質水準 | 全ての検査単位の誤率が10%以下なら合格、10%を超える検査単位が1つ以上あれば不合格。
h| 品質評価手法 | 抜取・目視検査を実施する。

* 手順1．抜取検査手法に従い、検査単位を抽出する。
* 手順2．検査単位の各メッシュを5×5のサブメッシュに分割する。
* 手順3．検査単位の範囲について、対象となる全ての地物インスタンスを抽出する。
* 手順4．検査単位ごとに全サブメッシュについて、参照データと手順3．を目視で比較して、どちらかと対応が取れない地物インスタンスがあった場合、そのサブメッシュをエラーとして、エラーの存在するサブメッシュ数を数える。
* 手順5．手順4．の結果より、検査単位ごとに誤率を算出する。

|===

[cols="1a,6a"]
|===
| No | C04（LODで指定された地物型の過剰）

h| 品質要求 h| 応用スキーマごとに定義された、各LODにおいて使用可能な地物型以外のインスタンスが含まれていない。
h| 品質要素 | 完全性・過剰
h| 品質適用範囲 | データ集合内の全ての地物型のインスタンス。
h| 品質評価尺度 | 応用スキーマごとに定義された、各LODにおいて使用可能な地物型以外のインスタンスが含まれている場合にエラーとする。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 応用スキーマごとに全数・自動検査を実施する。

* 手順1．データ製品に含まれる、全体となる地物型 footnoteblock:[fn_feature_types] のインスタンスがもつ空間属性のLOD（LODの詳細な区分が行われている場合には、その区分）を取得する。
* 手順2．LOD又はLODの詳細な区分 footnoteblock:[fn_lod_details] において、標準製品仕様書に示された使用可能な地物型を取得する。
* 手順3．データ製品に、手順2．で取得した地物型以外のインスタンスが存在した場合に、エラーとしてその数を数える。

|===

[[fn_feature_types]]
[NOTE]
--
全体となる地物型とは、以下をいう。 +
bldg:Building,brid:Bridge,frn:CityFurniture,luse:LandUse,tran:Road,tran:Railway,tran:Track,tran:Square,tun:Tunnel,veg:SolitaryVegetationObject,veg:PlantCover,wtr:WaterBody,dem:ReliefFeature,uro:OtherConstruction,uro:UndergroundBuilding,uro:UtilityNetworkElementを継承する都市オブジェクト,uro:Waterway,urf:Zone及びこれを継承する地物型。
--

[[fn_lod_details]]
[NOTE]
--
LOD又はLODの詳細な区分ごとに仕様可能な地物型は、標準製品仕様書の<<toc4_02>>～<<toc4_21>>に、応用スキーマごとに示す。
--


[cols="1a,6a"]
|===
| No | C05（出力すべき主題属性及び関連役割の漏れ）

h| 品質要求 h| 作成対象とする主題属性及び関連役割が、必ず要素（タグ）として出力される。
h| 品質要素 | 完全性・漏れ
h| 品質適用範囲 | データ製品に含まれる、作成対象とする主題属性及び関連役割のうち、必ず出力すべき主題属性及び関連役割のインスタンス。
h| 品質評価尺度 | 拡張製品仕様書が作成対象とする主題属性及び関連役割のうち、必ず出力すべきインスタンスの漏れ。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、各都市の拡張製品仕様書で作成対象とする主題属性及び関連役割のうち、必ず要素（タグ）として出現すべき主題属性及び関連役割が、都市オブジェクトの子要素として出現していない箇所をエラーとして数える。
+
作成対象とする主題属性及び関連役割とは、取得項目一覧のA.3.1_取得項目一覧シートにおいて、I列「作成対象」の欄に「○」が付いている全ての主題属性及び関連役割である。
+
必ず要素（タグ）として出現すべき主題属性及び関連役割とは、取得項目一覧のA.3.1_取得項目一覧シートにおいて、N列「不明な場合に不明値を出力する」の欄に「○」が付いている全ての主題属性及び関連役割である。
+
作成対象とする主題属性及び関連役割（I列に「○」）のうち、出力すべき主題属性及び関連役割（N列に「○」）は、必ず要素（タグ）として出力しなければならない。

|===

[cols="1a,6a"]
|===
| No | C06（作成対象である主題属性及び関連役割の漏れ）

h| 品質要求 h| 作成対象とする主題属性及び関連役割が、必ず要素（タグ）として1つ以上出力される。
h| 品質要素 | 完全性・漏れ
h| 品質適用範囲 | 作成対象とする主題属性及び関連役割。
h| 品質評価尺度 | 拡張製品仕様書で作成対象としている主題属性及び関連役割のインスタンスの漏れ。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、地物型ごとに各都市の拡張製品仕様書で作成対象とする主題属性及び関連役割が、都市オブジェクトの子要素として出現している箇所を数える。
* 手順2．出現している箇所が0か所（データセットにインスタンスが存在しない）となる主題属性及び関連役割の数を数える。

作成対象とする主題属性及び関連役割とは、取得項目一覧のA.3.1_取得項目一覧シートにおいて、I列「作成対象」の欄に「○」が付いている全ての主題属性及び関連役割である。

|===

[cols="1a,6a"]
|===
| No | C07（品質属性の漏れ）

h| 品質要求 h| 全ての幾何オブジェクトについて、作成に使用した原典資料の種類が入力されている。
h| 品質要素 | 完全性・漏れ
h| 品質適用範囲 | 全ての都市オブジェクト。
h| 品質評価尺度 | 幾何オブジェクトの作成に使用する原典資料の種類の漏れ。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。 +
地物型毎、かつ、拡張製品仕様書　<<tab-4-1>>に示される、作成対象となるLODごとに実施する。

* 手順1．品質属性（uro:DataQualityAttribute）のうち、あるLODの幾何オブジェクトが作成されているにもかかわらず、当該LODについての「幾何オブジェクトの作成に使用した原典資料の種類についての属性」が含まれていない場合にエラーとする。
* 手順2．全ての地物型及び作成対象とする全てのLODに対して手順1．を実施し、エラーの数を合計する。

「幾何オブジェクト作成するために使用した原典資料の種類についての属性」とは、以下である。 +
LOD0の場合：uro:geometrySrcDescLod0 +
LOD1の場合：uro:geometrySrcDescLod1 +
LOD2の場合：uro:geometrySrcDescLod2 +
LOD3の場合：uro:geometrySrcDescLod3 +
LOD4の場合：uro:geometrySrcDescLod4

|===

[cols="1a,6a"]
|===
| No | C08（公共測量品質属性の漏れ）

h| 品質要求 h| 公共測量成果又は基本測量成果となる全ての幾何オブジェクトについて、作成に使用した公共測量成果又は基本測量成果の種類が入力されている。
h| 品質要素 | 完全性・漏れ
h| 品質適用範囲 | 全ての都市オブジェクト。
h| 品質評価尺度 | 幾何オブジェクトの作成に使用する公共測量成果又は基本測量成果の種類の漏れ。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。 +
地物型毎、かつ、拡張製品仕様書　<<tab-4-1>>に示される、作成対象となるLODごとに実施する。

* 手順1．データセットに含まれる都市オブジェクトの品質属性（uro:DataQualityAttribute）について、各LODで「幾何オブジェクト作成するために使用した原典資料の種類についての属性」の値が「公共測量成果又は基本測量成果（コード「000」）」のみである属性の有無及びそのLODを特定する。
* 手順2．手順1．で「公共測量成果又は基本測量成果（コード「000」）」のみとなる属性がある場合は、uro:DataQualityAttributeの子要素としてuro:PublicSurveyDataQualityAttributeが出現し、かつ、そのLODにおける「公共測量成果又は基本測量成果の地図情報レベルについての属性」及び「公共測量成果又は基本測量成果の種類についての属性」が入力されていない場合に、エラーとする。
* 手順3．全ての地物型及び作成対象とする全てのLODに対して手順1．及び手順2．を実施し、エラーの数を合計する。

「幾何オブジェクト作成するために使用した原典資料の種類についての属性」とは、以下である。 +
LOD0の場合：uro:geometrySrcDescLod0 +
LOD1の場合：uro:geometrySrcDescLod1 +
LOD2の場合：uro:geometrySrcDescLod2 +
LOD3の場合：uro:geometrySrcDescLod3 +
LOD4の場合：uro:geometrySrcDescLod4 +

「公共測量成果又は基本測量成果の地図情報レベルについての属性」とは、以下である。 +
LOD0の場合：uro:srcScaleLod0 +
LOD1の場合：uro:srcScaleLod1 +
LOD2の場合：uro:srcScaleLod2 +
LOD3の場合：uro:srcScaleLod3 +
LOD4の場合：uro:srcScaleLod4 +

「公共測量成果又は基本測量成果の種類についての属性」とは、以下である。 +
LOD0の場合：uro:publicSurveySrcDescLod0 +
LOD1の場合：uro:publicSurveySrcDescLod1 +
LOD2の場合：uro:publicSurveySrcDescLod2 +
LOD3の場合：uro:publicSurveySrcDescLod3 +
LOD4の場合：uro:publicSurveySrcDescLod4

|===

[cols="1a,6a"]
|===
| No | C-bldg-01

h| 品質要素 | 完全性・過剰
h| 品質適用範囲 | bldg:Building
h| 品質評価尺度 | データ製品内に、属性「uro:buildingID」が同一となるインスタンスがない。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．データ製品に含まれる全ての建築物インスタンスについて、属性「uro:buildingID」の値が同一となるインスタンスを抽出する。
* 手順2．同一の属性「uro:buildingID」の値をもつインスタンス群について、属性「uro:branchID」又は「uro:partID」をもたないインスタンスが複数存在した場合に、エラーとしてその数を数える。

|===

[cols="1a,6a"]
|===
| No | C-bldg-02 （建築物と部屋の完全性）

h| 品質要求 h| 参照データとインスタンス数が等しい。
h| 品質要素 | 完全性・過剰/漏れ
h| 品質適用範囲 | LOD4の幾何オブジェクトをもつbldg:Building,bldg:Room
h| 品質評価尺度 | 参照データに含まれるIfcBuilding及びIfcSpaceのインスタンス数と、建築物モデル（LOD4）に含まれるbldg:Building及びbldg:Roomのインスタンス数が等しい。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．参照データに含まれる、IfcBuilding及びIfcSpaceのインスタンス数を数える。
* 手順2．建築物モデル（LOD4）に含まれるbldg:Building及びbldg:Roomのインスタンス数を数える。
* 手順3．手順1．と手順2．の結果より、IfcBuildingとbldg:Building、IfcSpaceとbldg:Room、それぞれのインスタンス数の差分を求め、その絶対値の和をエラーの数とする。

|===

[cols="1a,6a"]
|===
| No | C-bldg-03（LOD4における開口部の完全性）

h| 品質要求 h| 参照データとの一致。
h| 品質要素 | 完全性・過剰
h| 品質適用範囲 | bldg:Door,bldg:Window
h| 品質評価尺度 | 建築物モデル（LOD4）に含まれるbldg:Window及びbldg:Doorと、参照データに含まれる開口部（窓、ドア）のインスタンス数が等しい。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 抜取・目視検査を実施する。

* 手順1．建築物モデル（LOD4）に含まれる、bldg:Door及びbldg:Windowの全インスタンスの2%となるまで抽出する。
* 手順2．参照データを表示し、抽出したbldg:Door及びbldg:Windowに対応する開口部（窓、ドア）のインスタンスが存在するか、目視で確認する。
* 手順3．対応するインスタンスが存在しない場合にエラーとする。

|===

[cols="1a,6a"]
|===
| No | C-bldg-04（LOD4.1及びLOD4.2における付属物の過剰）

h| 品質要求 h| 参照データとの一致。
h| 品質要素 | 完全性・過剰
h| 品質適用範囲 | bldg:IntBuildingInstallation
h| 品質評価尺度 | 参照データに含まれる内部付属物と建築物モデル（LOD4）に含まれるbldg:IntBuildingInstallationのインスタンス数が等しい。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 抜取・目視検査を実施する。

* 手順1．建築物モデル（LOD4）に含まれるbldg:IntBuildingInstallationの全インスタンスの2%の数となるまでbldg:IntBuildingInstallationを抽出する。
* 手順2．参照データを表示し、抽出したbldg:IntBuildingInstallationに対応する内部付属物が存在し、その種類が一致するかを目視で確認する。
* 手順3．対応する内部付属物が存在しない場合、又は存在していても種類が不一致となる場合にエラーとする。

|===

NOTE: 内部付属物について +
IntBuildingInstallationとすべき内部付属物は、「（別冊）3D都市モデルとの連携のための情報伝達マニュアル（IDM）・モデルビュー定義（MVD）第3.0版　IFCクラスとPLATEAU標準建築物モデル（LOD4）の対応表」により、確認できる。

// footnoteblock:[int_inst_types]
////
[[int_inst_types]]
[NOTE]
--
IntBuildingInstallationとすべき内部付属物は、「（別冊）3D都市モデルとの連携のための情報伝達マニュアル（IDM）・モデルビュー定義（MVD）第3.0版　IFCクラスとPLATEAU標準建築物モデル（LOD4）の対応表」により、確認できる。
--
////

[[toc6_03_02]]
==== 論理一貫性

論理一貫性とは、データの構造、属性及び関係に関する論理的規則の遵守の度合いであり、以下の四つから構成される。

* 概念一貫性：応用スキーマに一致しているか否か
* 定義域一貫性：定義域に含まれているか否か
* 書式一貫性：XMLのフォーマットに従っているか否か
* 位相一貫性：応用スキーマに定義した位相的な特性が正しいか否か

[cols="1a,6a"]
|===
| No | L01

h| 品質要素 h| 論理一貫性・書式一貫性
h| 品質適用範囲 | データ製品に含まれる全ての都市モデル（core:CityModel）のインスタンス。
h| 品質評価尺度 | 整形式(Well-Formed XML)になっていない箇所数。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラム（XMLパーサなど）によって、都市モデルの書式が、XML文書の構文として正しくない箇所を数える。

|===

[cols="1a,6a"]
|===
| No | L02

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | データ製品に含まれる全ての都市モデル（core:CityModel）のインスタンス。
h| 品質評価尺度 | 妥当（Valid）なXML文書になっていない箇所数。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラム（XMLパーサなど）によって、都市モデルに含まれる地物型の構造が、7.1に符号化仕様として示すi-UR及びCityGMLのXMLSchemaが規定する構造と合致しない箇所を数える。

|===

[cols="1a,6a"]
|===
| No | L03

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | データ製品に含まれる全ての都市モデル（core:CityModel）のインスタンス。
h| 品質評価尺度 | 応用スキーマに定義していない地物型の出現箇所数。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、各都市の拡張製品仕様書の4章に示す応用スキーマ（応用スキーマクラス図及び応用スキーマ文書）に定義されている地物以外の地物インスタンスが、都市モデルの子要素として出現する箇所を数える。

|===

[cols="1a,6a"]
|===
| No | L04

h| 品質要素 h| 論理一貫性・定義域一貫性
h| 品質適用範囲 | gml:CodeTypeを型としてもつ地物属性のうち、コードリストを参照している地物属性。
h| 品質評価尺度 | 指定されたコードリストに定義されていない値となっている箇所数。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．gml:CodeTypeに含まれるコードリストへの相対パスを取得する。
* 手順2．相対パスで指定されたコードリストに定義された全てのコード値（gml:nameにより記述）を取得する。
* 手順3．検査プログラムにより、地物属性の値と取得した全てのコード値との比較を行い、地物属性の値が、コード値と合致しない箇所を数える。

|===

NOTE: コードリストへの相対パスは、gml:CodeTypeの属性であるcodeSpaceの値として記述されている。


[cols="1a,6a"]
|===
| No | L05

h| 品質要素 h| 論理一貫性・定義域一貫性
h| 品質適用範囲 | 全ての都市モデル（core:CityModel）のインスタンス。
h| 品質評価尺度 | 都市モデルに指定された空間参照系の識別子が、製品仕様書で指定された識別子ではない。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．都市モデルに含まれるgml:Envelopeに記述された空間参照系のURIが、製品仕様書に示されたURIに合致しない箇所を数える。

|===

NOTE: 空間参照系のURIは、gml:Envelopeの属性であるsrsNameの値として記述されている。


[cols="1a,6a"]
|===
| No | L06

h| 品質要素 h| 論理一貫性・定義域一貫性
h| 品質適用範囲 | 全ての幾何オブジェクトのインスタンス。
h| 品質評価尺度 | 幾何オブジェクトインスタンスの座標値に含まれる、緯度、経度、標高が、この幾何オブジェクトインスタンスを含む都市モデル（core:CityModel）の空間範囲に含まれる。
h| 適合品質水準 | エラーとなる幾何オブジェクトが0個の場合に合格。エラーとなる幾何オブジェクトが1個以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．都市モデルに含まれるgml:Envelopeの属性boundedByに記述された、緯度、経度及び標高の下限値及び上限値を超える座標値を有する幾何オブジェクトをエラーとする。

|===

[cols="1a,6a"]
|===
| No | L07

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | BIMモデルから変換したbldg:Building及びbldg:Buildingが含む、下位の地物インスタンスが持つgml:LineString及びgml:LinearRingのインスタンスを除く、全てのgml:LineString及びgml:LinearRingのインスタンス。
h| 品質評価尺度 | 同一座標又は頂点間での距離が近接閾値（0.01m）未満の頂点が連続する、又はgml:LineString及びgml:LinearRingのインスタンスを構成する点が2点未満のインスタンスをエラーとする。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L08

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 全てのgml:LineStringのインスタンス。
h| 品質評価尺度 | 単一インスタンスに始終点以外の「自己交差」又は「自己接触」が存在する場合にエラーとする。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L09

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 全てのgml:LinearRingのインスタンス。
h| 品質評価尺度 | 全てのgml:Ringのインスタンスの始終点の座標が一致していない、「自己交差」、「自己接触」、又は始終点以外に重複する座標値が存在するインスタンスをエラーとする。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L10

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 全てのgml:Polygon及びgml:_SurfacePatchの下位クラスのインスタンス。
h| 品質評価尺度 | 座標列の向きが不正なインスタンスをエラーとする。外周は反時計回り、内周は時計回りが正しい。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L11

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | LOD1の地物の空間属性に使用されるgml:Polygonのインスタンス。
h| 品質評価尺度 | gml:Polygonの境界を構成する全ての座標値が同一平面上になければならない。同一平面上にない座標値が存在するインスタンスをエラーとする。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L12

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | LOD2又はLOD3の空間属性に使用されるgml:Polygonのインスタンス。
h| 品質評価尺度 | gml:Polygonの境界を構成する全ての座標値が同一平面とみなす許容誤差（0.03m）内に存在しなければならない。同一平面とみなす許容誤差内に存在しない座標値が存在するインスタンスをエラーとする。 +
同一平面とみなす許容誤差は、作成に使用する原典資料や作成方法により異なるため、作業者が許容誤差案を作成し、監督員の確認を得てから品質評価を実施すること。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L13

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 内周が存在するgml:Polygonのインスタンス。
h| 品質評価尺度 | gml:Polygonに内周が存在する場合に、以下に示す条件に一つ以上に合致する場合にエラーとする。

* 内周が外周と交差している。
* 内周と外周が接することにより、gml:Polygonが二つ以上に分割されている。
* 内周同士が重なったり、包含関係にあったりする。

h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L14

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 全てのgml:Solidのインスタンス。
h| 品質評価尺度 | gml:Solidを構成する全ての境界面が、以下の条件を満たしていない場合にエラーとする。

* 境界面が自己交差していない。
* 閉じている。
* 全ての境界面の向きが立体の外側を向いている。
* 境界面が立体を分断していてはならない。
* 境界面が交差してはならない。

h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L15

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 全てのgml:Triangleのインスタンス。
h| 品質評価尺度 | 始点と終点が一致する4点の座標値から構成されていない場合に、エラーとする。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L16

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 全てのgml:TriangulatedSurface及びこの下位クラスのインスタンス。
h| 品質評価尺度 | gml:TriangulatedSurfaceの境界が閉じている場合にエラーとする。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L17

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 全てのgml:CompositeCurveのインスタンス。
h| 品質評価尺度 | gml:CompositeCurveを構成する（最初のgml:LineStringを除いた）gml:LineStringの始点が、直前のgml:LineStringの終点の座標と一致していない場合にエラーとする。
h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L18

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | 全てのgml:CompositeSurfaceのインスタンス。
h| 品質評価尺度 | gml:CompositeSurfaceを構成するgml:Polygonが、以下の場合にエラーとする。

* 同じgml:CompositeSurfaceを構成する他のgml:Polygonと重なる。
* 同じgml:CompositeSurfaceを構成する他のgml:Polygonのいずれとも接していない。

h| 適合品質水準 | エラーの数が0個の場合に合格。1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となる幾何オブジェクトインスタンスごとに、エラーの数を数える。

|===

[cols="1a,6a"]
|===
| No | L-bldg-01

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | bldg:Buildingのインスタンス。
h| 品質評価尺度 | bldg:Buildingが空間属性として保持する立体（gml:Solid）同士が重ならない。
h| 適合品質水準 | エラーとなるインスタンスが0個の場合に合格。エラーとなるbldg:Buildingが1個以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．全てのインスタンスについて、bldg:lod1Solid及びbldg:lod2Solidにより構成されるgml:Solidを抽出する。
* 手順2．抽出したgml:Solidのうち、重なるべきではないgml:Solid同士が交差している場合にエラーとする。

|===

[cols="1a,6a"]
|===
| No | L-bldg-02

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | bldg:BuildingPartをもつbldg:Buildingのインスタンス。
h| 品質評価尺度 | 1つのbldg:Buildingについて、これを構成するbldg:BuildingPartが空間属性として保持する立体（gml:Solid）同士が離れていない。
h| 適合品質水準 | エラーとなるインスタンスが0個の場合に合格。エラーとなるbldg:Buildingインスタンスが1個以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．bldg:BuildingPartをもつbldg:Buildingインスタンスを抽出する。
* 手順2．それぞれのインスタンスについて、これを構成する全てのgml:Solidを抽出し、境界面を共有していないgml:Solidが存在している場合にエラーとする。

|===

[cols="1a,6a"]
|===
| No | L-bldg-03

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | bldg:Window及びbldg:Doorのインスタンス。
h| 品質評価尺度 | bldg:_Openingの下位クラスのインスタンスが、これを集約するbldg:_BoundarySurfaceの下位クラスのインスタンスに包含されていない場合にエラーとする。
h| 適合品質水準 | エラーとなるbldg:Window、bldg:Doorのインスタンスが0個の場合に合格。エラーとなるインスタンスが1個以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．開口部（bldg:Window、bldg:Door）の空間属性として保持するgml:MultiSurfaceを、これを集約する境界面（bldg:_BoundarySurfaceの下位クラス）の空間属性が保持するgml:MultiSurface上に投影する。
* 手順2．投影されたbldg:Window及びbldg:Doorのgml:MultiSurfaceの一部又は全部が境界面の外側に存在するbldg:Window及びbldg:Doorのインスタンス数を数える。

|===

[cols="1a,6a"]
|===
| No | L-bldg-04

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | bldg:Building
h| 品質評価尺度 | bldg:Buildingの用途を示す属性が正しい階層構造を保っている。
h| 適合品質水準 | エラー数が0なら合格、1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．データ製品に含まれる全てのbldg:Buildingインスタンスについて、属性「uro:majorUsage2」をもつインスタンスを抽出する。
* 手順2．属性「uro:majorUsage」をもたない場合にエラーとし、その数を数える。

|===

[cols="1a,6a"]
|===
| No | L-bldg-05

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | bldg:Building
h| 品質評価尺度 | bldg:Buildingの用途を示す属性が正しい階層構造を保っている。
h| 適合品質水準 | エラー数が0なら合格、1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．データ製品に含まれる全ての建築物インスタンスについて、属性「uro:detailedUsage2」又は「uro:detailedUsage3」をもつインスタンスを抽出する。
* 手順2．属性「uro:detailedUsage2」をもつインスタンスは属性「uro:detailedUsage」を、属性「uro:detailedUsage3」をもつインスタンスは属性「uro:detailedUsage2」を、それぞれもたない場合にエラーとし、その数を数える。

|===

[cols="1a,6a"]
|===
| No | L-bldg-06

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | bldg:Building,bldg:BuildingPart
h| 品質評価尺度 | bldg:Building又はbldg:BuildingPartのbldg:lod2Solid及びbldg:lod3Solidにより記述される立体（gml:Solid）の境界面（gml:CompositeSurface）に含まれる多角形（gml:Polygon）は、bldg:boundedByにより参照する、bldg:RoofSurface,bldg:WallSurface,bldg:GroundSurface,bldg:OuterFloorSurface,bldg:OuterCeilingSurface,bldg:ClosureSurface及びこれらが参照する開口部（bldg:Door,bldg:Window）により記述される面（gml:MultiSurface）に含まれる多角形（gml:Polygon）のいずれかでなければならない。
h| 適合品質水準 | エラー数が0なら合格、1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、bldg:lod2Solid又はbldg:lod3Solidにより記述される立体（gml:Solid）の境界面（gml:CompositeSurface）が参照する多角形（gml:Polygon）のgml:idが、bldg:boundedByにより参照するbldg:RoofSurface,bldg:WallSurface,bldg:GroundSurface,bldg:OuterFloorSurface,bldg:OuterCeilingSurface,bldg:ClosureSurface及びこれらが参照する開口部（bldg:Door,bldg:Window）の面（gml:MultiSurface）の構成要素となる多角形（gml:Polygon）のgml:idと一致していない場合にエラーとする。

|===

[cols="1a,6a"]
|===
| No | L-bldg-07（境界面と開口部との位相）

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | bldg:_BoundarySurfaceの下位型及びbldg:_Openingの下位型のインスタンス。
h| 品質評価尺度 | bldg:_Openingの下位クラスのインスタンスの空間属性（bldg:lod4MultiSurface）が、これを集約するbldg:_BoundarySurfaceの下位クラスのインスタンスの空間属性（bldg:lod4MultiSurface）と境界線を共有していない場合にエラーとする。
h| 適合品質水準 | エラーとなるbldg:Window、bldg:Doorのインスタンスが0個の場合に合格。エラーとなるインスタンスが1個以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．開口部（bldg:Window、bldg:Door）の空間属性が保持するgml:MultiSurfaceを、これを集約する境界面（bldg:_BoundarySurfaceの下位クラス）の空間属性が保持するgml:MultiSurfaceを抽出する。
* 手順2．bldg:Window及びbldg:Doorのgml:MultiSurfaceが境界面のgml:MultiSurfaceと境界線を共有していないbldg:Window及びbldg:Doorのインスタンス数を数える。

|===

[cols="1a,6a"]
|===
| No | L-bldg-08（bldg:BuildingのLOD4が境界面に区分されていること）

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | bldg:Building
h| 品質評価尺度 | bldg:Buildingのbldg:lod4Solid又はbldg:lod4MultiSurfaceを構成するgml:Polygonが、bldg:Buildingに含まれるbldg:_BoundarySurfaceの下位型、bldg:_Openingの下位型、又はbldg:BuildingInstallationのgml:Polygonのいずれかでなければならない。
h| 適合品質水準 | エラー数が0なら合格、1以上なら不合格。
h| 品質評価手法 | 全数検査を実施する。

* 手順1．検査プログラムによって、bldg:lod4Solidにより記述される立体（gml:Solid）の境界面（gml:CompositeSurface）が参照する多角形（gml:Polygon）又はbldg:lod4MultiSurfaceにより記述される面の集まり（gml:MultiSurface）に含まれる多角形（gml:Polygon）のgml:idが、以下のいずれかに一致していない場合にエラーとする。
** bldg:boundedByにより参照するbldg:RoofSurface,bldg:WallSurface,bldg:GroundSurface,bldg:OuterFloorSurface,bldg:OuterCeilingSurface,bldg:ClosureSurface及びこれらが参照する開口部（bldg:Door,bldg:Window）の面（gml:MultiSurface）の構成要素となる多角形（gml:Polygon）のgml:id
** bldg:outerBuildingInstallationにより参照するbldg:BuildingInstallationの境界面となるbldg:RoofSurface,bldg:WallSurface,bldg:GroundSurface,bldg:OuterFloorSurface,bldg:OuterCeilingSurface,bldg:ClosureSurface及びこれらが参照する開口部（bldg:Door,bldg:Window）の面（gml:MultiSurface）の構成要素となる多角形（gml:Polygon）のgml:id

|===

[cols="1a,6a"]
|===
| No | L-bldg-09（bldg:RoomのLOD4が境界面に区分されていること）

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | bldg:Room
h| 品質評価尺度 | bldg:Roomのbldg:lod4Solidを構成するgml:Polygonが、bldg:Roomに含まれるbldg:_BoundarySurfaceの下位型又はbldg:_Openingの下位型のgml:Polygonのいずれかでなければならない。
h| 適合品質水準 | エラー数が0なら合格、1以上なら不合格。
h| 品質評価手法 | 全数検査を実施する。

* 手順1．検査プログラムによって、bldg:lod4Solidにより記述される立体（gml:Solid）の境界面（gml:CompositeSurface）が参照する多角形（gml:Polygon）のgml:idが、以下のいずれかに一致していない場合にエラーとする。
** bldg:boundedByにより参照するbldg:CeilingSurface,bldg:InteriorWallSurface,bldg:FloorSurface,bldg:ClosureSurface及びこれらが参照する開口部（bldg:Door,bldg:Window）の面（gml:MultiSurface）の構成要素となる多角形（gml:Polygon）のgml:id

|===

[cols="1a,6a"]
|===
| No | L-bldg-10（屋内・屋外の境界面の向き）

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | bldg:_BoundarySurfaceの下位型。
h| 品質評価尺度 | 建築物（bldg:Building）の外形を構成する境界面は常に法線ベクトルが外向きであり、部屋（bldg:Building）を構成する境界面は、常に法線ベクトルが内向きである。
h| 適合品質水準 | エラー数が0なら合格、1以上なら不合格。
h| 品質評価手法 | 全数検査を実施する。

* 手順1．検査プログラムによって、以下のエラーをカウントする。
** bldg:Buildingのbldg:boundedByにより保持されるbldg:_BoundarySurfaceの法線ベクトルの向きが、建築物の内側を向いている場合
** bldg:BuildingInstallationのbldg:boundedByにより保持されるbldg:_BoundarySurfaceの法線ベクトルの向きが、建築物の内側を向いている場合
** bldg:Roomのbldg:boundedByにより保持されるbldg:_BoundarySurfaceの法線ベクトルの向きが、建築物の外側を向いている場合
** bldg:IntBuildingInstallationのbldg:boundedByにより保持されるbldg:_BoundarySurfaceの法線ベクトルの向きが、建築物の外側を向いている場合

|===

[cols="1a,6a"]
|===
| No | L-bldg-11（部屋を構成する幾何オブジェクトと、境界面との関係）

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | bldg:Room
h| 品質評価尺度 | bldg:Roomのbldg:lod4Solidにより記述される立体又はbldg:lod4MultiSurfaceにより記述される面の集まりであるgml:Polygonが、bldg:Roomが参照する境界面又はbldg:IntBuildingInstallationの境界面となgml:Polgonがの反対の向きとなる。
h| 適合品質水準 | エラー数が0なら合格、1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、bldg:Roomのbldg:lod4Solidにより記述される立体（gml:Solid）の境界面（gml:CompositeSurface）の構成要素（gml:surfaceMember）又はbldg:lod4MultiSurfaceにより記述される面の集まり（gml:MultiSurface）の構成要素（gml:surfaceMember）が、以下のいずれかに一致していない場合にエラーとする。
** gml:surfaceMemberにより参照される面がorientationの値が”-“となるgml:OrientableSurfaceではない。
** gml:OrientableSurfaceが、gml:baseSurfaceにより参照するgml:idが、以下のいずれにも該当しない。
*** bldg:boundedByにより参照するbldg:InteriorWallSurface,bldg:FloorSurface,bldg:CeilingSurface,bldg:ClosureSurface及びこれらが参照する開口部（bldg:Door,bldg:Window）の面（gml:MultiSurface）の構成要素となる多角形（gml:Polygon）のgml:id
*** bldg:roomInstallationにより参照する、bldg:IntBuildingInstallationがbldg:boundedByにより参照する、bldg:InteriorWallSurface,bldg:CeilingSurface,bldg:FloorSurface,bldg:ClosureSurface及びこれらが参照する開口部（bldg:Door,bldg:Window）により記述される面（gml:MultiSurface）に含まれる多角形（gml:Polygon）のgml:id

|===

[cols="1a,6a"]
|===
| No | L-bldg-12（建築物と屋内に存在する地物との相対的な位置関係）

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | bldg:Building、bldg:Room、bldg:IntBuildingInstallation、bldg:BuildingFurniture
h| 品質評価尺度 | 全てのbldg:Room、bldg:IntBuildingInstallation、bldg:BuildingFurnitureの幾何オブジェクト（gml:Solid又はgml:MultiSurface）が、これを含むbldg:Buildingの幾何オブジェクト（gml:Solid又はgml:MultiSurface）の内側に含まれていなければならない。
h| 適合品質水準 | エラー数が0なら合格、1以上なら不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、全てのbldg:Room、bldg:IntBuildingInstallation、bldg:BuildingFurnitureのLOD4の幾何オブジェクトに含まれるgml:Polygonが、bldg:Buildingの幾何オブジェクトと交差しているgml:Polygonの数をカウントする。
* 手順2．検査プログラムによって、全てのbldg:Room、bldg:IntBuildingInstallation、bldg:BuildingFurnitureのLOD4の幾何オブジェクトに含まれるgml:Polygonの外側（負となる向き）に、bldg:Buildingの幾何オブジェクトが存在していないgml:Polygonの数をカウントする。
* 手順3．手順1．及び手順2．の合計をエラー数とする。

|===

[cols="1a,6a"]
|===
| No | L-frn-01

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | 空間属性として、lod1Geometry,lod2Geomatry又はlod3Geometryをもつ全ての地物型のインスタンス。
h| 品質評価尺度 | 空間属性により保持又は参照する幾何オブジェクトの型が、応用スキーマ文書で指定された幾何オブジェクト（gml:MultiSurface又はgml:Solid）ではないインスタンスの個数。
h| 適合品質水準 | エラーの箇所が0個の場合に合格。エラーの箇所数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となるインスタンスを検索する。
* 手順2．検索されたインスタンスの空間属性の型が、応用スキーマ文書と合致しないインスタンスを数える。

|===

[cols="1a,6a"]
|===
| No | L-frn-02

h| 品質要素 h| 論理一貫性・概念一貫性
h| 品質適用範囲 | 空間属性として、lod0Geometryをもつ全ての地物型のインスタンス。
h| 品質評価尺度 | 空間属性により保持又は参照する幾何オブジェクトの型が、応用スキーマ文書で指定された幾何オブジェクト（gml:Point, gml:MultiPoint, gml:MultiCurve又はgml:MultiSurface）ではないインスタンスの個数。
h| 適合品質水準 | エラーの箇所が0個の場合に合格。エラーの箇所数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、対象となるインスタンスを検索する。
* 手順2．検索されたインスタンスの空間属性の型が、応用スキーマ文書と合致しないインスタンスを数える。

|===

[cols="1a,6a"]
|===
| No | L-tran-01

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | tran:Road、tran:TrafficArea、tran:AuxiliaryTrafficArea
h| 品質評価尺度 | 延長方向に連続するインスタンスの空間属性（tran:lod2MultiSurface及びtran:lod3MultiSurface）が、境界線を共有していない場合をエラーとする。
h| 適合品質水準 | エラーとなるインスタンスが0個の場合に合格。エラーとなるインスタンスが1個以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。 +
同一の地物型かつ同一のLODで記述されている空間属性に対して実施する。

* 手順1．道路の延長方向に連続する全ての同一の地物型かつ同一のLODの空間属性をもつペアを抽出する。
* 手順2．全てのインスタンスのペアについて、“境界線で接する”、”離れている”のいずれにも該当しないオブジェクトのペアの数を数える。

|===

[cols="1a,6a"]
|===
| No | L-tran-02

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | tran:TrafficArea、tran:AuxiliaryTrafficArea
h| 品質評価尺度 | 同一の道路インスタンスに含まれる交通領域及び交通補助領域の空間属性（tran:lod2MultiSurface及びtran:lod3MultiSurface）は、境界線を共有するか、又は、離れているかのいずれかであり、それ以外の場合にエラーとする。 +
ただし、以下は例外とする。

* 中央帯と分離帯（分離帯は中央帯に含まれる場合がある。）
* 中央帯と側帯（側帯は中央帯に含まれる場合がある。）
* 路肩と側帯（側帯は路肩に含まれる場合がある。）

h| 適合品質水準 | エラーとなるインスタンスが0個の場合に合格。エラーとなるインスタンスが1個以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。 +
同一のLODで記述されている空間属性に対して実施する。

* 手順1．対象となる地物の全インスタンスのペアを抽出する。
* 手順2．全てのインスタンスのペアについて、“境界線で接する”に該当しないインスタンスの数を数える。

|===

[cols="1a,6a"]
|===
| No | L-tran-03

h| 品質要素 h| 論理一貫性・位相一貫性
h| 品質適用範囲 | tran:Road、tran:TrafficArea、tran:AuxiliaryTrafficArea
h| 品質評価尺度 | tran:Roadインスタンスに含まれるtran:TrafficAreaインスタンス及びtran:AuxiliaryTrafficAreaインスタンスの空間属性（tran:lod2MultiSurface及びtran:lod3MultiSurface）に含まれる全てのMultiSurfaceを道路インスタンスが参照していない場合にエラーとする。
h| 適合品質水準 | エラーとなるインスタンスが0個の場合に合格。エラーとなるインスタンスが1個以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．対象となる地物の全インスタンス数を数える。
* 手順2．全てのインスタンスのペアについて、“境界線で接する”に該当しないインスタンスの数を数える。

|===

[[toc6_03_03]]
==== 位置正確度

位置正確度とは、空間参照系内の地物の位置の正確さのことである。標準製品仕様書では、位置正確度として、報告された座標値と採択された値又は真とみなす値との近さを示す絶対正確度（外部正確度とも呼ぶ）を採用する。

標準製品仕様では、データ製品が満たすべき位置正確度として、地図情報レベル2500を適用することを基本とする。

ユースケースに応じて、位置正確度の適合品質水準は変更してもよい。ただし、変更に当たっては作業規程の準則に定義される地図情報レベルに従い決定すること。また、このレベルは地物型ごとに替えてよい。

点群や画像からの図化により取得したインスタンスは、P01とP02、P05とP06、又はP07とP08から、その地図情報レベルに応じて、品質要求及び評価手順を適用する。

また、GISデータからの変換により取得したインスタンスの場合はP03、既成図数値化により取得したインスタンスはP04を適用する。

なお、地形については、P-dem-01を適用する。

● 地図情報レベル2500の場合の位置正確度

[cols="1a,6a"]
|===
| No | P01

h| 品質要素 h| 位置正確度・絶対正確度
h| 品質適用範囲 | 点群や画像からの図化により取得した、データ集合内の全ての地物型のインスタンス。
h| 品質評価尺度 | データ集合内の位置の座標と、より正確度の高い参照データである点検測量成果の座標との誤差の標準偏差を計算する。また、誤差の母平均は0とする。 +
ただし、データ品質属性の「幾何属性作成方法」の値が「0（推定）」となるインスタンスは検査対象としない。
h| 適合品質水準 | 全ての検査単位について、水平位置の標準偏差が、水平距離1.75m以内であれば合格、1.75mを超えれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに明瞭な地物から21辺以上（2点以上／辺）を抽出する。
* 手順4．抽出した地物の点について、データ集合上の位置座標を測定する。
* 手順5．抽出した地物の点に対応する現地（又は現地とみなす資料）の点検測量成果を取得する。
* 手順6．手順4．及び手順5．より、誤差の標準偏差を計算する。

|===

[cols="1a,6a"]
|===
| No | P02

h| 品質要素 h| 位置正確度・外部正確度
h| 品質適用範囲 | 点群や画像からの図化により取得した、データ集合内の全ての地物型のインスタンス。

ただし、地形（dem:ReliefFeature）は除く。
h| 品質評価尺度 | データ集合内の位置の座標と、より正確度の高い参照データである水準測量成果の座標との誤差の標準偏差を計算する。また、誤差の母平均は0とする。 +
ただし、データ品質属性の「幾何属性作成方法」の値が「0（推定）」となるインスタンスは検査対象としない。
h| 適合品質水準 | 全ての検査単位別に、標高の標準偏差が0.66m以内であれば合格、0.66mを超えれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに明瞭な地物から21辺以上（2点以上／辺）を抽出する。
* 手順4．抽出した地物の点について、データ集合上の位置座標（標高）を測定する。
* 手順5．抽出した地物の点に対応する現地（又は現地とみなす資料）の水準測量成果を取得する。
* 手順6．手順4．及び手順5．より、誤差の標準偏差を計算する。

|===

● 地図情報レベル500又は地図情報レベル1000の場合の位置正確度

地図情報レベルを変更する場合は、P1及びP2に示す適合品質水準を下表に従い変更する。図化以外（GISデータの変換及び既成図数値化）の場合には、P3又はP4を使用する。

[cols="a,a,a"]
.新規測量における数値地形図データの位置精度及び地図情報レベル（作業規程の準則第106条）
|===
| 地図情報レベル | 水平位置の標準偏差 | 標高の標準偏差

| 500 | 0.25m以内 | 0.25m以内
| 1000 | 0.70m以内 | 0.33m 以内

|===

● 地図情報レベル500の場合の位置正確度

[cols="1a,6a"]
|===
| No | P05

h| 品質要素 h| 位置正確度・絶対正確度
h| 品質適用範囲 | 点群や画像からの図化により取得した、データ集合内の全ての地物型のインスタンス。
h| 品質評価尺度 | データ集合内の位置の座標と、より正確度の高い参照データである点検測量成果の座標との誤差の標準偏差を計算する。また、誤差の母平均は0とする。 +
ただし、データ品質属性の「幾何属性作成方法」の値が「0（推定）」となるインスタンスは検査対象としない。
h| 適合品質水準 | 全ての検査単位について、水平位置の標準偏差が、水平距離0.25m以内であれば合格、0.25mを超えれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに明瞭な地物から21辺以上（2点以上／辺）を抽出する。
* 手順4．抽出した地物の点について、データ集合上の位置座標を測定する。
* 手順5．抽出した地物の点に対応する現地（又は現地とみなす資料）の点検測量成果を取得する。
* 手順6．手順4．及び手順5．より、誤差の標準偏差を計算する。

|===

[cols="1a,6a"]
|===
| No | P06

h| 品質要素 h| 位置正確度・外部正確度
h| 品質適用範囲 | 点群や画像からの図化により取得した、データ集合内の全ての地物型のインスタンス。 +
ただし、地形（dem:ReliefFeature）は除く。
h| 品質評価尺度 | データ集合内の位置の座標と、より正確度の高い参照データである水準測量成果の座標との誤差の標準偏差を計算する。また、誤差の母平均は0とする。 +
ただし、データ品質属性の「幾何属性作成方法」の値が「0（推定）」となるインスタンスは検査対象としない。
h| 適合品質水準 | 全ての検査単位別に、標高の標準偏差が0.25m以内であれば合格、0.25mを超えれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに明瞭な地物から21辺以上（2点以上／辺）を抽出する。
* 手順4．抽出した地物の点について、データ集合上の位置座標（標高）を測定する。
* 手順5．抽出した地物の点に対応する現地（又は現地とみなす資料）の水準測量成果を取得する。
* 手順6．手順4．及び手順5．より、誤差の標準偏差を計算する。

|===

● 地図情報レベル1000の場合の位置正確度

[cols="1a,6a"]
|===
| No | P07

h| 品質要素 h| 位置正確度・絶対正確度
h| 品質適用範囲 | 点群や画像からの図化により取得した、データ集合内の全ての地物型のインスタンス。
h| 品質評価尺度 | データ集合内の位置の座標と、より正確度の高い参照データである点検測量成果の座標との誤差の標準偏差を計算する。また、誤差の母平均は0とする。 +
ただし、データ品質属性の「幾何属性作成方法」の値が「0（推定）」となるインスタンスは検査対象としない。
h| 適合品質水準 | 全ての検査単位について、水平位置の標準偏差が、水平距離0.7m以内であれば合格、0.7mを超えれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに明瞭な地物から21辺以上（2点以上／辺）を抽出する。
* 手順4．抽出した地物の点について、データ集合上の位置座標を測定する。
* 手順5．抽出した地物の点に対応する現地（又は現地とみなす資料）の点検測量成果を取得する。
* 手順6．手順4．及び手順5．より、誤差の標準偏差を計算する。

|===

[cols="1a,6a"]
|===
| No | P08

h| 品質要素 h| 位置正確度・外部正確度
h| 品質適用範囲 | 点群や画像からの図化により取得した、データ集合内の全ての地物型のインスタンス。 +
ただし、地形（dem:ReliefFeature）は除く。
h| 品質評価尺度 | データ集合内の位置の座標と、より正確度の高い参照データである水準測量成果の座標との誤差の標準偏差を計算する。また、誤差の母平均は0とする。 +
ただし、データ品質属性の「幾何属性作成方法」の値が「0（推定）」となるインスタンスは検査対象としない。
h| 適合品質水準 | 全ての検査単位別に、標高の標準偏差が0.33m以内であれば合格、0.33mを超えれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに明瞭な地物から21辺以上（2点以上／辺）を抽出する。
* 手順4．抽出した地物の点について、データ集合上の位置座標（標高）を測定する。
* 手順5．抽出した地物の点に対応する現地（又は現地とみなす資料）の水準測量成果を取得する。
* 手順6．手順4．及び手順5．より、誤差の標準偏差を計算する。

|===

GISデータからの変換を行う場合及び既成図数値化を行う場合：適合品質水準は地図情報レベル2500の場合と同様とする。ただし、原典資料は変更した地図情報レベルの要件を満たさなければならない。

● GISデータの変換の場合

[cols="1a,6a"]
|===
| No | P03

h| 品質要素 h| 位置正確度・外部正確度
h| 品質適用範囲 | GISデータからの変換により取得した、データ集合内の全ての地物型のインスタンス。  +
ただし、地形（dem:ReliefFeature）は除く。
h| 品質評価尺度 | 「データ集合内の座標」と「原典資料の座標」との誤差の標準偏差を計算する。 +
ただし、原典資料は地図情報レベル2500の要件を満たしているものとする。また、誤差の母平均は0とする。
h| 適合品質水準 | 全ての検査単位別に、標準偏差が0mであれば合格、0mを超えれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに他の地物との関係から位置が明確な点を10点以上抽出する。
* 手順4．抽出した点について、データ集合上のインスタンスの座標値を取得する。
* 手順5．原典資料を用いて、手順4．で抽出した地物の点の座標値を取得する。
* 手順6．手順4．及び手順5．より、検査単位毎に誤差の標準偏差を計算する。

|===

● 既成図数値化の場合

[cols="1a,6a"]
|===
| No | P04

h| 品質要素 h| 位置正確度・外部正確度
h| 品質適用範囲 | 既成図数値化により取得した、データ集合内の全ての地物型のインスタンス。
h| 品質評価尺度 | 「データ集合内の水平位置の座標」と「データ取得時に使用した原典資料を用いて図化したデータ集合内の水平位置の座標」との誤差の標準偏差を計算する。 +
ただし、原典資料は地図情報レベル2500の要件を満たしているものとする。また、誤差の母平均は0とする。
h| 適合品質水準 | 全ての検査単位について、図上の水平位置の標準偏差が0.3mm以内であれば合格、0.3mmを超えれば不合格。
h| 品質評価手法 | 既成図の図郭四隅の残存誤差を計測し、図郭四隅の残存誤差が0.2mm以内であれば、以降の手順に従い、地物の空間属性が保持する幾何オブジェクトの誤差の標準偏差を計測する。 +
抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに明瞭な地物から21辺以上（2点以上／辺）を抽出する。
* 手順4．抽出した地物の点について、データ集合上の位置座標を測定する。
* 手順5．抽出した地物の点に対応する既成図上の座標を測定する。
* 手順6．手順4．及び手順5．より、検査単位毎に誤差の標準偏差を計算する。

|===

● 地形の位置正確度

[cols="1a,6a"]
|===
| No | P-dem-01

h| 品質要素 h| 位置正確度・外部正確度
h| 品質適用範囲 | dem:ReliefFeature
h| 品質評価尺度 | データ集合内の位置の座標と、より正確度の高い参照データである水準測量成果の座標との誤差の標準偏差を計算する。また、誤差の母平均は0とする。 +
ただし、データ品質属性の「幾何属性作成方法」の値が「0（推定）」となるインスタンスは検査対象としない。
h| 適合品質水準 | 全ての検査単位別に、標高の標準偏差が0.7m以内であれば合格、0.7mを超えれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い検査単位を抽出する。
* 手順2．検査単位に含まれるデータ（地物インスタンス）を表示又は出力する。
* 手順3．検査単位ごとに明瞭な地物から21 辺以上（2点以上／辺）を抽出する。
* 手順4．抽出した地物の点について、データ集合上の位置座標（標高）を測定する。
* 手順5．抽出した地物の点に対応する現地（又は現地とみなす資料）の水準測量成果を取得する。
* 手順6．手順4．及び手順5．より、誤差の標準偏差を計算する。

|===


[[toc6_03_04]]
==== 時間正確度

CityGMLでは、時間オブジェクトを定義する時間スキーマ（ISO 19108）を使用していないことから、 標準製品仕様書でも時間スキーマは使用していない。そのため、時間正確度は本標準仕様書では対象外とする。

なお、年や日付の値が設定された地物属性は主題正確度による品質要求を行い、参照データとの比較による品質評価手法を示す。

[[toc6_03_05]]
==== 主題正確度

主題正確度は、定量的属性の正確度、非定量的属性、地物分類及び地物間関係の正しさである。なお、定量的属性とは、長さや大きさなど、値が大小関係のある数値となる属性である。また、非定量的属性とは文字列やコードのような値の大小関係がない属性である。

[cols="1a,6a"]
|===
| No | T01

h| 品質要素 h| 主題正確度・非定量的主題属性の正しさ
h| 品質適用範囲 | 非定量的主題属性をもつ全ての地物型のインスタンス。
h| 品質評価尺度 | インスタンスに設定された地物属性のうち、型がxs:string、gml:CodeType、xs:boolean、xs:date、xs:gYear、gml:MeasureOrNullListType又は、gml:StringOrRefTypeとなる主題属性について、設定された値が参照データの属性値と一致しないインスタンスをエラーインスタンスとする。
h| 適合品質水準 | エラーの箇所が0個の場合に合格。エラーの箇所数が1以上の場合は不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い、検査単位を抽出する。
* 手順2．検査単位の各メッシュを5×5のサブメッシュに分割する。
* 手順3．検査単位の範囲について、属性値が識別できるようにインスタンスを表示又は出力する。
* 手順4．検査単位ごとに全サブメッシュについて、参照データと手順3．を比較し、サブメッシュに含まれる全てのインスタンスの値が妥当であるかを確認する。

|===

[cols="1a,6a"]
|===
| No | T02

h| 品質要素 h| 主題正確度・定量的主題属性の正しさ
h| 品質適用範囲 | 定量的主題属性をもつ全ての地物型のインスタンス。
h| 品質評価尺度 | インスタンスに設定された地物属性のうち、型がxs:integer、xs:nonNegativeInteger、 xs:double、gml:MeasureType、gml:LengthType又はgml:MeasureOrNullListTypeとなる主題属性について、設定された値が参照データの属性値と一致しないインスタンスをエラーとする。
h| 適合品質水準 | エラーの箇所が0個の場合に合格。エラーの箇所数が1以上の場合は不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い、検査単位を抽出する。
* 手順2．検査単位の各メッシュを5×5のサブメッシュに分割する。
* 手順3．検査単位の範囲について、属性値が識別できるようにインスタンスを表示又は出力する。
* 手順4．検査単位ごとに全サブメッシュについて、参照データと手順3．を比較し、サブメッシュに含まれる全てのインスタンスの値が妥当であるかを確認する。

|===

[cols="1a,6a"]
|===
| No | T03

h| 品質要素 h| 主題正確度・分類の正しさ
h| 品質適用範囲 | 地物関連（幾何オブジェクトへの参照を含む）のうち、gml:idの参照により実装されている全てのインスタンス。
h| 品質評価尺度 | 地物関連により参照されるgml:idをもつインスタンスの型が、応用スキーマの中で指定された関連相手先の型と一致しない箇所の出現回数。
h| 適合品質水準 | エラーの箇所が0個の場合に合格。エラーの箇所数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、xlink:href属性により参照されたgml:idをもつインスタンスを検索する。
* 手順2．検索されたインスタンスの型が、応用スキーマで定義された関連相手先となる地物型又は幾何オブジェクト型と合致しないインスタンスを数える。

|===

[cols="1a,6a"]
|===
| No | T-bldg-01

h| 品質要素 h| 主題正確度・分類の正しさ
h| 品質適用範囲 | 以下の地物型のインスタンス：bldg:RoofSurface,bldg:WallSurface,bldg:GroundSurface,bldg:OuterFloorSurface,bldg:OuterCeilingSurface,bldg:ClosureSurface
h| 品質評価尺度 | 建築物及び建築物部分を構成する境界面が、正しく区分されていないインスタンスをエラーとする。エラーが1つ以上存在するサブメッシュをエラーサブメッシュとする。

// [stem]
// ++++
// "誤率（％）" = "エラーサブメッシュの数" / "検査単位毎の全サブメッシュ数" xx 100
// ++++
式：誤解率（%） = (エラーサブメッシュの数 / 検査単位毎の全サブメッシュ数) x 100

h| 適合品質水準 | 全ての検査単位の誤率が10%以下なら合格、10%を超える検査単位が1つ以上あれば不合格。
h| 品質評価手法 | 抜取検査を実施する。

* 手順1．抜取検査手法に従い、検査単位を抽出する。
* 手順2．検査単位の各メッシュを5×5のサブメッシュに分割する。
* 手順3．検査単位の範囲について、建築物及び建築物部分を構成する境界面を識別できるようにインスタンスを表示又は出力する。
* 手順4．検査単位ごとに全サブメッシュについて、参照データと手順3．を比較し、サブメッシュに含まれる全てのインスタンスの境界面が妥当であるかを確認する。
* 手順5．確認の結果、妥当ではないインスタンスが一つでも存在するサブメッシュをエラーとして、エラーの存在するサブメッシュ数を数える。
* 手順6．手順5．の結果より、検査単位ごとに誤率を算出する。

|===

[cols="1a,6a"]
|===
| No | T-bldg-02

h| 品質要素 h| 主題正確度・分類の正しさ
h| 品質適用範囲 | 全てのbldg:BuildingInstallationのインスタンス。
h| 品質評価尺度 | bldg:lod2Geometry又はbldg:lod3Geometryにより保持又は参照する幾何オブジェクトの型が、gml:MultiSurface又はgml:Solidではないインスタンスの個数。
h| 適合品質水準 | エラーの箇所が0個の場合に合格。エラーの箇所数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

* 手順1．検査プログラムによって、建築物の屋外付属物のインスタンスのうち、bldg:lod2Geometryにより保持又は参照する幾何オブジェクトの型が、gml:MultiSurface又はgml:Solidと合致しないインスタンスを数える。

|===

