[[toc6_02]]
=== 品質評価手順に関する共通事項

標準製品仕様では、品質評価手法を以下の2種類に大別する。

* 全数・自動検査

* 抜取・目視検査

このうち、抜取検査を実施する場合、標準製品仕様書では、抜取方法と合否判定を「<<gsi_map_level_dps,地図情報レベル2500数値地形図データ作成のための標準製品仕様書（案）>>」を参考に、以下のとおり設定する。

. 検査ロット
+
3D都市モデル整備対象となる全域

. 検査量
+
総面積の2%

. 検査単位の抽出方法
+
--
「4分の1地域メッシュ（分割地域メッシュ）」を検査単位とする。 +
「4分の1地域メッシュ」とは、基準地域メッシュ（第3次地域区画）を経線方向緯線方向に四分割したメッシュである。

[.source]
<<stat_regional_mesh>>

検査量2%のうち、1%は監督員による任意抽出とし、残りの1%は無作為抽出により抽出する。無作為抽出の結果、監督員が既に抽出した検査単位、検査の対象が含まれない検査単位、市町村境界の外側や海などの白部が含まれる地区が抽出された場合には、隣接する検査単位を選択する。白部が含まれない検査単位を抽出することが困難な場合には、出来る限り白部の比率が小さい検査単位を選択する。最小検査単位数は16とする。同一の成果に対しては、異なる品質評価項目に対しても原則として同一の検査単位を使用する。
--

. アイテム（品質評価の対象）の定義
+
個別に規定する。

. 抜取率（母集団からサンプルを抽出する割合）
+
検査単位内の全数を対象とする。
+
各検査単位を10×10サブメッシュ（品質評価手順によっては2×2）に分割し、サブメッシュ毎に全数を点検する。

. 検査方法
+
個別に規定する。

. 合否判定
+
--
次式により検査単位ごとに誤率を求める。

// [stem]
// ++++
// "誤率（%）" = "エラーが一つでも含まれるサブメッシュ数" / "検査単位ごとの全サブメッシュ数" xx 100
// ++++
式：誤率（%） = (エラーが一つでも含まれるサブメッシュ数 / 検査単位ごとの全サブメッシュ数) x 100

検査単位ごとの全サブメッシュ数は100に等しく、検査単位の一部に白部が含まれる場合にも100として誤率を計算する。 +
一つ以上の検査単位で誤率が適合品質水準を超えたら「不合格」とする。不合格となった場合、全般について再点検を行う。再点検が終了したら、3%の面積に相当する検査単位の抽出を行うものとし、その結果不適合が認められた場合には、さらに4%の追加実施を行うか、再作業を行う。
--

