[[toc0_01]]
[abstract]
== はじめに

* 本書は、各地方公共団体等が3D都市モデルを整備する際に、その製品仕様を容易に作成でき、かつ、整備された3D都市モデルを国際標準に適合したものとすることを目的として提供する標準文書である。

* 「3D都市モデル」は、都市空間をデータによって再現したもの、すなわち、現実の都市空間から必要な情報を取捨選択し、データとして記述したものである。あらゆるデータがそうであるように、3D都市モデルも何らかのソリューション（ユースケース）を創出するために整備されるものであるから、そのデータ内容や範囲等はユースケースに依存する。しかし、ユースケースごとに異なる仕様の3D都市モデルを整備することはデータ作成の観点から非効率であり、多用途への展開を考慮する場合は流通性や再利用性を阻害する懸念がある。

* 3D都市モデルの流通性・再利用性を高め、様々な分野・用途での利用に資するデータとするためには、「標準」に適合することが重要である。本書は、地理空間データに関する標準化団体であるOpen Geospatial Consortium（OGC）が策定した3D都市モデルのためのオープンデータモデル及びデータ形式の国際標準である「CityGML」と、このCityGMLの拡張規則であるApplication Domain Extension（ADE）に基づき内閣府地方創生推進事務局が都市再生に必要なデータを拡張した「i-都市再生技術仕様（案）」（i-UR）を我が国における3D都市モデルの標準仕様として採用し、「標準製品仕様」として示すものである。

* 標準製品仕様は、CityGML及びi-URに準拠して作成され、Project PLATEAUの2020年度、2021年度、2022年度及び2023年度の成果を踏まえ、様々な地物やその属性の定義、また、品質要求及び評価手順を示している。さらに、必要な地物等に過不足があった場合に、国際標準に準拠しつつ3D都市モデルをカスタマイズするための規則を示している。そのため、3D都市モデルを整備する場合には、本書を参照することで、国際標準に準拠した3D都市モデルの製品仕様（以下、「拡張製品仕様」と呼ぶ）を作成できる。

* 今後、3D都市モデルの整備主体が、本書を参照し、ユースケースに応じた拡張製品仕様を作成することで、国際標準に適合した3D都市モデルが整備され、様々な分野での利用が促進されることを期待する。

