[[toc4_26]]
=== データ集合の応用スキーマ

データ集合は地物の集まりである。

[[toc4_26_01]]
==== データ集合のLOD

データ集合は地物の集まりであり、それ自身の空間属性をもたないため、LODは定義しない。

[[toc4_26_02]]
==== データ集合の応用スキーマクラス図

[[toc4_26_02_01]]
===== Core（CityGML）

Coreパッケージには、CityGMLが定義する地物型の最上位概念であるcore:_CityObjectと、データ集合であるcore:CityModelが定義されている。CityGMLで定義される全ての地物型、また、CityGMLを拡張するi-URで定義される全ての地物型は、core:_CityObjectを継承する。

image::images/426.svg[]

[[toc4_26_03]]
==== データ集合の応用スキーマ文書

[[toc4_26_03_01]]
===== Core（CityGML）

====== core:CityModel

[cols="1a,1a,2a"]
|===
| クラスの定義
2+| 3次元都市モデルのための地物集合。 +
全ての都市オブジェクト及びその幾何形状等はこの地物型の中に含める。

h| 上位の型 2+| gml:_FeatureCollection
h| ステレオタイプ 2+| << FeatureType >>
3+h| 継承する属性
h| 属性名 h| 属性の型及び多重度 h| 定義
| gml:description | gml:StringOrRefType [0..1] | 3D都市モデルの概要。
| gml:name | gml:CodeType [0..1] | 3D都市モデルを識別する名前。文字列とする。
| gml:boundedBy
| gml:Envelope [0..1]
| 3D都市モデルが含まれる空間範囲、3D都市モデルに適用される空間参照系及び3D都市モデルの次元数を記述する。 +
必須とする。

3+h| 自身に定義された関連役割
h| 関連役割名 h| 関連役割の型及び多重度 h| 定義
| core:cityObjectMember
| core:_CityObject [0..*]
| 都市モデルに含まれる都市オブジェクト。 +
core:CityModelがcore:cityObjectMemberにより直接含む都市オブジェクトは、各応用スキーマにおいて、全体となる都市オブジェクトのみである。 +
それ以外の都市オブジェクトは、全体となる都市オブジェクトの部品として出現する。 +
全体となる都市オブジェクトとは、以下である。 +
bldg:Building +
brid:Bridge +
frn:CityFurniture +
grp:CityObjectGroup +
luse:LandUse +
tran:Road +
tran:Railway +
tran:Track +
tran:Square +
tun:Tunnel +
veg:SolitaryVegetationObject +
veg:PlantCover +
wtr:WaterBody +
dem:ReliefFeature +
uro:OtherConstruction +
uro:UndergroundBuilding +
uro:UtilityNetworkElementを継承する都市オブジェクト +
uro:Waterway +
urf:Zone及びこれを継承する都市オブジェクト

|===

[[toc4_26_04]]
==== データ集合で使用するコードリストと列挙型

[[toc4_26_04_01]]
===== Core（CityGML）

なし

