[[toc4_04]]
=== データ出力と品質評価

[[toc4_04_01]]
==== データ出力

前項までで作成した((3D都市モデル))を、製品仕様に示された符号化仕様に従うデータに変換する。

(((i-UR)))(((CityGML)))(((3D都市モデル)))(((標準製品仕様書)))

* 【手順】
* 手順1．指定されたファイル単位に分割する。 +
標準製品仕様書で地物型ごとに指定されたファイル単位（<<toc5_04_02>>）に従い、分割する。分割は、メッシュコードに紐づく空間範囲ごとに実施する。ただし、空間範囲の境界線上に存在する地物は区切らず、それぞれのメッシュに平面投影した形状が含まれる面積の割合を算出し、この割合が最も大きいメッシュに対応するファイルに含む。m2で面積を計算し、小数点2桁（3桁目で四捨五入）で比較する。面積が同じ場合はメッシュ番号の小さい方とする。
* 手順2．分割したファイル単位にデータを変換・出力する。 +
符号化仕様に定義されたタグ及びタグの構造（階層、出現順序、データ型、出現回数等）に従い、プログラム等により分割したデータをCityGML及びi-URによるGML形式に変換する。i-UR及びCityGMLに定義された地物型等には、それぞれi-UR及びCityGMLで推奨された接頭辞を使用する。 +
出力においては、成果品となる3D都市モデルの構造（5.4に示すファイル名やフォルダ構成）を考慮すること。 +
CityGML及びi-URの符号化仕様は以下より取得できる。

** CityGML：
*** http://schemas.opengis.net/citygml/[]
** i-UR：
*** https://www.geospatial.jp/iur/schemas/uro/3.2/urbanObject.xsd[]
*** https://www.geospatial.jp/iur/schemas/urf/3.2/urbanFunction.xsd[]
*** なお、符号化仕様は最新のものであることをversion属性により確認すること。version属性は、符号化仕様内のxs:schemaタグに記載されている（以下のフラグメントの太字部分）。
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:urf="https://www.geospatial.jp/iur/urf/3.2"
  xmlns:core="http://www.opengis.net/citygml/2.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:gml="http://www.opengis.net/gml"
  xmlns:uro="https://www.geospatial.jp/iur/uro/3.2"
  targetNamespace="https://www.geospatial.jp/iur/urf/3.2"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  version="3.1.0">
----

* 手順3．コード型に対応するコードリストをXML形式に変換・出力する。XMLの形式は、GML 3.1.1 simple dictionary profileを使用する。 +
GML 3.1.1 simple dictionary profileは、もともとは辞書として利用されることを想定したXML形式であり、名前（gml:name）とその説明（gml:description）の対の集まりから構成される。CityGMLでは、コードリストの符号化仕様としてこのGML 3.1.1 simple dictionary profileを使用していることから、標準製品仕様においてもコードリストの符号化仕様としてGML 3.1.1 simple dictionary profileを採用する。 +
GML 3.1.1 simple dictionary profileに従ったXML形式のコードリスト例を以下に示す。
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<gml:Dictionary
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:gml="http://www.opengis.net/gml"
  xsi:schemaLocation="http://www.opengis.net/gml http://schemas.opengis.net/gml/3.1.1/profiles/SimpleDictionary/1.0.0/gmlSimpleDictionaryProfile.xsd"
  gml:id="cl_f649301c-8e10-11ec-b909-0242ac120002">
  <gml:name>Building_class</gml:name>
  <gml:dictionaryEntry>
    <gml:Definition gml:id="id1">
      <gml:description>普通建物</gml:description>
      <gml:name>3001</gml:name>
    </gml:Definition>
  </gml:dictionaryEntry>
  <!-- …略… -->
  <gml:dictionaryEntry>
    <gml:Definition gml:id="id5">
      <gml:description>分類しない建物</gml:description>
      <gml:name>3000</gml:name>
    </gml:Definition>
  </gml:dictionaryEntry>
</gml:Dictionary>
----

** gml:Dictionaryのgml:idは、``[接頭辞]_[UUID]``とする。
*** ``[接頭辞]``は、clとする。``[UUID]``は、Universally Unique Identifierとする。
** gml:nameには、当該3D都市モデルにおけるコードリストを識別する名称として、地物型名と属性名との組み合わせとする。地物型名と属性名とは_（アンダースコア）でつなぐ。
** コードとその説明を、gml:Definitionにより対として記述する。gml:Definitionの子要素となるgml:descriptionには説明を、gml:nameにはコードを示す。
** 標準製品仕様書に定義されたコードリストのXMLは以下より取得できる。 +
https://www.geospatial.jp/iur/codelists[]

* 手順4．品質評価を実施する。
** 論理一貫性（L03）の品質評価は、拡張製品仕様書において作成対象とした地物及び属性に対して行うこと。

[[toc4_04_02]]
==== 作業上の留意事項

出力したデータについても、[underline]##<<tocB>>及び<<tocU>>に示す要件を満たさなければならない。##以下に、本作業で生じうるエラーに対する留意事項を示す。

[requirement]
.要素への接頭辞付与
====
[%metadata]
identifier:: /att/quality/12
subject:: 標準作業手順
class:: 留意事項
[statement]
--
全ての要素に必ず接頭辞を付ける。

* 複数の名前空間に定義された符号化仕様を使用しているため、混乱を生じないよう、全ての要素に接頭辞を付ける。

--
====

[requirement]
.`gml:id`の付与ルール
====
[%metadata]
identifier:: /att/quality/13
subject:: 標準作業手順
class:: 留意事項
[statement]
--
(((3D都市モデル)))(((CityGML)))(((i-UR)))
gml:idの付与ルールに従う。

* gml:idは、データ集合内でオブジェクトを識別するためのIDである。3D都市モデルでは、このgml:idに ``[接頭辞]_[UUID]``を使用する。
* ``[接頭辞]``は、製品仕様書に示す、CityGML及びi-URの各パッケージに与えられた接頭辞（<<tab-4-4>>）とする。また、``[UUID]``は、Universally Unique Identifierとする。

--
====

// rwp 20240816 revise as per slide file 20240802 slide02 slide03
// this table is_common to both doc01 and doc02 slide02 slide03


(((都市計画決定情報)))
[[tab-4-4]]
include::../../../common/sections/com_7_02_5_04_004.adoc[]

////
[cols="2a,2a,1a"]
.接頭辞
|===
2+^|  応用スキーマ ^|  接頭辞
2+| 建築物モデル |  bldg
2+| 交通（道路）モデル |  tran
2+| 交通（鉄道）モデル |  rwy
2+| 交通（徒歩道）モデル |  trk
2+| 交通（広場）モデル |  squr
2+| 交通（航路）モデル |  wwy
2+| 土地利用モデル |  luse
.5+| 災害リスク（浸水）モデル | 洪水浸水想定区域 |  fld
| 津波浸水想定 |  tnm
| 高潮浸水想定区域 |  htd
| 内水浸水想定区域 |  ifld
| ため池ハザードマップ |  rfld
| 災害リスク（土砂災害）モデル | 土砂災害警戒区域 |  lsld
2+| 都市計画決定情報モデル |  urf
2+| 橋梁モデル |  brid
2+| トンネルモデル |  tun
2+| その他の構造物モデル |  cons
2+| 都市設備モデル |  frn
2+| 地下街モデル |  ubld
2+| 植生モデル |  veg
2+| 地形モデル |  dem
2+| 水部モデル |  wtr
2+| 区域モデル |  area
2+| 汎用都市オブジェクト |  gen
2+| アピアランスモデル |  app
2+| 拡張製品仕様書で拡張した地物（ただし、urf:Zoneを継承する地物を除く）|  ext

|===
////

[requirement]
.XMLタグの出現順序
====
[%metadata]
identifier:: /att/quality/14
subject:: 標準作業手順
class:: 留意事項
[statement]
--
(((CityGML)))(((i-UR)))
XML文書におけるタグの出現順序は、XMLSchemaにおいて定められた順序とする。

* XMLで出現するタグは、あらかじめXMLSchemaによりその順序が決まっている。具体的には以下の順序で出現することが基本となる。これらの順序を守らない場合、論理一貫性に不適合となる。 +
1）gml:* +
2）core:* +
3）gen:* +
4）bldg:*、tran:*等CityGMLの地物型で定義された属性・関連役割 +
5）uro:*、urf:*等i-URで定義された属性・関連役割
** UMLクラス図で記述された属性や関連役割がXML文書のタグとして出現する。UMLクラス図で記述された属性と関連役割には順序の概念がない。一方、XMLSchemaでは順序をもつ。そのため、UMLクラス図の記述だけでは、XMLSchemaでの出現順序が分からない。データ出力時には、XMLSchemaにおいて出現順序を確認し、定められた順序となるよう注意すること。
**	ただし、ポイントクラウドモデルはcore:_CityObjectに拡張を行っているため、ポイントクラウドと関連付けた都市オブジェクトのインスタンスに関してはcore:_CityObjectを継承する各都市オブジェクトに定義された属性（例：bldg:class）などよりも前にuro:pointCloudのタグが出現する。また、植生モデルは、uro:を接頭辞とする属性及び関連役割が、CityGMLで定義された接頭辞veg:よりも前に出現してよい。接頭辞veg:よりも前に出現してよいタグは、veg:SolitaryVegetationObject及びveg:PlantCoverの上位の地物型である、veg:_VegetationObjectに拡張された属性及び関連役割（uro:vegDataQualityAttribute、uro:vegFacilityIdAttribute、uro:vegFacilityTypeAttribute、uro:vegFacilityAttribute、uro:vegKeyValuePairAttribute及びuro:vegDmAttribute）である。

--
====

[requirement]
.主題属性には「不明」値も含めて出力
====
[%metadata]
identifier:: /att/quality/15
subject:: 標準作業手順
class:: 留意事項
[statement]
--
(((CityGML)))(((i-UR)))(((建築物)))
作成対象となる主題属性は、「不明」値も含めて出力する。

* 一つの応用スキーマの単位で作成対象とする主題属性を決定した場合は、原典資料に基づき「不明」の値も含めて全ての都市オブジェクトに必ずタグを作成する。
** 「不明」値は、基本となるデータ型ごとに指定された不明を表す値（留意事項30参照）を使用すること。
* CityGML及びi-URで定義された属性の多くは多重度が``[0..1]``であり、省略可能である。しかし、作成対象であるデータについてタグを省略すると、データがないのか、不明なのか、又はエラーで漏れているのかがわからなくなるため、不明であることを明示する必要がある。
** 例えば、「都市計画基礎調査（建物利用現況）」を原典資料として「建築物モデル」の主題属性「bldg:usage」を作成することとした場合、原典資料によって、「不明」の場合に不明値のコードが入力されている場合と、値が空となっている場合（調査対象ではあるが値を入れていない場合）が混在する。後者のような場合には、作業機関の作業によって、「不明」の範囲を特定し、主題属性「bldg:usage」には不明を表すコード値（461）を出力する。
** 補足：「洪水浸水想定区域図」を原典資料として、「建築物モデル」の主題属性「uro:BuildingRiverFloodingRiskAttribute」を作成することとするような場合、原典資料の範囲外の値は存在しない。このような場合は、「不明」ではなく「不存在」なので、値を出力する必要はない。

--
====

[requirement]
.作成対象外のタグは作成しない
====
[%metadata]
identifier:: /att/quality/16
subject:: 標準作業手順
class:: 留意事項
[statement]
--
(((i-UR)))(((CityGML)))
作成対象ではない地物型等のタグは作成しない（空タグを作成しない）。

* i-UR やCityGMLには様々な地物型や属性が定義されている。作成対象としない地物型及び属性は、空タグ（値を入れないタグ）を作成しない。

--
====

[requirement]
.単位付き数値には必ずuom属性を指定
=====
[%metadata]
identifier:: /att/quality/17
subject:: 標準作業手順
class:: 留意事項
[statement]
--
単位付き数値型の属性には、かならずuom属性により、単位を指定する。

* 単位付き数値とは、50.0m, 50haのように、数値に単位を付する属性の型である。原典資料では単位が省略されている場合があるが、符号化仕様において単位付き数値で記述することが指定されている場合には、単位を付与する。

[example]
.記述例
====
(((標準製品仕様書)))
[source,xml]
----
<uro:buildingFootprintArea uom="m2">189.78</uro:buildingFootprintArea>
----
====

* 標準製品仕様書では原則として、長さの単位は“メートル”、面積の単位は“平方メートル”又は“ヘクタール”、時間の単位は“時間”を採用している。uom属性にはそれぞれ"m"、"m2"、"ha"、"hour"を記述する。

--
=====

// (((3D都市モデル)))

[requirement]
.コードリストとcodeSpaceの指定
=====
[%metadata]
identifier:: /att/quality/18
subject:: 標準作業手順
class:: 留意事項
[statement]
--
コードは、あらかじめ用意されたコードリストに列記されたコードから一つを選択し、値として記述する。このとき、用意されたコードリストの所在をcodeSpace属性に記述する。

* コードリストは3D都市モデルのファイルからの相対パスによる記述とする。

** 相対パスは、成果品のフォルダ構成に従う（<<toc5,第6章>>参照）。

[example]
.記述例：相対パスによるcodeSpaceの指定の例
====
[source,xml]
----
<bldg:usage codeSpace="../codelists/Building_usage.xml">422</bldg:usage>
----
====
--
=====

// (((汎用属性セット)))(((汎用属性)))

[requirement]
.コード型属性の汎用属性セット
=====
[%metadata]
identifier:: /att/quality/19
subject:: 標準作業手順
class:: 留意事項
[statement]
--
汎用属性セットを用いてコード型の属性を追加した場合には、コードが参照するコードリストの所在を記述する文字列型の汎用属性（name=“codeSpace”）とコードを記述する文字列型の汎用属性（name=“code”）との対として符号化する。

[example]
.記述例：都市設備（CityFurniture）に追加する場合
====
[source,xml]
----
<gen:genericAttributeSet name="避難設備区分">
  <gen:stringAttribute name="codeSpace">
    <gen:value>../../codelists/CityFurniture_generic-evacType.xml</gen:value>
  </gen:stringAttribute>
  <gen:stringAttribute name="code">
    <gen:value>11</gen:value>
  </gen:stringAttribute>
</gen:genericAttributeSet>
----
====

[example]
.記述例：汎用都市オブジェクト（GenericCityObject）に追加する場合
====
[source,xml]
----
<gen:genericAttributeSet name="避難設備区分">
  <gen:stringAttribute name="codeSpace">
    <gen:value>../../codelists/GenericCityObject_generic-20-type.xml</gen:value>
  </gen:stringAttribute>
  <gen:stringAttribute name="code">
    <gen:value>11</gen:value>
  </gen:stringAttribute>
</gen:genericAttributeSet>
----
====

* コードリストの所在の記述は、gml:CodeTypeを使用したcodeSpace属性による指定と同様とする。

--
=====

[requirement]
.データ出力時の変換エラーに注意
====
[%metadata]
identifier:: /att/quality/20
subject:: 標準作業手順
class:: 留意事項
[statement]
--
データ出力時における変換エラーに留意する。

* 幾何オブジェクトの作成や、属性の追加において正しくデータが作成されているにも関わらず、符号化する際の変換プログラムの誤りにより、エラーが生じることに留意すること。特に、以下の事項を確認する。
** 変換元となる空間参照系と、変換先となる空間参照系が正しく設定されているか。
** コード型の主題属性について、原典資料独自のコードから指定したコードに正しくマッピングされているか。また、正しいコードリストを参照しているか。
** 単位付き数値型の属性が、指定した単位に変換されているか。
** 不要なNULL値が出力されていないか。また、不要な空タグが出力されていないか。
** 座標列は、緯度、経度、標高の順列となっているか（経度、緯度、標高の順列は誤り）。
** 面を構成する座標列の向きは左回りになっているか（右回りは誤り）。

--
====

[requirement]
.i-URの符号化仕様は相対パスで指定
====
[%metadata]
identifier:: /att/quality/21
subject:: 標準作業手順
class:: 留意事項
[statement]
--
(((i-UR)))(((CityGML)))(((3D都市モデル)))
i-URの符号化仕様は相対パスによりschemaLocationを指定する。

* CityGML形式に出力したファイルのschemaLocationの指定は、3D都市モデルの成果品に含めるi-URの符号化仕様のファイルへの相対パスとする。
** 地物型又はモジュールごとに分けられた3D都市モデルの成果品を格納するフォルダ（例：bldg,tran）の直下に格納した3D都市モデルファイルの場合、schemaLocationとして記述すべき符号化仕様への相対パスは以下となる。
+
`urbanObject.xsdへの相対パス：`../../schemas/iur/uro/3.2/urbanObject.xsd
+
`urbanFunction.xsdへの相対パス：`../../schemas/iur/uro/3.2/urbanFunction.xsd

--
====

// (((3D都市モデル)))

[requirement]
.部分更新時のデータ漏れ・重複確認
====
[%metadata]
identifier:: /att/quality/22
subject:: 標準作業手順
class:: 留意事項
[statement]
--
部分更新となる場合は、統合したデータに漏れや重複が無いことを確認する。

* 既に3D都市モデルが存在しており、その一部を更新する場合は、更新した3D都市モデルと更新していない3D都市モデルとを統合し、一式とする必要がある。そのため、統合した際にデータの漏れや重複が無いことを確認する。

--
====

// (((標準製品仕様書)))

[requirement]
.変換プログラムのデフォルト値確認
====
[%metadata]
identifier:: /att/quality/23
subject:: 標準作業手順
class:: 留意事項
[statement]
--
変換プログラムのデフォルト設定に注意する。

* データ出力に使用する変換プログラムによっては、必須となる属性等にデフォルト値が用意されている場合がある。デフォルト値が標準製品仕様書の指定する値と異なる場合もあるため、設定を確認する。
** app:Appearance の属性app:themeの値を標準製品仕様書では、“rgbTexture”と指定している。データ変換ツールとして一般的に使用されている商用ツールであるFMEを使って変換する場合、この値の指定をしなければ、デフォルトで“FMETheme”と入力される。

--
====

// (((3D都市モデル)))

[requirement]
.LOD別の地物は同一ファイルに出力
====
[%metadata]
identifier:: /att/quality/24
subject:: 標準作業手順
class:: 留意事項
[statement]
--
一つの都市オブジェクトを異なるLODで記述した場合、一つの地物インスタンスとして同じファイルに出力することを基本とする。

* 3D都市モデルの各地物型には、LOD0からLOD4までの複数の空間属性が定義されている。これにより一つの都市オブジェクトを詳細度の異なる複数の幾何オブジェクトで表現することができる。このとき、同じ都市オブジェクトについてのLODが異なる複数の幾何オブジェクトは、同一の地物インスタンスに含まれる各LODの幾何オブジェクトとして同じファイルに出力することを基本とする。
* ただし、地形モデル（LOD3）の場合は、ファイル名のオプション（lod3）を用いてファイルを分けてもよい。これは、地物の単位が基準地域メッシュであることから、同一の地物インスタンスに複数のLODを格納することでデータ量が膨大となり、操作性が低下することを避けることを目的としている。

--
====

[[toc4_04_03]]
==== 実施すべき品質評価

データ出力では、主として出力されたデータが符号化仕様に適合しているか（書式一貫性、概念一貫性）の評価を行う。また、完全性として、データ作成に使用したツールの内部形式で記述されたデータが、漏れや過剰なく出力されていることを確認する。 +
データ出力において実施すべき品質評価を以下に示す。 +
品質要素ごとに分類された各番号は、((標準製品仕様書))に定義する品質要求及び評価手順の識別子である。(((位置正確度)))

* 完全性：C01,C02,C03,C05,C06
* 論理一貫性：L01,L02,L03,L05,L06,L07,L10,L15,L-bldg-06,L-bldg-07,L-bldg-08,L-bldg-09,L-bldg-10,L-bldg-11,L-frn-01,L-tran-03
* 位置正確度：―
* 主題正確度：T03,T-bldg-02

((標準製品仕様書))の品質要求に追加又は変更を行った場合には、完全性、論理一貫性及び主題正確度について、出力したデータに対して必要となる品質評価を実施する。

// (((3D都市モデル)))

[requirement]
.全ての都市オブジェクトにデータ品質属性を付与
====
[%metadata]
identifier:: /att/quality/25
subject:: 標準作業手順
class:: 留意事項
[statement]
--
3D都市モデルに含まれる全ての都市オブジェクトに、データ品質属性（uro:DataQualityAttribute）を作成する。

* 作成対象とするLODごとに、幾何オブジェクトの作成に使用した原典資料の種類を記述すること。
* アピアランスを作成した場合には、対象とするLODごとに使用した原典資料の種類を記述すること。
* 主題属性を作成した場合は、使用した原典資料の種類を記述すること。
* 複数種類の原典資料を使用した場合には、それぞれ記述すること。
* 作成対象とするLODを作成しなかった都市オブジェクトについても、「未作成（コード：999）」であることを示さなければならない。

--
====

[requirement]
.公共測量成果を用いた場合の品質属性作成
====
[%metadata]
identifier:: /att/quality/26
subject:: 標準作業手順
class:: 留意事項
[statement]
--
公共測量成果又は基本測量成果を使用する場合は、公共測量品質属性（uro:PublicSurveyDataQualityAttribute）を必ず作成する。

* 公共測量成果又は基本測量成果のみを使用して幾何オブジェクトを作成した場合は、公共測量品質属性（uro:PublicSurveyDataQualityAttribute）を用いて、使用した公共測量成果又は基本測量成果の種類をLODごとに記述すること。
* ただし、公共測量成果又は基本測量成果とそれ以外の資料を組み合わせによる作成や推定による補完は、公共測量成果とはならないため、公共測量品質属性（uro:PublicSurveyDataQualityAttribute）を作成しない。
* 作成した幾何オブジェクトが公共測量成果となる場合にのみ作成する。

--
====

