[[toc4_03]]
=== 属性追加と品質評価

[[toc4_03_01]]
==== 属性の追加

地物型に定義された主題属性及び時間属性を、幾何オブジェクトの属性として追加する。追加すべき主題属性及び時間属性は、第1章において決定した各都市の製品仕様に従う。

* 【手順】
* 手順1．原典資料に含まれる、作成した幾何オブジェクトに対応する値を特定する。
* 手順2．幾何オブジェクトの属性として特定した値を記述する。
* 手順3．品質評価を実施する。

[[toc4_03_02]]
==== 作業上の留意事項

((建築物))等の都市オブジェクトの作成においては、[underline]##<<tocC>>から<<tocU>>に示す妥当な都市オブジェクトの要件を満たす##こと。 +
以下に、本作業で生じうるエラーに対する留意事項を示す。

// (((拡張製品仕様書)))

[requirement]
.データ型の整合性
====
[%metadata]
identifier:: /att/quality/4
subject:: 標準作業手順
class:: 留意事項
[statement]
--
製品仕様では、データの値の型が厳密に定義されている。そのため、原典資料により得られた情報と型が一致しない場合には、定義された型に合わせて修正する。

* 日付の記述には、JIS X0301により定義された、拡張形式による暦日付の完全表記（YYYY-MM-DD）を使用する。
+
正しい記述例： +
2020-04-01
+
誤った記述例： +
令和2年4月1日（西暦で記載しなければならない） +
2020-04（年、月、日の組み合わせでなければならない） +
2020/04/01（年と月、月と日はハイフンでつながなければならない） +
不明（不明な場合は、0001-01-01を入れる） +
令和2年4月（年月のみ分かる場合は、YYYY-MM-01とするため、2020-04-01とする）

* コード型の属性におけるコードの記述は、コードリストに示されたコードと一致させる。
+
原典資料では、文字列として入力されていることが多いため、半角・全角の区分が混在している場合や、定義されたコード以外が入力されている場合がある。あらかじめ原典資料に含まれるコードを抽出し、作成したコードリストと照合させ、必要に応じてコードの変換又はコードリストへの反映を行う。

* 単位付き数値型の属性の値を記述する際は、原典資料の単位と拡張製品仕様書において指定した単位を確認する。
+
原典資料で使用されている数値の単位と拡張製品仕様書で使用する単位が異なる場合は、数値の変換が必要となる。
--
====

[requirement]
.不整合の対処方法
====
[%metadata]
identifier:: /att/quality/5
subject:: 標準作業手順
class:: 留意事項
[statement]
--
幾何オブジェクトは存在するが、記述すべき属性が既存資料等に無い、あるいは記述すべき属性が既存資料等に存在するが、該当する場所に幾何オブジェクトが無い、等の不整合が発見された場合には、<<toc2_04>>において決定した対処方法に従う。
--
====

// (((建築物)))

[requirement]
.建築物の属性「uro:city」の必須記述
====
[%metadata]
identifier:: /att/quality/6
subject:: 標準作業手順
class:: 留意事項
[statement]
--
建築物の属性uro:city（市区町村）は、必ず記述する。

* 都市ごとに建築物の表示／非表示を切り替える等、建築物の大まかな位置を把握するために使用されるため、uro:cityは必ずデータを作成する。
* 政令指定都市の場合は、「区」に該当するコードを選択する。

--
====

[requirement]
.建築物の用途列挙
====
[%metadata]
identifier:: /att/quality/7
subject:: 標準作業手順
class:: 留意事項
[statement]
--
複合的な用途を有する建築物について、それぞれの用途を記述したい場合にはbldg: usageを複数列挙する。

* 複数の用途を列挙する場合は、主たる用途を最初に記述する。

--
====

// (((汎用属性セット)))(((汎用属性)))

[requirement]
.コード型属性の追加
====
[%metadata]
identifier:: /att/quality/8
subject:: 標準作業手順
class:: 留意事項
[statement]
--
建築物以外の地物型にコード型の属性を追加する場合には、汎用属性セットにより、コードだけではなく、参照するコードリストの所在を対として追加する。

* 建築物以外の地物に属性を追加する仕組みとして、汎用属性（gen:genericAttribute）がある。しかしながら、汎用属性には、文字列型、数値型等があるもののコード型はない。
* そこで、コード型の属性を追加する場合には、汎用属性セットにより、コードだけではなく、参照するコードリストの所在を対として追加する。
** 汎用属性は、コードを記述する文字列型の汎用属性（name=”code”とする）と、コードが参照するコードリストの所在を記述する文字列型の汎用属性（name=”codeSpace”）を作成し、これらを汎用属性セットにより束ねる。
** コードに対応するコードリストを必ず作成する。

--
====

[requirement]
.不明値の指定方法
====
[%metadata]
identifier:: /att/quality/9
subject:: 標準作業手順
class:: 留意事項
[statement]
--
属性の値が不明である場合は、属性の型ごとに指定された不明を表す値を入力する。

* 属性の値が不明である場合は、属性の型ごとに指定された不明を表す値（<<tab-4-3>>）を入力する。
* ただし、コード値（gml:CodeType）及び真偽値（xs:boolean）については、以下とする。
** 真偽値（xs:boolean）は、はtrue又はfalseのみを値として取るため、属性を省略する。
** コード値（gml:CodeType）は、不明を表すコードが定義されている場合はこれを入力し、不明を表すコードが定義されていない場合は、属性を省略する。ただし、不明値の入力が必須の場合は、指定のコードリストを拡張し、不明値を示すコードを追加することを基本とする。

--
====

[[tab-4-3]]
[cols="3a,7a"]
.属性値が不明な場合の対応
|===
h| 属性の型 h| 不明な場合の対応
| xs:string | Nullと入力する。（半角英文字）
| xs:integer | -9999と入力する。
| xs:double | -9999と入力する。
| xs:date
| 年月日が分からない場合は、0001-01-01と入力する。 +
年のみ分かる場合はYYYY-01-01とし、年月のみ分かる場合はYYYY-MM-01とする。

| xs:boolean | 属性を省略する。
| xs:gYear | 0001と入力する。
| xs:nonNegativeInteger | 9999と入力する。
| gml:MeasureType, gml:LengthType | 値は-9999とし、単位は属性ごとに指定された単位を入力する。
| gml:MeatureOrNullListType | Null値の定義域にunknownを指定する。
| xs:anyURI | Nullと入力する。（半角英文字）

|===

　

[NOTE,type="explanation"]
--
必須ではない属性は省略できる。そのため、属性値が不明な場合は属性を省略することもできる。

ただし、属性を省略すると、不明だからデータがないのか、データが漏れている（エラー）なのかを区別できない。そこで、作成対象とするデータについては、属性値が不明な場合は<<tab-4-3>>に示す不明を表す値を入力する。
--

[requirement]
.NULL値と不明値の変換
====
[%metadata]
identifier:: /att/quality/10
subject:: 標準作業手順
class:: 留意事項
[statement]
--
(((標準製品仕様書)))
原典資料におけるNULL値や不明値の取り扱いに注意する。

* 原典資料がGISデータである場合、GIS独自のデータ形式の仕様により、NULL値の取り扱いが異なる。例えば、数値型の属性についてデータが無い場合に、「0」が入力されていることがある。この「0」はデータが無いことを意味するため、NULL値として取り扱うべきである。
* 値が不明な場合に、各原典資料の定義に従い「不明」や「9999」といった不明であることを示す文字列又は数値が入力されている。これらの不明値は、標準製品仕様書のデータ型やコードリストの定義に従い変換すること。 +
例えば、xs:gYear型（年）の値が不明な場合に、原典資料では「9999」となっていたとする。標準製品仕様書では、xs:gYear型（年）の値が不明な場合には、「0001」とするよう定められている。よって、「9999」は「0001」に変換しなくてはならない。

--
====

[requirement]
.主題属性の品質記録
====
[%metadata]
identifier:: /att/quality/11
subject:: 標準作業手順
class:: 留意事項
[statement]
--
主題属性の作成に関する品質情報を、都市オブジェクト毎に記録する。

全ての都市オブジェクトは、データの品質に関する情報を記録するデータ品質属性（uro:DataQualityAttribute）を作成しなければならない。このデータ品質属性は、主題属性に関する品質として以下の属性をもつ。

* 主題属性に使用した原典資料の種類

都市オブジェクトごとに、これらの情報を記録すること。
--
====

[[toc4_03_03]]
==== 実施すべき品質評価

「属性の追加」では、主として主題属性に関する品質評価を行う。属性の型は正しいか、定義域を満たしているか（論理一貫性）、正しい属性値が格納されているか（主題正確度）について評価する。 +
「属性の追加」において実施すべき品質評価を以下に示す。 +
品質要素ごとに分類された各番号は、((標準製品仕様書))に定義する品質要求及び評価手順の識別子である。(((位置正確度)))

* 完全性：C-bldg-01
* 論理一貫性：L04,L-bldg-03,L-bldg-04,L-bldg-05
* 位置正確度：―
* 主題正確度：T01,T02

((標準製品仕様書))の品質要求に追加又は変更を行った場合には、論理一貫性及び主題正確度についての品質評価を実施すること。
