[[toc1_03]]
=== 標準製品仕様書の使用
(((標準製品仕様書)))

((3D都市モデル))のユースケースに対して、必要となる地物型等が標準製品仕様書に定義された地物型等で網羅されている場合は、標準製品仕様書を使用する。

* 【手順】
* 手順1．標準製品仕様書に定義された地物型等の一覧（前項にて作成）のうち、ユースケースに必要（3D都市モデルとして整備する対象）となる地物型等について、「作成対象」欄に〇を付ける。また、作成対象とする属性及び関連役割の内、必須とする属性及び関連役割には、●を付ける。
+
なお、標準製品仕様書の使用にあたり、以下の点に留意する。

[requirement]
.品質要求の変更手順
====
[%metadata]
identifier:: /att/decision/2
subject:: 標準作業手順
class:: 留意事項
statement:: 標準製品仕様書に示された品質要求を変更したい場合は、標準製品仕様書の拡張に該当するため、<<toc1_05_01>>に従って品質要求を作成し、拡張製品仕様書にこれを含める。
====

(((建築物)))
[NOTE,type=commentary]
--
ユースケースに応じて、標準製品仕様書に示された品質要求よりも高い品質が求められる場合がある。そのような場合には、品質要求を変更できる。ただし、地物型等に要求されている品質を変更する場合には、その内容を拡張製品仕様書において定めなければならない。また、地物型ごとに適用する地図情報レベルを変更してもよい。

例：　道路には、地図情報レベル500を適用し、建築物には、地図情報レベル2500を適用する。

3D都市モデルの整備では、既存の測量成果等を活用することが想定される。これらを使用することでデータ整備の効率化を図ることができる。ただし、既存の測量成果等の使用が、ユースケースの品質要求に適合することを確認しなければならない。特に、既存の測量成果等から得られる位置正確度やその時点に注意する必要がある。
--

[requirement]
.コードリストの拡張
====
[%metadata]
identifier:: /att/decision/3
subject:: 標準作業手順
class:: 留意事項
[statement]
--
標準製品仕様書のコードリストは原則として変更しない。独自のコードリストを使用したい場合は、新たにコード型の属性を追加することを基本とする。コード型の属性の追加は標準製品仕様書の拡張に該当するため、<<toc1_04>>の手順に従い、拡張製品仕様書を作成する。

* 標準製品仕様書に定義されたコードリストは、原則としてそのまま使用する。ただし、標準製品仕様書でコードの追加やコードリストの作成が許容されている場合は、拡張製品仕様書において追加又は作成できる。
--
====

[NOTE,type=commentary]
--
標準製品仕様書に示すコードリストは、複数の都市間での比較や広域での集計に使用することを想定し、変更しない。都市ごとに詳細に設定されたコード区分を用いた可視化や分析を行う場合は、都市ごとに定められた定義域をもつ属性を追加する。

ただし、標準製品仕様書では、コード型として定義された属性のうち、コードリストの作成を拡張製品仕様書に委ねている場合やコードの追加を認めている場合がある。この場合は、都市ごとにコードを追加できる。
--

[requirement]
.地物型の省略手順
====
[%metadata]
identifier:: /att/decision/4
subject:: 標準作業手順
class:: 留意事項
[statement]
--
(((標準製品仕様書)))
標準製品仕様書の地物型等を使用しない場合は、以下の3点を行う。

* 拡張製品仕様書に、作成範囲を示す一覧（本手順で作成する、標準製品仕様書に定義された地物型等のうち、いずれを作成対象とするかを示したもの）を付す。
* 応用スキーマ単位で作成対象外とする場合には、標準製品仕様書の項番号は残したまま、応用スキーマクラス図及び応用スキーマ文書を削除する。
* 応用スキーマのうち、一部を作成対象外とする場合は、応用スキーマクラス図及び応用スキーマ文書を削除しない。

--
====

[NOTE,type=commentary]
--
各都市におけるユースケースを実現する際に、標準製品仕様書に定義している地物型等が不要の場合には、これらのデータ整備を省略できる。

この場合には、手順1．で作成した地理空間データの作成範囲を標準製品仕様書に付することで、整備する3D都市モデルの製品仕様とする。
--

[requirement]
.必須属性の明確化
====
[%metadata]
identifier:: /att/decision/5
subject:: 標準作業手順
class:: 留意事項
[statement]
--
作成対象とする属性や関連役割のうち、必ず作成すべきものとそうではないものを明確にする。

* 対象とする地物型等の一覧において、必ず作成する属性及び関連役割には「●」、作成しない場合もある属性及び関連役割には「〇」を付ける。
--
====

[NOTE,type=commentary]
--
CityGMLやi-URでは様々なユースケースで利用されることを想定し、全ての属性や関連役割が任意項目（オプション）と設定されている。しかしながらユースケースによっては、任意ではなく、必須の項目としたい場合もある。そこで、必須とすべき対象を明確にするため、対象とする地物等の一覧において、任意項目として作成するのか、あるいは、必須項目として作成すべきなのかを示す。

ここで必須項目とする属性又は関連役割は、品質評価（4章参照）において完全性の評価を行わなければならない。
--

// (((3D都市モデル)))(((建築物)))

[requirement]
.LODの適用決定
====
[%metadata]
identifier:: /att/decision/6
subject:: 標準作業手順
class:: 留意事項
[statement]
--
空間属性に適用すべきLOD（Level of Detail）を決定する。

* LODが細分されている地物型を作成対象とする場合は、<<tocC>>以降に示す、各LODの定義を参考に、3D都市モデルとして作成すべきLODを決定する。
* 建築物モデル以外の地物型（例：橋梁、都市設備）は、上位となるLODの空間属性を作成対象とする場合、下位となるLODの空間属性の作成を必須としていない。ただし、多様なユースケースでの利用を見据え、下位のLODについても作成することを推奨する（例えば、都市設備モデル（LOD3）を作成する場合、都市設備モデル（LOD1）及び都市設備モデル（LOD2）をセットで作成することが望ましい）。

--
====

(((建築物)))(((立体)))
[NOTE,type=commentary]
--
LODとは、詳細さの度合い（詳細度）であり、CityGMLにおいて定義されている、一つの都市オブジェクトの空間属性をその利用や可視化の目的に応じて、複数の段階に抽象化することを可能とする、マルチスケールなモデリングの仕組みである。

CityGMLでは、LOD0からLOD4までの五段階を定義しており、標準製品仕様書では、LOD0からLOD4までを対象としている。LOD0からLOD3までは外部を対象とし、LOD4は外部に加えて、内部も対象とする。LOD0が最も粗く、LOD4が最も詳細な段階となる。LODが高いほど形状がより詳細に記述可能となる。また、地物型によっては、LODが高くなるにつれ、地物型も細かく細分される。

例えば、建築物の場合、LOD0は建築物の外形となる平面で表現されるが、LOD1では平面を上向きに押し出した立体（箱モデル）となる。LOD2やLOD3では建築物の形状をより詳細に表現することができる。LOD2では建築物の屋根面や外壁面といった地物型に区分することができ、LOD3では屋根面や外壁面に加えて窓や扉を記述することができる。また、LOD4ではLOD3の外部の表現に加えて、部屋や家具といった内部の記述が可能となる。

LODが高くなればなるほど3D都市モデルに含まれる情報量は増え、利用可能なユースケースも増える。しかしながら、データを作成するためにより詳細な原典資料が必要となり、データ作成のコストが増大する。

そのため、ユースケースを踏まえ、適切なLODを選択する必要がある。

標準製品仕様書では、データの内容や構造の選択肢が複数存在する地物型については、データ作成の実現性の観点から各LODを細分し、それぞれの取得基準を定めている。LODの選定においては、これを考慮すること。
--
