[[toc1_02]]
=== 標準製品仕様書との比較
(((標準製品仕様書)))

((3D都市モデル))に必要な情報を整理し、標準製品仕様書に定義された地物型等と比較する。これにより、((拡張製品仕様書))に含むべき地物型等（作成すべき地理空間データの範囲）を明らかにする。

* 【手順】(((3D都市モデル)))
* 手順1．3D都市モデルのユースケースに基づき、必要となる情報を、地物型等として整理する。
** 地物属性の型は、標準製品仕様書「4.3.1基本データ型」に示す地物属性の型を参考にする。
* 手順2．手順1．の整理結果と、標準製品仕様書に定義された地物型等とを比較する。
** 比較に際しては、標準製品仕様書の地物型等一覧（<<tocA_03_01>>）を用いる。
** 地物型、地物属性、地物関連のそれぞれについて比較する。
** 地物属性の型や地物関連の相手先となる地物型等が合致するか否かも比較する。
* 手順3．必要な地物型等が、標準製品仕様書に網羅されている場合は、3D都市モデルの整備には標準製品仕様書を使用する。
** 標準製品仕様書の使用は、<<toc1_03>>に示す手順に従う。
* 手順4．必要な地物型等が、標準製品仕様書では不足する場合は、標準製品仕様書を拡張する。
** 拡張製品仕様書への追加は、<<toc1_04>>に示す手順に従う。

[NOTE,type=commentary]
--
本工程の目的は、「標準製品仕様書にユースケースに必要な情報が網羅されているか否か」を確認し、その製品仕様（拡張製品仕様書）を決定することである。本工程に先立ち、あらかじめユースケース及びそれに必要な情報を整理しておかなければならない。

なお、標準製品仕様書では、「1．都市に関わる様々な地理空間データを格納する基盤」「2．3次元空間における都市計画決定情報の可視化」「3．災害リスク情報の3次元可視化」の三つのユースケースを設定しているが、都市の規模や環境によって、同じユースケースであっても必要となる情報が異なる可能性に注意すること。

例えば、3次元空間における都市計画決定情報の可視化に使用する都市計画基礎調査等の情報は、各都市において属性情報が異なることが想定される。また、災害リスク情報の3次元可視化では、都市が沿岸部に存在するのか、山間部に存在するのか等、その立地条件によって考慮すべき災害リスクは異なる。
--

// (((都市計画決定情報)))(((建築物)))

[requirement]
.拡張製品仕様書に含めることが望ましい地物型等について
====
[%metadata]
identifier:: /att/decision/1
subject:: 標準作業手順
class:: 留意事項
[statement]
--
拡張製品仕様書に含めることが望ましい地物型

* 「拡張製品仕様書に含めることが望ましい地物型とLODの組み合わせ」（<<tab-1-1>>）として「基本セット」に含まれる「建築物」、「道路」、「都市計画決定情報」、「土地利用」、「災害リスク」及び「地形」の各地物型は、ユースケースの利用有無によらず、3D都市モデルに含むことが望ましい。
* これらの地物型に定義された地物属性のうち、主題属性（名称や種類、面積など、図形以外の属性）について、拡張製品仕様書に含むことが望ましい主題属性を「<<tocA>>拡張製品仕様のための様式」の「取得項目一覧」に示す。
* 拡張製品仕様書に含むべき地物型等の選定においては、「取得項目一覧」を参考にすること。
--
====

[NOTE,type=commentary]
--
本書では、3D都市モデルの再利用性を高めるため、「拡張製品仕様書に含めることが望ましい地物型とLODの組み合わせ」（<<tab-1-1>>）として、「基本セット」を示している。基本セットは、建築物、道路、都市計画決定情報、土地利用、災害リスク及び地形の各地物型を含む。これらの地物型は様々なユースケースで利用されることが想定される地物型である。そのため、想定したユースケースでの利用有無によらず3D都市モデルに含めることが望ましい。これによりオープンデータとしての利用価値が向上する。

一方、基本セットに含まれる地物型をユースケースで利用しない場合には、どの地物属性を整備対象とすべきかを決定することが困難となる。そこで本書では、基本セットに含まれる地物型の主題属性（名称や種類、面積など、図形以外の地物属性）について、標準製品仕様として必須となる主題属性と、都市計画基礎調査や都市計画決定情報のように各都市で保有するデータや、国土数値情報や国土地理院ベクトルタイル等のオープンデータを活用して入力できる主題属性を、想定される原典資料とともに整理し、「<<tocA>>拡張製品仕様のための様式」の「取得項目一覧」に示している。基本セットに含まれる地物型の主題属性の選定にあたっては、「取得項目一覧」を参考にするとよい。

なお、「取得項目一覧」では、基本セットに含まれる地物型の主題属性について、必須となる主題属性に「●」、都市計画基礎調査等の既存データを利用して入力可能な主題属性に「〇」を付けている。「●」となっている主題属性は、必ず作成しなければならない。また、「〇」となっている主題属性は、都市計画基礎調査や都市計画決定情報のGISデータ等、利用可能な原典資料が存在する場合には、原則として作成する。空欄となっている主題属性は、必要に応じて作成する。
--
