[[toc1_05]]
=== 拡張製品仕様書の作成
(((拡張製品仕様書)))
前項までにおいて、各都市のユースケースに必要な情報について、標準製品仕様書の定義をそのまま適用する地物型等や、標準製品仕様書では不足するため新たに追加した地物型等を決定した。本項ではこれらを取りまとめ、拡張製品仕様書を作成する手順を示す。 +
なお、((3D都市モデル))の製品仕様書として、データ製品が作成された日付や空間的な範囲、問合せ先等を示す必要があるため、[underline]##地物型等の拡張が無い場合も、3D都市モデルごとの拡張製品仕様書を作成する##ことになる。

[[toc1_05_01]]
==== データ品質の決定

以下に該当する場合は、品質要求及び評価手順を決定し、拡張製品仕様書に示されなければならない。(((標準製品仕様書)))

* 標準製品仕様書にない地物型、地物属性又は地物関連を新たに追加した場合
* 標準製品仕様書定義された品質要求を変更する場合

品質要求及びその評価手順の作成には、<<tocA_03_07>>に示す様式を用いる。品質要求及びその評価手順の作成は、国土交通省国土地理院「品質の要求、評価及び報告のための規則」に従うこと。

手順：

1）地理空間データに求める品質（地理空間データに含まれるべきでないエラーの内容）を整理する。

* 整理した全ての品質要求に対して、個々を識別する識別子を与える。
* 以降の手順は、識別子を与えた全ての品質要求について実施する。

2）「品質の要求、評価及び報告のための規則」に定義された品質要素から、1）に適合する品質要素（<<tab-1-10>>）を選択する。

[[tab-1-10]]
[cols="1a,3a,6a"]
.品質要素
|===
2+| 品質要素 | 概要

2+| 完全性 | 地物、地物属性及び地物間関係の存在及び欠落
.2+| | 過剰 | データ集合内の過剰なデータの存在
| 漏れ | データ集合内のデータの欠落
2+| 論理一貫性 | データの構造、属性及び関係に関する論理的規則の遵守度合い
.4+| | 書式一貫性 | データがデータ集合の物理的構造に従って格納されている度合い
| 概念一貫性 | 概念スキーマ規則の厳守
| 定義域一貫性 | 値定義域に対する値の厳守
| 位相一貫性 | データ集合に関して明示的に符号化した位相的特性の正しさ
2+| 位置正確度 | 空間参照系内の地物の位置の正確度
.3+| | 絶対正確度又は外部正確度 | 報告された座標値と採択された値又は真とみなす値との近さ
| 相対正確度又は内部正確度 | データ集合内の地物の相対位置と採択された個々の相対位置又は真とみなす個々の相対位置との近さ
| グリッドデータ位置正確度 | グリッドデータ位置と採択された値又は真とみなす値との近さ
2+| 時間正確度 | 地物の時間属性及び時間関係の品質
.3+| | 時間測定正確度 | 報告された時間測定と、真と採択された値もしくは真とみなす値との近さ
| 時間一貫性 | 報告された事象の順序の正しさ
| 時間妥当性 | データの時間に関する妥当性
2+| 主題正確度 | 地物の分類の正しさや主題属性の値の正しさ
.3+| | 分類の正しさ | 地物又はその属性に割り当てられた分類と論議領域との比較
| 非定量的属性の正しさ | 非定量的属性が正しいか否かについての評価尺度
| 定量的属性の正確度 | 定量的属性値と、真として採択された値もしくは真とみなす値との近さ

|===

3）「品質の要求、評価及び報告のための規則」5．品質要求のための規則に従い、品質要求の項目として「データ品質適用範囲」及び「データ品質評価尺度」を定める。

* 「データ品質適用範囲」は品質評価の対象である。1）に関係する地物型/地物属性/地物関連を特定し、設定する。このとき、複数の地物型/地物属性/地物関連は、まとめてデータ品質適用範囲と設定してもよい。
* 「データ品質評価尺度」は、エラーの定義、エラーの数え方等、品質を定量的な数値で記述するための基準である。

4）合否判断の基準（適合品質水準）を決定する。

5）2）～4）を踏まえ、品質評価手法を決定する。品質評価手法の決定に当たっては、「品質の要求、評価及び報告のための規則」6．品質評価のための規則に従い、データ品質評価尺度を適用するための手順（規定された方法）を記述する、又はその記述を含む文書（例えば、認定済の日本産業規格など）を引用する。また、参照データの名称も示す。 +
品質評価手法の決定においては、関連するオープンソースソフトウェアがProject"PLATEAU"公式GitHubリポジトリに公開されており、それらを利用しても良い（https://github.com/Project-PLATEAU/ ）。<<tocW>>に、オープンソースソフトウェアが対応する品質評価項目を示す。


品質要求及び評価手法の例を<<tab-1-11>>に示す。

[[tab-1-11]]
[cols="3a,17a"]
.品質要求及び評価手法の例
|===
h| No. h| LO1
h| 品質要素 h| 論理一貫性・書式一貫性
h| 品質適用範囲 | データ製品に含まれる全ての都市モデル（core:CityModel）のインスタンス。
h| 品質評価尺度 | 整形式（Well-Formed XML）になっていない箇所数。
h| 適合品質水準 | エラーの箇所数が0の場合に合格。エラーの箇所数が1以上の場合は不合格。
h| 品質評価手法
| 全数・自動検査を実施する。

1．検査プログラム（XMLパーサなど）によって、都市モデルの書式が、XML文書の構文として正しくない箇所を数える。

|===

// (((建築物)))(((標準製品仕様書)))

[requirement]
.品質基準の柔軟性
====
[%metadata]
identifier:: /att/decision/7
subject:: 標準作業手順
class:: 留意事項
[statement]
--
地物型等により、要求する品質及び品質評価手法を変えることができる。

* 標準製品仕様では、データ製品が満たすべき位置正確度として、外部位置正確度における地図情報レベル2500を基本とする。
** ただし、建築物には地図情報レベル2500、道路には地図情報レベル500というように、ユースケースに応じて地物型ごとに変更できる。
* また、標準製品仕様書では、<<gsi_map_level_dps,地図情報レベル2500数値地形図データ作成のための標準製品仕様書（案）>>を参考に品質評価手法を定めている。拡張製品仕様書におけるデータ品質の決定においても、これを参考にするとよい。

--
====

[requirement]
.位置精度の選定
====
[%metadata]
identifier:: /att/decision/8
subject:: 標準作業手順
class:: 留意事項
[statement]
--
適切な位置正確度の適合品質水準を選択する。

* 拡張製品仕様書では、各都市のユースケースに基づき、適切な地図情報レベルに応じた位置正確度の適合品質水準を選択すること。
** 作業規程の準則では標高点や等高線以外の地物についての高さ方向の指標が無い。そのため、標準製品仕様では、各地図情報レベルにおける標高点や等高線の標準偏差（<<table-1-12>>）を参考に、地図情報レベルごとの適合品質水準を定めている。拡張製品仕様では、各都市のユースケースに基づき、適切な地図情報レベルを選択する必要がある。

--
====

[[table-1-12]]
[cols="a,a,a,a,a"]
.新規測量における数値地形図データの位置精度及び地図情報レベル（作業規程の準則第106条）
|===
| 地図情報レベル | 水平位置の標準偏差 | 標高点の標準偏差 | 等高線の標準偏差 | 相当する地形図の縮尺

|  500 |  0.25m以内 |  0.25m以内 |  0.5m以内 |  1/500
|  1000 |  0.70m以内 |  0.33m 以内 |  0.5m以内 |  1/1,000
|  2500 |  1.75m以内 |  0.66m以内 |  1.0m以内 |  1/2,500

|===


　


[NOTE,type=commentary]
--
標準製品仕様書の品質要求は、2次元の地理空間データの基盤として整備・活用されている基盤地図情報の、原形データベース仕様（<<gsi_map_level_dps,「基盤地図情報　原形データベース　地理空間データ製品仕様書（案）」>>）に示された品質要求を参考として適合性品質水準（誤率等）や品質評価手法（抜取検査等）を設定している。しかしながら、ユースケースによっては、より高い適合性品質水準を求める場合や、より厳密な品質評価を求める場合も想定される（例：人命にかかわるユースケース）。

品質要求を高くすることは、原典資料（データ取得の拠り所となる資料）やデータ整備方法、品質評価方法に影響を与え、3D都市モデルの整備費用に反映される場合が多く、品質と費用はトレードオフの関係にある傾向にある。ユースケースの実現により得られる効果と3D都市モデルの整備にかかる費用との均衡点を見つけることも重要となる。
--

[[toc1_05_02]]
==== 製品仕様の作成

前項までの結果を集約・整理し、各都市における拡張製品仕様書を作成する。拡張製品仕様書には<<tab-1-13>>に示す項目を示さなければならない。 +
((標準製品仕様書))は汎用的な記載となっている。そのため、個々の地理空間データに応じた製品仕様として記載を具体化する必要がある。拡張製品仕様書の作成には、<<tocA>>に示す様式を使用して前項までに作成した結果と、拡張製品仕様書のテンプレートを用いる。拡張製品仕様書の作成においては、国土交通省国土地理院が作成した「<<gsi_geospatial_dps_manual,地理空間データ製品仕様書作成マニュアル>>」を参照すること。

[[tab-1-13]]
[cols="1,3"]
.製品仕様書の構成
|===
^| データ製品仕様書の構成 ^| 記載内容

| 1. 概覧 | データ製品（地理空間データ）の概要として、データ製品仕様の作成に関する情報、利用目的（ユースケース）、対象とする範囲等
| 2. 適用範囲 | データ製品仕様が適用される範囲
| 3. データ製品識別 | データ製品の名称、日付、問合せ先、地理記述
| 4. データの内容及び構造 | 作成する/された地理空間データの内容と構造
| 5. 参照系 | 地理空間データの空間的・時間的位置を特定するための基準
| 6. データ品質 | 地理空間データが利用目的に合致するために保証しなければならない品質の基準
| 7. データ製品配布 | 地理空間データが記録されるデータフォーマットと記録される媒体
| 8. メタデータ | 地理空間データを説明するためのデータ（メタデータ）の仕様
| 9. その他 | 地理空間データを作成または作成された地理空間データを使用する際に重要となる事項

|===

手順：(((標準製品仕様書)))

1）製品仕様の記載事項（<<tab-1-14>>）に従い、データ製品の仕様を記述する。 +
記述には、拡張製品仕様書のテンプレートを使用する。テンプレートは、以下よりダウンロードできる。 +
URL： https://www.mlit.go.jp/plateau/file/libraries/doc/template.zip

2）標準製品仕様書を拡張した内容について、前項までに作成した表を添付する。 +
<<tocA_03_01>>により整理した、取得対象とする地理空間データの一覧と、拡張の内容に応じて、<<tab-1-15>>の各表を付し、拡張製品仕様書とする。

[[tab-1-14]]
[cols="3,6a,11a"]
.製品仕様書の記載事項
|===
2+^h| データ製品仕様書の構成 ^h| 記載内容
.6+| 1. 概覧 | 1.1 データ製品仕様の作成情報 | 題名は、「XXXXX3D都市モデル拡張製品仕様書」とする。 +
 XXXXXには、対象とする都市（基礎自治体）の名称を入れる。 +
日付は、拡張製品仕様書を作成した日付とし、作成者は、拡張製品仕様書の作成を所管した機関とする。分野には、「都市」に加え、ユースケースを端的に表現する単語を入れる（例：防災）
| 1.2 目的 | データ製品が対象とするユースケースを記載する。
| 1.3 製品の範囲 | 空間範囲をデータ製品が対象とする都市の名称に変更する。
| 1.4 引用規格等 | 引用規格等として、以下を追加する

* 3D都市モデル標準データ製品仕様書　第4.X版
* 3D都市モデル標準作業手順書　第4.X版 その他、データ製品仕様の拡張にあたり、引用した法令・規格・仕様がある場合には追加する。

| 1.5 用語と定義 | 拡張したデータ製品仕様に専門的な用語が含まれる場合にはその用語と定義を追加する。
| 1.6 略語 | 拡張したデータ製品仕様に略語が含まれる場合にはその用語と定義を追加する。
2+| 2. 適用範囲 | 範囲の名称を「XXXXXにおける3D都市モデル拡張製品仕様適用範囲」とする。XXXXXには、対象とする都市の名称を入れる。
.4+| 3. データ製品識別 | 3.1 データ製品の名称 | 「``3D都市モデル\_[都市コード]_[提供者区分]\_[整備年度]_[オプション]``」とする。

``[都市コード]``は、3D都市モデルの作成範囲となる都市を示すコードとし、作成範囲が市区町村の場合は``JIS X0401``に示される2桁の都道府県コードと``JIS X0402``に示される市区町村コードを加えた5桁）を記載する。作成範囲が都道府県の場合は、``JIS X0401``に示される2桁の都道府県コードとする。  +
``[提供者区分]``は、3D都市モデルの提供者を識別する文字列である。成果品のフォルダ名に使用する``[提供者区分]``に一致する。 +
``[整備年度]``には、3D都市モデルを構築した西暦年度を半角4桁の数字で記載する。成果品のフォルダ名に使用する``[整備年度]``に一致する。 +
``[オプション]``は、複数種類のデータ製品が同一都市かつ同一年度に作成される場合にこれらを識別するための任意の文字列とする。半角英数字のみ使用できる。
| 3.2 データ製品の日付 | 3D都市モデルを構築した日付とする。3D都市モデルの構築にかかる業務発注の際の仕様書等により指定された日付がある場合には、その日付を採用する。
| 3.3 データ製品の問合せ先 | 3D都市モデルを作成する都市の問合せ窓口（担当部局、連絡先）を記載する。
| 3.4 データ製品の地理記述
| 3D都市モデルを作成する都市の名称を記述する。 +
複数の都道府県や市区町村が含まれている場合には、それぞれを列記する。

.3+| 4. データの内容及び構造 | 4.1はじめに | データ製品仕様が対象とする地物型等の一覧を示す。
| 4.2 応用スキーマクラス図 | i-URやCityGMLに定義された地物型等を追加した場合には、該当するクラス図を追加する。

なお、i-URやCityGMLの仕様書に示されたクラス図を転載する場合には、その出典を記載すること。
| 4.3 応用スキーマ文書
| 地物型等を追加した場合には、作成した応用スキーマ文書を追加する。 +
コードリストを作成した場合には作成したコードリストを追加する。

2+| 5. 参照系 | 変更しない。
| 6. データ品質 | 6.3 品質要求及び評価手順 | 地物型等を追加した場合には、これに対して要求する品質を示す。

定義済みの品質要求を変更した場合にはこれを示す。
| 7. データ製品配布 | 7.2 配布媒体情報 | 成果品のフォルダ構成を示す。 +
追加した地物のファイル名を分ける場合など、ファイルのオプションを使って地物のファイルを分割する場合には、ファイル名のオプションの一覧を付すこと。 +
災害リスク情報は都市ごとに作成されるサブフォルダが異なるため、データ製品に含まれるサブフォルダの一覧を付すこと。
2+| 8. メタデータ | 必要な場合には、メタデータの作成単位を設定する。
2+| 9. その他 | 作成したデータ製品の使用にあたり、留意事項がある場合にはこれを記載する。

|===

[[tab-1-15]]
[cols="a,5a,^a,^a,^a,^a,^a,^a,^a,5a",options="noheader"]
.拡張製品仕様書に必要な様式
|===
2.3+^h| 拡張の内容 7+^h| 様式（●：必ず作成、〇：条件に応じて作成） .3+^h| 備考
^h| A.3.1 ^h| A.3.2 ^h| A.3.3 ^h| A.3.4 ^h| A.3.5 ^h| A.3.6 ^h| A.3.7
h| 地物一覧 h| コードリスト h| 拡張属性 h| 　定義文書 h| 汎用オブジェクト h| 汎用属性 h| 　品質

.2+| 「建築物」に地物属性/地物関連を追加 | コード値型の地物属性を追加 | ● | ● | ● |  |  |  | 〇 |
| コード値型以外の地物属性/地物関連を追加 ^| ● |  |  | ● |  | ● | 〇 |
2+| i-URまたはCityGMLに存在する地物型等を追加 ^| ● | 〇 |  | ● |  |  | 〇 | コード値型の属性を追加する場合は、コードリストを作成する。
.2+| i-URまたはCityGMLに存在しない地物型等を追加 | GenericCityObjectによる地物型の追加 | ● |  |  |  | ● |  | ● |
| GenericAttributeによる地物属性/地物関連の追加 ^| ● | 〇 |  |  |  | ● | ● | コード値型として汎用属性セットを追加する場合には、コードリストを作成する。

|===

拡張製品仕様書の作成における留意事項を以下に示す。

// (((3D都市モデル)))

[requirement]
.オープンデータ仕様書
====
[%metadata]
identifier:: /att/decision/9
subject:: 標準作業手順
class:: 留意事項
[statement]
--
成果品となる3D都市モデルを加工し、オープンデータ化可能な3D都市モデルを別途作成する場合には、オープンデータ用の拡張製品仕様書も作成すること。

* 3D都市モデルは、特定のユースケースだけではなく、様々な分野で活用されることで新たな価値を創出することが期待されている。そのため、3D都市モデルを幅広く公開することが望ましい。一方で、ユースケースによっては、個人情報保護の観点等からオープンデータとして適切ではない情報項目が含まれている可能性がある。その場合には3D都市モデルからオープンデータ化可能な項目を抽出した、オープンデータ用の3D都市モデルを作成する（<<toc5_02>>参照）。
* オープンデータ用の3D都市モデルを作成する場合は、これの製品仕様を示す製品仕様書を作成すること。

--
====

[[toc1_05_03]]
==== 作成制限施設の確認
(((作成制限施設)))(((建築物)))

本ドキュメントの作成主体である国土交通省都市局は、国の安全保障又は警備上の理由から作成を制限すべき((3D都市モデル))の地物等について関係機関と協議し、以下のとおり作成制限施設の規則を決定した。((3D都市モデル))の作成主体である地方公共団体及び受託事業者であるモデル整備事業者においては、((3D都市モデル))の作成に当たっては、作成対象地物が本規則を遵守したものかを確認しなければならない。

* 地物型「bldg:Building（建築物）」について、<<tab-1-16>>で示す対象施設類型に従い、作成制限を行う。例えば、「防衛関係施設」についてはデータを作成してはならない（削除）。「裁判所関係施設」については、LOD2まで作成可能である。
* 対象施設の定義については<<tab-1-17>>を参照すること。対象エリア内にある施設が該当施設類型に当たるか不明な場合等は、下記連絡先まで問い合わせること。
* 該当施設のデータ整備が特定の利用目的等のために必要な場合は、個別に当該施設管理者と協議し、許諾等を取得すること。
* 警察関係施設が入居している民間施設のLOD3以上を作成する場合には、具体的な表示方法について、当該警察関係施設の管理者と協議すること。
* 当該空港を含めた空港について、空港管理者及び空港管理者の委託を受けた事業者等がLOD3以上のデータの作成を要望する場合は下記の連絡先に記載された空港所管課と協議すること。なお、当該空港も含めた空港を整備する場合にあっては、空港保安上公開すべきでないエリア・構造等について、必要な作成制限をすること。具体的な表示方法については、当該空港管理者と協議すること。

[[tab-1-16]]
[cols="3a,^a,^a,^a,^a"]
.作成制限施設の規則
|===
| 対象施設類型/作成制限 | LOD1 | LOD2 | LOD3 | LOD4

h| 宮内庁所管施設 | × | × | × | ×
h| 防衛関係施設 | × | × | × | ×
h| 裁判所関係施設 | 〇 | 〇 | × | ×
h| 警察関係施設 | 〇 | 〇 | × | ×
h| 刑務所等 | 〇 | 〇 | × | ×
h| 外国公館等 | 〇 | 〇 | × | ×
h| 空港 | 〇 | 〇 | × | ×
h| 原子力事業所 | × | × | × | ×

|===

[%key]
〇:: 作成可
×:: 作成不可

[[tab-1-17]]
[cols="1a,4a"]
.対象施設類型の定義
|===
| 対象施設類型 | 定義

h| 宮内庁所管施設 | 重要施設の周辺地域の上空における小型無人機等の飛行の禁止に関する法律（平成二十八年法律第九号）第２条第１項第１号ホに定める施設及びその他の皇室関連施設
h| 防衛関係施設 | 防衛省・自衛隊及び在日米軍関係施設
h| 裁判所関係施設 | 裁判所法（昭和二十二年法律第五十九号）に定める下級裁判所の庁舎
h| 警察関係施設 | 警察庁、警察庁分庁舎、管区警察局、管区警察局分庁舎、警察大学校、警察学校、科学警察研究所、科学捜査研究所、警察本部、警察本部分庁舎、執行隊庁舎、警察広報施設、訓練場、留置施設、車両整備工場、宿舎、公舎、少年センター、警察犬訓練所、運転免許センター、運転免許試験場、交通管制センター、交通反則通告センター、駐車違反処理センター、警備派出所、警察署、警察署分庁舎、交番、駐在所、その他警察の職務に供される施設
h| 刑務所等 | 法務省設置法（平成十一年法律第九十三号）第8条第１項に定める施設
h| 外国公館等 | 大使館（大使公邸を含む。）、外交官の個人的住居、領事館（（総）領事公邸及び領事官の住居の不可侵又は保護に関する規定を有する二国間領事条約（協定）を有する国については、領事官の住居を含む。）及び国際機関本部・駐日事務所
h| 空港 | 重要施設の周辺地域の上空における小型無人機等の飛行の禁止に関する法律（平成二十八年法律第九号）第2条第4号に定める施設
h| 原子力事業所 | 重要施設の周辺地域の上空における小型無人機等の飛行の禁止に関する法律（平成二十八年法律第九号）第2条第5号に定める施設

|===

<連絡先>

* 宮内庁所管施設：宮内庁管理部管理課管財第一係　電話番号：03-3213-1111（内線3481、3482）
* 防衛関係施設：防衛省調査課　代表番号：03-3268-3111(内線20442、20432)
* 裁判所関係施設：最高裁判所事務総局経理局管理課　直通番号：03-4233-5437
* 警察関係施設：<<tab-1-18>>を参照
* 刑務所等：法務省矯正局成人矯正課警備対策室　直通番号：03-3592-7371
* 外国公館等：外務省儀典外国公館室　直通番号03-5501-8042
* 空港：国土交通省航空局安全部安全企画課航空保安対策室　番号：03-5253-8111（内線48141）

[[tab-1-18]]
[cols="^a,^a,^a",]
.警察関係施設の連絡先
|===
.2+h| 2+^h| 連絡先
^h| 所属 ^h| 電話番号
|  東北管区警察局 |  総務監察・広域調整部警務課 |  022-221-7181（内線2641）
|  関東管区警察局 |  総務監察部警務課 |  048-600-6000（内線2622）
|  中部管区警察局 |  総務監察・広域調整部警務課 |  052-951-6000（内線2631）
|  近畿管区警察局 |  総務監察部警務課 |  06-6944-1234（内線2621、2622）
|  中国四国管区警察局 |  総務監察・広域調整部警務課 |  082-228-6411（内線2642）
|  四国警察支局 |  四国警察支局警務・監察課 |  087-821-3111（内線2612）
|  九州管区警察局 |  総務監察部警務課 |  092-622-5000（内線2612）
|  北海道 |  総務部施設課 |  011-251-0110（内線2272）
|  青森県 |  警務部警務課 |  017-723-4211（内線2654）
|  岩手県 |  警務部警務課 |  019-653-0110（内線2643）
|  宮城県 |  警務部警務課 |  022-221-7171（内線2625）
|  秋田県 |  警務部警務課 |  018-863-1111（内線2632、2636）
|  山形県 |  警務部施設装備課 |  023-626-0110（内線2282）
|  福島県 |  警務部施設装備課 |  024-522-2151（内線2322）
|  警視庁 |  総務部施設課 |  03-3581-4321（内線22601）
|  茨城県 |  警務部警務課 |  029-301-0110（内線2651、2652）
|  栃木県 |  警務部警務課 |  028-621-0110（内線2643）
|  群馬県 |  警務部装備施設課 |  027-243-0110（内線2281）
|  埼玉県 |  総務部財務局施設課 |  048-832-0110（内線2283）
|  千葉県 |  警務部警務課 |  043-201-0110（内線2623）
|  神奈川県 |  総務部施設課 |  045-211-1212（内線2292）
|  新潟県 |  警務部警務課 |  025-285-0110（内線2672）
|  山梨県 |  警務部警務課 |  055-221-0110（内線2663）
|  長野県 |  警務部会計課 |  026-233-0110（内線2236）
|  静岡県 |  総務部施設課 |  054-271-0110（内線2272）
|  富山県 |  警務部警務課 |  076-441-2211（内線2644）
|  石川県 |  警務部警務課 |  076-225-0110（内線2654）
|  福井県 |  警務部会計課 |  0776-22-2880（内線2238）
|  岐阜県 |  総務室装備施設課 |  058-271-2424（内線2282）
|  愛知県 |  警務部警務課 |  052-951-1611（内線2638）
|  三重県 |  警務部総務課 |  059-222-0110（内線2143）
|  滋賀県 |  警務部警務課 |  077-522-1231（内線2662、2633、2634）
|  京都府 |  総務部会計課 |  075-451-9111（内線2273）
|  大阪府 |  総務部施設課 |  06-6943-1234（内線22721）
|  兵庫県 |  警務部警務課 |  078-341-7441（内線2653）
|  奈良県 |  警務部施設装備課 |  0742-23-0110（内線2272）
|  和歌山県 |  警務部会計課 |  073-423-0110（内線2269）
|  鳥取県 |  警務部警務課 |  0857-23-0110（内線2636）
|  島根県 |  警務部警務課 |  0852-26-0110（内線2625）
|  岡山県 |  警務部警務課 |  086-234-0110（内線2671）
|  広島県 |  総務部施設課 |  082-228-0110（内線2265）
|  山口県 |  警務部警務課 |  083-933-0110（内線2635）
|  徳島県 |  警務部総務課 |  088-622-3101（内線2657）
|  香川県 |  警務部会計課 |  087-833-0110（内線2272）
|  愛媛県 |  警務部警務課 |  089-934-0110（内線2646）
|  高知県 |  警務部警務課 |  088-826-0110（内線2662）
|  福岡県 |  総務部施設課 |  092-641-4141（内線2265）
|  佐賀県 |  警務部警務課 |  0952-24-1111（内線2633）
|  長崎県 |  警務部警務課 |  095-820-0110（内線2631）
|  熊本県 |  警務部総務課 |  096-381-0110（内線2146）
|  大分県 |  警務部警務課 |  097-536-2131（内線2624）
|  宮崎県 |  警務部施設装備課 |  0985-31-0110（内線2272～2274）
|  鹿児島県 |  警務部警務課 |  099-206-0110（内線2621）
|  沖縄県 |  警務部警務課 |  098-862-0110（内線2633）

|===

